### ISSUE TITLE
VolumeClaimsTemplate definitions are not respected, and the defaults are being used 

### ISSUE THREAD

**Issue by guitcastro** [mongodb/mongodb-kubernetes-operator#1009]
**What did you do to encounter the bug?**

Try to use custom storage class, like this:

 ```
statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongodb-agent
              readinessProbe:
                failureThreshold: 40
                initialDelaySeconds: 5
                timeoutSeconds: 30
              resources:
                limits:
                  cpu: 100m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
            - name: mongod
              resources:
                limits:
                  cpu: 200m
                  memory: 512Mi
                requests:
                  cpu: 200m
                  memory: 256Mi
          volumeClaimTemplates:
            - metadata:
                name: data-volume
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
                storageClassName: regional-pd
```

**What did you expect?**

PVC created using the regional-pd class

**What happened instead?**

The default 10Gi data PVC is being created 

**Operator Information**
 - 0.7.3
 - docker.io/mongo:5.0.7

**Kubernetes Cluster Information**
 - GKE
 - 1.23
 
 - `kubectl describe` output
```
Name:         gmt-importer-mongodb
Namespace:    gmt-importer
Labels:       <none>
Annotations:  mongodb.com/v1.lastAppliedMongoDBVersion: 5.0.7
              mongodb.com/v1.lastSuccessfulConfiguration:
                {"members":3,"type":"ReplicaSet","version":"5.0.7","arbiters":0,"security":{"authentication":{"modes":["SCRAM"],"ignoreUnknownUsers":true}...
API Version:  mongodbcommunity.mongodb.com/v1
Kind:         MongoDBCommunity
Metadata:
  Creation Timestamp:  2022-06-15T02:04:42Z
  Generation:          1
  Managed Fields:
    API Version:  mongodbcommunity.mongodb.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:members:
        f:security:
          f:authentication:
            f:modes:
        f:statefulSet:
          f:spec:
            f:template:
              .:
              f:spec:
                .:
                f:containers:
                f:volumeClaimTemplates:
        f:type:
        f:users:
        f:version:
    Manager:      Terraform
    Operation:    Apply
    Time:         2022-06-15T02:04:42Z
    API Version:  mongodbcommunity.mongodb.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:mongodb.com/v1.lastAppliedMongoDBVersion:
          f:mongodb.com/v1.lastSuccessfulConfiguration:
    Manager:      manager
    Operation:    Update
    Time:         2022-06-15T02:08:26Z
    API Version:  mongodbcommunity.mongodb.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:currentMongoDBMembers:
        f:currentStatefulSetReplicas:
        f:mongoUri:
        f:phase:
        f:version:
    Manager:         manager
    Operation:       Update
    Subresource:     status
    Time:            2022-06-15T02:08:26Z
  Resource Version:  41717559
  UID:               43a28f0e-9e49-46b0-9705-b2cd0cb5166a
Spec:
  Members:  3
  Security:
    Authentication:
      Ignore Unknown Users:  true
      Modes:
        SCRAM
  Stateful Set:
    Spec:
      Template:
        Spec:
          Containers:
            Name:  mongodb-agent
            Readiness Probe:
              Failure Threshold:      40
              Initial Delay Seconds:  5
              Timeout Seconds:        30
            Resources:
              Limits:
                Cpu:     100m
                Memory:  256Mi
              Requests:
                Cpu:     100m
                Memory:  64Mi
            Name:        mongod
            Resources:
              Limits:
                Cpu:     200m
                Memory:  512Mi
              Requests:
                Cpu:     200m
                Memory:  256Mi
          Volume Claim Templates:
            Metadata:
              Name:  data-volume
            Spec:
              Access Modes:
                ReadWriteOnce
              Resources:
                Requests:
                  Storage:         5Gi
              Storage Class Name:  regional-pd
  Type:                            ReplicaSet
  Users:
    Db:    admin
    Name:  admin
    Password Secret Ref:
      Name:  mongodb-admin-password
    Roles:
      Db:                           admin
      Name:                         root
      Db:                           admin
      Name:                         clusterAdmin
      Db:                           admin
      Name:                         userAdminAnyDatabase
    Scram Credentials Secret Name:  gmt-importer-scram
  Version:                          5.0.7
Status:
  Current Mongo DB Members:       3
  Current Stateful Set Replicas:  3
  Mongo Uri:                      mongodb://gmt-importer-mongodb-0.gmt-importer-mongodb-svc.gmt-importer.svc.cluster.local:27017,gmt-importer-mongodb-1.gmt-importer-mongodb-svc.gmt-importer.svc.cluster.local:27
017,gmt-importer-mongodb-2.gmt-importer-mongodb-svc.gmt-importer.svc.cluster.local:27017
  Phase:                          Running
  Version:                        5.0.7
```

 - log files for the operator and database pods
`
2022-06-15T01:34:43.113Z	INFO	controllers/replica_set_controller.go:277	Successfully finished reconciliation, MongoDB.Spec: {Members:3 Type:ReplicaSet Version:5.0.7 Arbiters:0 FeatureCompatibilityVersion: ReplicaSetHorizons:[] Security:{Authentication:{Modes:[SCRAM] IgnoreUnknownUsers:0xc001b0a280} TLS:{Enabled:false Optional:false CertificateKeySecret:{Name:} CaCertificateSecret:<nil> CaConfigMap:<nil>} Roles:[]} Users:[{Name:admin DB:admin PasswordSecretRef:{Name:mongodb-admin-password Key:} Roles:[{DB:admin Name:root} {DB:admin Name:clusterAdmin} {DB:admin Name:userAdminAnyDatabase}] ScramCredentialsSecretName:gmt-importer-scram}] StatefulSetConfiguration:{SpecWrapper:{Spec:{Replicas:<nil> Selector:nil Template:{ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]} Spec:{Volumes:[] InitContainers:[] Containers:[{Name:mongodb-agent Image: Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[cpu:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI} memory:{i:{value:268435456 scale:0} d:{Dec:<nil>} s: Format:BinarySI}] Requests:map[cpu:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI} memory:{i:{value:67108864 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]} VolumeMounts:[] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:nil,TCPSocket:nil,},InitialDelaySeconds:5,TimeoutSeconds:30,PeriodSeconds:0,SuccessThreshold:0,FailureThreshold:40,TerminationGracePeriodSeconds:nil,} StartupProbe:nil Lifecycle:nil TerminationMessagePath: TerminationMessagePolicy: ImagePullPolicy: SecurityContext:nil Stdin:false StdinOnce:false TTY:false} {Name:mongod Image: Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[cpu:{i:{value:200 scale:-3} d:{Dec:<nil>} s:200m Format:DecimalSI} memory:{i:{value:536870912 scale:0} d:{Dec:<nil>} s: Format:BinarySI}] Requests:map[cpu:{i:{value:200 scale:-3} d:{Dec:<nil>} s:200m Format:DecimalSI} memory:{i:{value:268435456 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]} VolumeMounts:[] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil StartupProbe:nil Lifecycle:nil TerminationMessagePath: TerminationMessagePolicy: ImagePullPolicy: SecurityContext:nil Stdin:false StdinOnce:false TTY:false}] EphemeralContainers:[] RestartPolicy: TerminationGracePeriodSeconds:<nil> ActiveDeadlineSeconds:<nil> DNSPolicy: NodeSelector:map[] ServiceAccountName: DeprecatedServiceAccount: AutomountServiceAccountToken:<nil> NodeName: HostNetwork:false HostPID:false HostIPC:false ShareProcessNamespace:<nil> SecurityContext:nil ImagePullSecrets:[] Hostname: Subdomain: Affinity:nil SchedulerName: Tolerations:[] HostAliases:[] PriorityClassName: Priority:<nil> DNSConfig:nil ReadinessGates:[] RuntimeClassName:<nil> EnableServiceLinks:<nil> PreemptionPolicy:<nil> Overhead:map[] TopologySpreadConstraints:[] SetHostnameAsFQDN:<nil>}} VolumeClaimTemplates:[] ServiceName: PodManagementPolicy: UpdateStrategy:{Type: RollingUpdate:nil} RevisionHistoryLimit:<nil> MinReadySeconds:0}}} AdditionalMongodConfig:{Object:map[]} AutomationConfigOverride:<nil> Prometheus:<nil>}, MongoDB.Status: {MongoURI:mongodb://gmt-importer-mongodb-0.gmt-importer-mongodb-svc.gmt-importer.svc.cluster.local:27017,gmt-importer-mongodb-1.gmt-importer-mongodb-svc.gmt-importer.svc.cluster.local:27017,gmt-importer-mongodb-2.gmt-importer-mongodb-svc.gmt-importer.svc.cluster.local:27017 Phase:Running Version:5.0.7 CurrentStatefulSetReplicas:3 CurrentMongoDBMembers:3 CurrentStatefulSetArbitersReplicas:0 CurrentMongoDBArbiters:0 Message:}	{"ReplicaSet": "gmt-importer/gmt-importer-mongodb"}`

**Comment by mrszop** [comment]
Good morning,

you indentation is wrong. It needs to be like this:

```yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.6"

  statefulSet:
    spec:
      template:
        spec:
          containers:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
```

Cheers,
Szop
