### ISSUE TITLE
Nothing generated after install the operator and install replica example

### ISSUE THREAD

**Issue by victory4software** [mongodb/mongodb-kubernetes-operator#1035]
**What did you do to encounter the bug?**
1. I installed the operator using 
helm -n mongo-operator install community-operator mongodb/community-operator
 
![image](https://user-images.githubusercontent.com/28552955/176830564-0fa91ce1-0a39-49ed-af31-6e26d34048e8.png)

2.I tried to install and example of yaml file
```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: root
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: xxxxxxxxx
```
~                                              
after apply the changes of tha above file i a different namespace nothing generated on this except the custom resources
![image](https://user-images.githubusercontent.com/28552955/176830929-94be956c-d6e4-4542-acfc-e1ef4f51f337.png)

**What did you expect?**
I am expecting the secret that contains the connection string details to be generated but nothing is generated

**What happened instead?**
No pods or secretes generated after apply the above yaml code

**Operator Information**
 - Operator Version community-operator-0.7.4
 -
 - MongoDB Image used
type: ReplicaSet
  version: "4.2.6"

**Kubernetes Cluster Information**
 Minikube
