### ISSUE TITLE
Can not connect to Mongodb

### ISSUE THREAD

**Issue by ralphflat** [mongodb/mongodb-kubernetes-operator#1049]
1. install the operator (v0.7.4)
2. apply config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml in the oper namespace (see below)
3. Connected to resulting pod:  "kubectl -n oper exec --stdin --tty example-mongodb-0 -- /bin/bash"
4. Get error trying to connect to database

```
mongo "mongodb://example-mongodb-svc.mongodb.svc.cluster.local:27017/admin?ssl=true" --username admin --password abc123
MongoDB shell version v4.2.6
connecting to: mongodb://example-mongodb-svc.mongodb.svc.cluster.local:27017/admin?compressors=disabled&gssapiServiceName=mongodb&ssl=true
2022-07-14T20:54:43.108+0000 E  QUERY    [js] Error: couldn't connect to server example-mongodb-svc.mongodb.svc.cluster.local:27017, connection attempt failed: HostNotFound: Could not find address for example-mongodb-svc.mongodb.svc.cluster.local:27017: SocketException: Host not found (authoritative) :
connect@src/mongo/shell/mongo.js:341:17
```

Operator YAML
```
more config/manager/manager.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    email: support@mongodb.com
  labels:
    owner: mongodb
  name: mongodb-kubernetes-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-kubernetes-operator
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mongodb-kubernetes-operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - mongodb-kubernetes-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /usr/local/bin/entrypoint
        env:
        - name: WATCH_NAMESPACE
          value: '*'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: mongodb-kubernetes-operator
        - name: AGENT_IMAGE
          value: quay.io/mongodb/mongodb-agent:11.12.0.7388-1
        - name: VERSION_UPGRADE_HOOK_IMAGE
          value: quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4
        - name: READINESS_PROBE_IMAGE
          value: quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.9
        - name: MONGODB_IMAGE
          value: mongo
        - name: MONGODB_REPO_URL
          value: docker.io
        image: quay.io/mongodb/mongodb-kubernetes-operator:0.7.4
        imagePullPolicy: Always
        name: mongodb-kubernetes-operator
        resources:
          limits:
            cpu: 1100m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 200Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 2000
          allowPrivilegeEscalation: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: mongodb-kubernetes-operator
```

Mongo YAML

```
more config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: abc123
```
The mongo service does not have a ClusterIP address - is this expected?

service/example-mongodb-svc                    ClusterIP      None            <none>         27017/TCP                             24m

It seems like something is not configured correctly, but I don't see what.  Note that we do not have a mongosh in the pod - is this expected?

**Comment by davesargrad** [comment]
Anyone have any suggestions on this? I'm having same problem.

**Comment by davesargrad** [comment]
@ralphflat As an aside, when mongodb community operator is configured to watch resources in the same namespace then it seems to work fine with Cluster-iP none;
```
(base) [dsargrad@localhost heartbeat]$ k get services -n mongodb 

NAME                  TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
example-mongodb-svc   ClusterIP   None         <none>        27017/TCP   4d12h
```
i'll do more experimentation with mongodb community operator watching other namespaces. hopefully someone will have some insights into your problem.

**Comment by davesargrad** [comment]
@ralphflat Cluster-Ip none.. is normal. its called a headless service. see [here](https://faun.pub/kubernetes-headless-service-vs-clusterip-and-traffic-distribution-904b058f0dfd).

**Comment by davesargrad** [comment]
@ralphflat Did you skip this step? 

`kubectl apply -f deploy/clusterwide`

it is not described as an option. it seems that it may be required. I dont know if it would cause your problem

**Comment by fengruxiao** [comment]
I have the same problem , the cluster-ip is none. How to connet to the mongod?

**Comment by dan-mckean** [comment]
Hi, I'm Dan and I'm the Product Manager for MongoDB's support of Kubernetes.

I'm doing some work right now to try and identify how the Community Operator is being used. The Community Operator is something I inherited when I started at MongoDB, but it doesn't get as much attention from us as we'd like and we're trying to understand how it's used in order to establish its future. It will help us prioritize future issues and PRs raised by the community 🙂

Here's a super short survey (it's much easier for us to review all the feedback that way!): [https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSfwrwyxBSlUyJ6AmC-eYlgW_3JEdfA48SB2i5--_WpiynMW2w/viewform?usp=sf_link)

 If you'd rather email me instead: [dan.mckean@mongodb.com](mailto:dan.mckean@mongodb.com?subject=MongoDB%20Community%20Operator%20feedback)

Thank you in advance!
Dan

**Comment by ololoepepe** [comment]
For anyone who finds this issue, check that you do not modify stateful set labels. This was my case. I've changed default `app: mongodb-svc` to `app: mongodb` and the headless service cound not find any endpoints.

```yaml
  statefulSet:
    spec:
      # THIS IS WRONG!!! REMOVE IT
      selector:
        matchLabels:
          app: mongodb
      template:
        metadata:
          # THIS IS WRONG TOO
          labels:
            app: mongodb
```
Config is merged recursively, so you do not have to modify labels/selectors, they are assigned automatically.

It would be nice for the operator to check the labels and assign correct (manually modified) labels to service selector, though.
