### ISSUE TITLE
Init container in crash loop backoff with: version-upgrade-hook: applet not found

### ISSUE THREAD

**Issue by BryanHunt** [mongodb/mongodb-kubernetes-operator#1079]
**What did you do to encounter the bug?**
Installed MongoDBCommunity using the operator and the example config from the documentation.
Changed the version to 5.0.10

```yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.10"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: letMeIn
```

**What did you expect?**
I expected MongoDB to start

**What happened instead?**
The init container is in a crash loop backoff.  There is only one line in the logs:

```
version-upgrade-hook: applet not found
```

**Screenshots**

**Operator Information**
 - Operator Version: 0.7.5
 - MongoDB Image used: 5.0.10

**Kubernetes Cluster Information**
 - Distribution: Rancher Desktop
 - Version: 1.21.12
 - Image Registry location (quay, or an internal registry) default
