### ISSUE TITLE
Cannot connect to ReplicaSet from within Kubernetes Cluster

### ISSUE THREAD

**Issue by flolu** [mongodb/mongodb-kubernetes-operator#108]
I have followed the instruction from the README to install the Operator.
Then I applied the following configuration to my cluster:
```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: event-store
spec:
  members: 2
  type: ReplicaSet
  version: '4.2.7'
  featureCompatibilityVersion: '4.0'
```

So far everything works fine and running `k get po -n mongodb` returns
```
NAME                                           READY   STATUS    RESTARTS   AGE
event-store-0                                  2/2     Running   0          49m
event-store-1                                  2/2     Running   0          44m
mongodb-kubernetes-operator-85cb7f7b87-5sbwk   1/1     Running   0          56m
```
The service is also up and running:
```
NAME              TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
event-store-svc   ClusterIP   None         <none>        27017/TCP   51m
```

Now I deployed my NodeJs application, which tries to connect to MongoDb like this:
```
const client = new MongoClient('mongodb://event-store-svc.mongodb.svc.cluster.local:27017', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});
```
However, I cannot connect to the database. I get this error:
```
MongoServerSelectionError: connect ECONNREFUSED 10.1.87.44:27017
    at Timeout._onTimeout (node_modules/mongodb/lib/core/sdam/topology.js:430:30)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

Did I forget something? What am I doing wrong?
