### ISSUE TITLE
NetworkPolicy blocks readiness probes

### ISSUE THREAD

**Issue by laurivosandi** [mongodb/mongodb-kubernetes-operator#1087]
Please document how are NetworkPolicies supposed to be set up in order to make Mongo instances work with the operator

**Comment by laurivosandi** [comment]
So far I've got this:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongodb-operator
spec:
  podSelector:
    matchLabels:
      app: mongodb-svc
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - podSelector: {}
      ports:
      - port: 27017
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: mongodb-svc
      ports:
      - port: 27017
```
