### ISSUE TITLE
Cannot use any database other than admin

### ISSUE THREAD

**Issue by alexandretrichot** [mongodb/mongodb-kubernetes-operator#1104]
**What did you do to encounter the bug?**
- deploy operator
- deploy mongodb cluster with custom user and a database name other than "admin"
- let’s connect with your app
- Your custom user not have access to custom db (it works with "admin" as database

**What did you expect?**
I want to use custom database names for my users

**What happened instead?**
User does not have roles with use custom databases

**Operator Information**
 - Operator Version: latest
 - MongoDB Image used: 4.*, 5.*, 6.*
 
 Please I want to use multiple databases with multiples users on same cluster. Say if it is possible or not. The docs say it is possible but in practice, this doesn’t works…

Thanks for your time.

Alexandre

**Comment by elimumford** [comment]
@alexandretrichot This scenario is definitely supported.  You need to provide some information about your usage of the `MongoDBCommunity` CRD definition if you expect any help.  Have you granted your users any role in the target database?  i.e.
```yaml
...
  users:
    - name: myUser
      db: admin #default authentication db
      scramCredentialsSecretName: myUser #will become "myUser-scram-credentials" secret
      passwordSecretRef: myUser-Password #the secret you created for the users password (see docs)
      roles:
        - name: readWrite #built in ability to create db, read and write data to/from it
          db: myCustomeDbName #the database you expect the user to have access to.
...
```

**Comment by alexandretrichot** [comment]
Hello @elimumford, your CRD in my case looks like this:

```yaml
...
  users:
    - name: my-user
      db: admin
      scramCredentialsSecretName: my-user
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: readWrite
          db: my-db
...
```

This create the following connection URL in secret `mongo-admin-my-user`:

```
mongodb+srv://my-user:secret@mongo-svc.default.svc.cluster.local/admin?replicaSet=mongo&ssl=false
```

If you look at the end of the connection string, the database is `admin`. That's not what i want. In my case I would to use `my-db`.

So, I've setup my CRD Like this:

```yaml
...
users:
    - name: my-user
      db: my-db
      scramCredentialsSecretName: my-user
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: root
          db: my-db
...
```

what gave me:

```
mongodb+srv://my-user:secret@mongo-svc.default.svc.cluster.local/my-db?replicaSet=mongo&ssl=false
```

But when connecting with Prisma I get this error:

> Command failed (Unauthorized): not authorized on my-db to execute command

## Solution

For an unknown reason, if I replace `root` role with `readWrite`: **It works !**

Strange...

**Comment by zivfuture** [comment]
same issue and same solution as me.

**Comment by nammn** [comment]
@alexandretrichot 👋  thanks for opening the issue and apologies for the late reply. 
AFAICT you are reporting 2 issues.

1. The generated custom connection string is wrong and scoped to `admin`, even if you setup something else in your `CRD` like `my-db`. 
2. Using the `role` `root` does not work for  you, while `readWrite` does.

####  Regarding your first issue:
- I am not able to reproduce this issue in the current operator release. I used the following yaml
```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: my-user
      db: my-db
      scramCredentialsSecretName: my-user
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: readWrite
          db: my-db
    - name: my-user
      db: my-db-2
      scramCredentialsSecretName: my-user-2
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: read
          db: my-db-2
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: mongodb
```

 I was able to retrieve the connection string and it looked like I expected it to look like:
```
 k view-secret example-mongodb-my-db-my-user connectionString.standard
mongodb://my-user:mongodb@example-mongodb-0.example-mongodb-svc.mongodb.svc.cluster.local:27017,example-mongodb-1.example-mongodb-svc.mongodb.svc.cluster.local:27017,example-mongodb-2.example-mongodb-svc.mongodb.svc.cluster.local:27017/my-db?replicaSet=example-mongodb&ssl=false
```

#### Regarding your second issue
- The reason why above role `root` did not work for you is that the role is a pre-defined mongodb role which only works for the `admin` role. Read more here: https://www.mongodb.com/docs/manual/reference/built-in-roles/#std-label-database-administration-roles
> MongoDB provides the built-in  [database user](https://www.mongodb.com/docs/manual/reference/built-in-roles/#std-label-database-user-roles) and  [database administration](https://www.mongodb.com/docs/manual/reference/built-in-roles/#std-label-database-administration-roles) roles on every database. MongoDB provides all other built-in roles only on the admin database.
In case you plan to create custom roles and use these, we have dedicated [documentation](https://github.com/mongodb/mongodb-kubernetes-operator/blob/6e2270ca6564468e0e4f9c8f382373a44a9485c4/docs/deploy-configure.md#define-a-custom-database-role) for that. If you need a more detailed example you can read through the following issue: https://github.com/mongodb/mongodb-kubernetes-operator/issues/1162
