### ISSUE TITLE
Create new database upon resource creation

### ISSUE THREAD

**Issue by ctheisingfl** [mongodb/mongodb-kubernetes-operator#1112]
I would like to have another database created when I make a Mongodb resource.
Something like 

---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: examplev3
spec:
  db: examplev3
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: <password>

then shell into and do:
This is what it currently shows:
show dbs:
local  0.0GB
config 0.0GB
admin 0.001GB

I would like it to show :
show dbs:
local  0.0GB
config 0.0GB
examplev3  0.0GB
admin 0.001GB

Can I add an entry into the cr.yaml file to do this?

**Comment by mircea-cosbuc** [comment]
Hi @ctheisingfl,
Since MongoDB only creates a database when inserting data into it, the operator doesn't offer a functionality to define databases (beyond the default ones: `local`, `config` and `admin`) in the CR. You can however prepare roles for your users on these databases you are planning to use. Take for example this resource:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  annotations:
  name: mongodb
spec:
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  members: 1
  security:
    authentication:
      ignoreUnknownUsers: true
      modes:
      - SCRAM
    roles:
    - db: admin
      privileges:
      - actions:
        - createCollection
        resource:
          collection: ""
          db: examplev3
      role: customRole
  type: ReplicaSet
  users:
  - db: admin
    name: my-user
    passwordSecretRef:
      name: my-user-password
    roles:
    - db: admin
      name: clusterAdmin
    - db: admin
      name: userAdminAnyDatabase
    - db: admin
      name: customRole
    scramCredentialsSecretName: my-scram
  version: 6.0.2
```
The above will create the database and assign the `customRole` to `my-user` that allows it to create collections in the `examplev3` database. You can use this pattern to construct your custom role based on the available actions documented here: https://www.mongodb.com/docs/manual/reference/privilege-actions/.
