### ISSUE TITLE
Additional flags to autogenerated connection string

### ISSUE THREAD

**Issue by bygui86** [mongodb/mongodb-kubernetes-operator#1134]
I deployed a simple MongoDB ReplicaSet as example:

```yml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: temp-mongodb-replicaset
spec:
  type: ReplicaSet
  members: 3
  version: 6.0.2
  security:
    authentication:
      modes:
        - SCRAM
      ignoreUnknownUsers: false
  users:
    - name: temp-mongodb-admin
      db: admin
      passwordSecretRef:
        name: mongodb-kubernetes-operator-admin-creds
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: temp-mongodb-admin
      connectionStringSecretName: temp-mongodb-admin-connection-string
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      selector:
        matchLabels:
          component: mongodb
          replicaset: "true"
      template:
        metadata:
          labels:
            component: mongodb
            replicaset: "true"
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 1
                  memory: 2Gi
            - name: mongodb-agent
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              readinessProbe:
                failureThreshold: 50
                initialDelaySeconds: 10
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: kubernetes.io/hostname
                    labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - mongodb
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: ssd-csi-expandable
            resources:
              requests:
                storage: 3Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: ssd-csi-expandable
            resources:
              requests:
                storage: 2Gi
  prometheus:
    username: metrics
    passwordSecretRef:
      name: mongodb-kubernetes-operator-metrics-creds
```

As I got a secret named `temp-mongodb-admin-connection-string` with this connection string as content: `mongodb+srv://temp-mongodb-admin:***@temp-mongodb-replicaset-svc.temp.svc.cluster.local/admin?replicaSet=temp-mongodb-replicaset&ssl=false`

Is it possible to add flags to the connection string through the operator? For example in MongoDBCommunity CRD?

Flags like `readPreference` would be really important.

**Operator Information**
 - Operator Version:   0.7.6
 - MongoDB Image used:   docker.io/mongo:6.0.2

**Kubernetes Cluster Information**
 - Distribution/Version:   v1.21.14-gke.2700
 - Image Registry location (quay, or an internal registry):   quay
