### ISSUE TITLE
Could not access file: EACCES: permission denied, mkdir '/data/db/.mongodb'

### ISSUE THREAD

**Issue by zivfuture** [mongodb/mongodb-kubernetes-operator#1141]
**What did you do to encounter the bug?**
manager.yaml:
![image](https://user-images.githubusercontent.com/49356505/197373641-eb5815b0-0c76-4272-9845-e539236eaf5a.png)

```yaml
#mongodb.yaml:

apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: db
spec:
  version: "6.0.2"
  type: ReplicaSet
  members: 1
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongo-admin
  additionalMongodConfig:
    systemLog:
      destination: file
      path: /var/log/mongodb-mms-automation/mongodb.log
      logAppend: true
    storage:
      journal:
          enabled: true
    net:
      bindIp: 0.0.0.0
      port: 27017
  statefulSet:
    spec:
      serviceName: mongodb
      selector: {}
      template:
        metadata:
          labels:
            app: mongodb
        spec:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            runAsNonRoot: true
          containers:
          - name: mongod
            imagePullPolicy: IfNotPresent  #default is always
          - name: mongodb-agent
            imagePullPolicy: IfNotPresent  #default is always
      volumeClaimTemplates:
        - metadata:
            name: data-volume
            namespace: db
          spec:
            accessModes: [ "ReadWriteOnce", "ReadWriteMany" ]
            resources:
              requests:
                storage: 5Gi
        - metadata:
            name: logs-volume
            namespace: db
          spec:
            accessModes: [ "ReadWriteOnce", "ReadWriteMany" ]
            resources:
              requests:
                storage: 2Gi

```

**What did you expect?**
works fine

**What happened instead?**
```shell
I have no name!@mongodb-0:/$  mongosh "mongodb://admin:xxx@ip:port/admin?authSource=admin"
Warning: Could not access file: EACCES: permission denied, mkdir '/data/db/.mongodb'
```

**Screenshots**
run "kubect exec it" into container and ls files:
![image](https://user-images.githubusercontent.com/49356505/197373754-dd16cf86-89b1-49e8-91ac-9fbef5dd2e93.png)
you can see the directory  has wrong uid and groups and wrong permission: `rwxr-xr-x`.

cat /etc/passwd:
![image](https://user-images.githubusercontent.com/49356505/197373800-2259e6bc-f152-46c6-aeb8-6a9de368eaf7.png)

**Operator Information**
 - Operator Version
 - MongoDB Image used

**Kubernetes Cluster Information**
 - Version :  v1.24.1

Where am i missed?
