### ISSUE TITLE
nodeSelector usage

### ISSUE THREAD

**Issue by lombardialess** [mongodb/mongodb-kubernetes-operator#1142]
Hello,
for using specific nodepools on the cluster I'm trying to use the nodeSelector but seems not recognize by the operator.
Is it a bug or a feature request?
If it is a feature I think that could be useful to introduce it.
Thanks
Alessandro

**Comment by laurivosandi** [comment]
Hi, in the depths of documentation I managed to find this. For example to get Mongo nodes scheduled on dedicated storage nodes whilst being distributed between AWS AZ-s I used following. I hope this helps:

```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
spec:
  statefulSet:
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - mongodb-svc
                  topologyKey: topology.kubernetes.io/zone
          nodeSelector:
            dedicated: storage
          tolerations:
            - key: dedicated
              operator: Equal
              value: storage
              effect: NoSchedule
```
