### ISSUE TITLE
Readiness probe failed:  write error: can't open new logfile: open /var/log/mongodb-mms-automation/readiness.log: permission denied

### ISSUE THREAD

**Issue by nileshm2501** [mongodb/mongodb-kubernetes-operator#1143]
**RKE2 version v1.22.6+rke2r1**

I have followed the below doc.

1. Install Operator --> https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md
2. Create DB --> https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md

Got the PVC issue but sorted after creating it manually 10GB for data n 2 gb for log

Yaml file

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: dev-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.13"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    net:
      port: 40333

---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password:<pass>
```
  
  **Pod Error**
  
  ```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  17m                   default-scheduler  Successfully assigned mongodb/dev-mongodb-0 to wk3
  Normal   Pulling    17m                   kubelet            Pulling image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.5"
  Normal   Pulled     17m                   kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.5" in 1.006125915s
  Normal   Created    17m                   kubelet            Created container mongod-posthook
  Normal   Started    17m                   kubelet            Started container mongod-posthook
  Normal   Pulling    17m                   kubelet            Pulling image "quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.11"
  Normal   Pulled     17m                   kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.11" in 1.338753566s
  Normal   Created    17m                   kubelet            Created container mongodb-agent-readinessprobe
  Normal   Started    17m                   kubelet            Started container mongodb-agent-readinessprobe
  Normal   Pulling    17m                   kubelet            Pulling image "docker.io/mongo:5.0.13"
  Normal   Pulled     16m                   kubelet            Successfully pulled image "docker.io/mongo:5.0.13" in 19.859299577s
  Normal   Created    16m                   kubelet            Created container mongod
  Normal   Started    16m                   kubelet            Started container mongod
  Normal   Pulling    16m                   kubelet            Pulling image "quay.io/mongodb/mongodb-agent:12.0.10.7591-1"
  Normal   Pulled     16m                   kubelet            Successfully pulled image "quay.io/mongodb/mongodb-agent:12.0.10.7591-1" in 1.034043168s
  Normal   Created    16m                   kubelet            Created container mongodb-agent
  Normal   Started    16m                   kubelet            Started container mongodb-agent
  Warning  Unhealthy  16m                   kubelet            Readiness probe failed: 2022-11-02 14:02:18.202168269 +0000 UTC m=+0.037562782 write error: can't open new logfile: open /var/log/mongodb-mms-automation/readiness.log: permission denied
  Warning  Unhealthy  16m                   kubelet            Readiness probe failed: 2022-11-02 14:02:18.273271592 +0000 UTC m=+0.028320205 write error: can't open new logfile: open /var/log/mongodb-mms-automation/readiness.log: permission denied
  Warning  Unhealthy  16m                   kubelet            Readiness probe failed: 2022-11-02 14:02:28.194902018 +0000 UTC m=+0.029879174 write error: can't open new logfile: open /var/log/mongodb-mms-automation/readiness.log: permission denied
```
