### ISSUE TITLE
Create Role and  Management

### ISSUE THREAD

**Issue by kapendra-sentieo** [mongodb/mongodb-kubernetes-operator#1162]
I have a scenario where I need to create and assign a mongo role with a needed DB. Below is the config but the user is not reflected in mongo

```

---
# Source: as-mongodb/templates/deployment.yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  namespace: mongodb
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: 4.4.17
  security:
    authentication:
      modes: ["SCRAM"]
    roles: # custom roles are defined here
      - role: read-cust
        db: test-db
        privileges:
          - resource:
              db: test-db
              collection: "" # an empty string indicates any collection
            actions: ["update","insert","remove"]
        roles: []
  users:
    - name: mongodb-admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
    - name: test-db-user
      db: test-db
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-admin-password
      roles:
        - name: read-cust
          db: test-db
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
```
