### ISSUE TITLE
Unable to scrape metrics with ClusterPodMonitoring "monitoring.googleapis.com/v1"

### ISSUE THREAD

**Issue by marandalucas** [mongodb/mongodb-kubernetes-operator#1217]
**What did you do to encounter the bug?**

**We can not scrape Prometheus metrics in GCP using Managed Prometheus.**

We are trying to scrape metrics from MongoDB following the next example:
https://github.com/mongodb/mongodb-kubernetes-operator/blob/93c86675b851e7d44d5bfbd65375602dd4b3ad49/docs/prometheus/mongodb-prometheus-sample.yaml#L75-L83

**Scenario:**
We are using Managed Prometheus in GCP with GKE. Because of that, we have to [convert](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gmp-servicemonitor) _ServiceMonitor_ to _ClusterPodMonitoring_ or _PodMonitoring_.

In this scenario, we can not use "_authentication_", because unfortunately is not allowed -> 
https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.5.0/doc/api.md#scrapeendpoint

- **Could you help us? Did anyone have the same problem??**
- **Cloud you add a feature to scrape metrics without auth?**

Thank you so much

_ClusterPodMonitoring Example:_
```
---
apiVersion: monitoring.googleapis.com/v1
kind: ClusterPodMonitoring
metadata:
  name: mongodb-cluster
  namespace: gmp-system
  labels:
    name: mongodb-cluster
spec:
  selector:
    matchLabels:
      app: mongodb-rs-srv-svc
  endpoints:
  - port: prometheus
    interval: 15s
  # - authentication:
  #     password:
  #       key: password
  #       name: mongodb-rs-srv-metrics-endpoint-password
  #     username:
  #       key: username
  #       name: mongodb-rs-srv-metrics-endpoint-password
```

**What did you expect?**
Scrape metrics without basic auth or another workaround to solve it.
