### ISSUE TITLE
Impossible to unset limits in "mongod" and "mongodb-agent"

### ISSUE THREAD

**Issue by marandalucas** [mongodb/mongodb-kubernetes-operator#1220]
**What did you do to encounter the bug?**
Steps to reproduce the behaviour:
1. Define only requests for "mongod" and "mongodb-agent" pods.
```
  statefulSet:
    spec:
      template:
        spec:
          containers:
          - name: mongod
              requests:
                cpu: 200m
                memory: 256Mi
          - name: mongodb-agent
            resources:
              requests:
                cpu: "0.2"
                memory: 200M
```

3. Confirm the limits in the ReplicaSet. There are limits defined by default... Even when We didn't define it.

**mongod**
```
        name: mongod
        resources:
          limits: # NOTE: We don't want to define these Limits.
            cpu: "1"
            memory: 500M
          requests:
            cpu: 200m
            memory: 256Mi
```
**mongodb-agent**

```
        name: mongodb-agent
        resources:
          limits: # NOTE: We don't want to define these Limits.
            cpu: "1"
            memory: 500M
          requests:
            cpu: 200m
            memory: 200M
```

5. We expect don't limits in the statefulset for "monogd and mongodb-agents". For now, our workaround was to apply big limits.

**Does anyone have another idea? We've tried with 0 and "" but it's not allowed.**

```
  statefulSet:
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - mongodb-rs-srv-svc
                topologyKey: kubernetes.io/hostname
          containers:
          - name: mongod
            resources:
              limits:
                cpu: 4000m
                memory: 4Gi
              requests:
                cpu: 200m
                memory: 256Mi
          - name: mongodb-agent
            resources:
              limits:
                cpu: 4000m
                memory: 4Gi
              requests:
                cpu: "0.2"
                memory: 200M
```

Thanks in advance
