### ISSUE TITLE
Unable to upgrade mongodb community resource

### ISSUE THREAD

**Issue by tnormani** [mongodb/mongodb-kubernetes-operator#1222]
Hi,

we need to upgrade MongoDB community from version 4.2.22 to 6.0.3, using the operator in business continuity (rolling upgrade).
In details:

1.  we upgraded the operator to the latest version 0.7.8. The upgrade terminated successfully
2. starting from this resource

```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: test-mongodb
spec:
  type: ReplicaSet
  version: "4.2.22"
  members: 3
  security:
    authentication:
      modes: [ "SCRAM", "SCRAM-SHA-256", "SCRAM-SHA-1" ]
  users:
    - name: dbroot
      db: admin
      passwordSecretRef:
        name: test-dbroot-password
      roles:
        - name: dbAdmin
          db: admin
        - name: clusterAdmin
          db: admin
        - name: readWriteAnyDatabase
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: test-mongodb-admin-dbroot
  statefulSet:
    spec:
      selector:
        matchLabels:
          app: test-mongodb-svc
      # Specifies a size for the data amd logs volumes
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 10Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 2Gi
      template:
        metadata:
          labels:
            app: test-mongodb-svc
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - test-mongodb-svc
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: mongod
              resources:
                limits:
                  memory: 1Gi
                requests:
                  cpu: 1200m
            - name: mongodb-agent
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 50m
              readinessProbe:
                initialDelaySeconds: 10
                periodSeconds: 10
                timeoutSeconds: 10
                successThreshold: 1
                failureThreshold: 10
```
which is deployed **successfully** 

3.  we moved to 
```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: test-mongodb
spec:
  type: ReplicaSet
  version: "4.4.18"
  featureCompatibilityVersion: "4.2"
  members: 3
  security:
    authentication:
      modes: [ "SCRAM", "SCRAM-SHA-256", "SCRAM-SHA-1" ]
  users:
    - name: dbroot
      db: admin
      passwordSecretRef:
        name: test-dbroot-password
      roles:
        - name: dbAdmin
          db: admin
        - name: clusterAdmin
          db: admin
        - name: readWriteAnyDatabase
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: test-mongodb-admin-dbroot
  statefulSet:
    spec:
      selector:
        matchLabels:
          app: test-mongodb-svc
      # Specifies a size for the data amd logs volumes
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 10Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 2Gi
      template:
        metadata:
          labels:
            app: test-mongodb-svc
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - test-mongodb-svc
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: mongod
              resources:
                limits:
                  memory: 1Gi
                requests:
                  cpu: 1200m
            - name: mongodb-agent
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 50m
              readinessProbe:
                initialDelaySeconds: 10
                periodSeconds: 10
                timeoutSeconds: 10
                successThreshold: 1
                failureThreshold: 10
```
This upgrade isn't coming to an end. After several minutes, the situation is the following
```shell
$ kubectl get pods -n mongodb -w
NAME                                           READY   STATUS    RESTARTS   AGE
mongodb-kubernetes-operator-55d488798b-54m87   1/1     Running   0          33m
test-mongodb-0                                2/2     Running   0          23m
test-mongodb-1                                1/2     Running   0          32m
```
test-mongodb-0 is upgraded successfully, test-mongodb-1 is still 4.2 version and agent-probe is not ready and test-mongodb-2 is missing totally. The situation doesn't seem to change after hours. Manually deleting test-mongodb-1 seems to solve the stale situation, but it breaks business continuity process.

**Operator Information**
 - Operator Version: 0.7.8
 - MongoDB Image used: 
   - quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.12
   - quay.io/mongodb/mongodb-agent:12.0.15.7646-1
   - docker.io/mongo:4.4.18

**Kubernetes Cluster Information**
 - Distribution: Anthos 1.13, Kind 0.17.0, Minikube 1.28.0
 - Image Registry location (quay, or an internal registry): quay

**Additional context**
No matter K8s cluster flavour or the version of the K8s itself, the behaviour described is the same. We also tried various MongoDB upgrades and the behaviour is the same too.

Tell us what we are doing wrong, because it's very unlikely that such an important feature is broken.
Thank you in advance
