### ISSUE TITLE
cert-manager is not supported in case of intermediate certificate

### ISSUE THREAD

**Issue by VincentMarnier** [mongodb/mongodb-kubernetes-operator#1239]
**What did you do to encounter the bug?**
1. I generate a certificate for mongodb using cert-manager with the Issuer's caBundle being an intermediate certificate + the CA certificate
2. I use the secret generated by cert-manager with mongodb kubernetes operator just as stated in your doc (I know I am doing it right, and there is no mistake in my config file, see Additional context)

**What did you expect?**
At least, the mongodb pods to be marked as "Running 2/2"

**What happened instead?**
Stuck at "Running 1/2" with this logs displaying in loop in the container:
`{"t":{"$date":"2023-03-10T14:23:08.549+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.17.0.11:44994","uuid":"45d7368a-0e32-40db-a73c-941d769eac94","connectionId":7851,"connectionCount":3}}
{"t":{"$date":"2023-03-10T14:23:08.549+00:00"},"s":"I",  "c":"NETWORK",  "id":22988,   "ctx":"conn7851","msg":"Error receiving request from client. Ending connection from remote","attr":{"error":{"code":141,"codeName":"SSLHandshakeFailed","errmsg":"The server is configured to only allow SSL connections"},"remote":"172.17.0.11:44994","connectionId":7851}}
{"t":{"$date":"2023-03-10T14:23:08.550+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn7851","msg":"Connection ended","attr":{"remote":"172.17.0.11:44994","uuid":"45d7368a-0e32-40db-a73c-941d769eac94","connectionId":7851,"connectionCount":2}}`

**Operator Information**
 - Operator Version: v0.7.8
 - MongoDB Image used: The default one

**Kubernetes Cluster Information**
 - Distribution: Minikube
   - Host machine: Ubuntu 20.04 LTS
   - Command to start: minikube start --driver=docker --kubernetes-version=v1.23.12 --feature-gates=GRPCContainerProbe=true --addons=ingress
 - Version: 
 minikube version: v1.28.0
commit: 986b1ebd987211ed16f8cc10aed7d2c42fc8392f
 - Image Registry location: The default one

**Additional context**
- I am running vault with cert-manager
- The whole thing work if I don't use an intermediate certificate
- If you need it rephrased, I found someone with the same issue back in april 2022: https://discuss.hashicorp.com/t/mongodb-replicaset-tls-issue-using-vault-and-cert-manager/38699
- The intermediate certificate + vault's intermediate certificate are bundled in the secret's "tls.crt", only the root ca is in "ca.crt".
- The mongodb config does not change and I just adjust a path to match my vault config in cert-manager's issuer config.
- In both cases, the certificates generated by cert-manager work as expected with my others services, only mongodb kubernetes operator community with vault managing an intermediate certificate instead of a root one caused an issue

**Comment by Mreddi1** [comment]
I have the same problem. MongoDB version 6.0.4

**Comment by olekristensen** [comment]
I have the same issue... trying to skip the intermediate cert for now

**Comment by p-kimberley** [comment]
I have a working setup using a cert-manager intermediate cert `ClusterIssuer`. The wildcard CN and SAN could be replaced with explicitly named pod FQDNs - I just did this for ease of scaling.

`MongoDBCommunity` config snippet:
```yaml
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.18"
  ...
  security:
    tls:
      enabled: true
      optional: true
      caCertificateSecretRef:
        name: mongodb-prod-ca
      certificateKeySecretRef:
        name: mongodb-prod-tls
```

Certificates:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-prod-ca
  namespace: mongodb
spec:
  secretName: mongodb-prod-ca
  commonName: "*.mongodb-prod-svc.mongodb.svc.cluster.local"
  dnsNames:
    - "*.mongodb-prod-svc.mongodb.svc.cluster.local"
  privateKey:
    algorithm: ECDSA
    size: 256
  isCA: true
  issuerRef:
    name: k8s-prod-sub-ca
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-prod-tls
  namespace: mongodb
spec:
  secretName: mongodb-prod-tls
  commonName: "*.mongodb-prod-svc.mongodb.svc.cluster.local"
  dnsNames:
    - "*.mongodb-prod-svc.mongodb.svc.cluster.local"
    - mongodb-prod.mongodb.svc.prod
  issuerRef:
    name: k8s-prod-sub-ca
    kind: ClusterIssuer
```
