### ISSUE TITLE
Using SSL with the operator without cert-manager

### ISSUE THREAD

**Issue by onurbingol** [mongodb/mongodb-kubernetes-operator#1258]
Hello,

I was wondering if it is possible to use SSL with the operator without the cert-manager. I haven't done a lot of investigation, but it seems like enabling SSL on the operator requires cert-manager. It is impossible to enable SSL without it. 

The way as instructed on the [secure.md](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/secure.md) contains information on cert-manager, I modified the helm install a bit as follows:

```
helm upgrade community-operator mongodb/community-operator \
--namespace mongodb --set createResource=true --set resource.tls.enabled=true
```

Unfortunately, this command fails asking for the cert-manager.

I've also added the following without enabling SSL

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: my-mongodb
spec:
  version: "6.0.1"
  members: 1
  type: ReplicaSet
  replicaSetHorizons:
    - horizon: mydomain.fqdn:31181
  security:
    tls:
      enabled: true
      certificateKeySecretRef:
        name: ssl-mydomain
      caConfigMapRef:
        name: my-ca
    authentication:
      modes: ["SCRAM"]
```

In this case, the MongoDB pod fails and I can't see any log entries regarding the failure.

One may ask why I would want to use without cert-manager as it is a real convenience. I've already have my SSL certificates, and I'd like to use them. It is better this way for my use case and I believe it would be useful for many others.
