### ISSUE TITLE
(Unauthorized): 'not authorized on test to execute command

### ISSUE THREAD

**Issue by batazor** [mongodb/mongodb-kubernetes-operator#1293]
I create MongoDB replica set:

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-testkube
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  featureCompatibilityVersion: "6.0"
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: local-path
            resources:
              requests:
                storage: 2G
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: local-path
            resources:
              requests:
                storage: 1G
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: testkube
      db: testkube
      scramCredentialsSecretName: testkube
      passwordSecretRef:
        name: testkube-user-password
      roles:
        - name: clusterAdmin
          db: testkube
        - name: userAdminAnyDatabase
          db: testkube

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: testkube-user-password
type: Opaque
stringData:
  password: "super-secret-password"
```

And get URI for connect from secret: `mongodb://testkube:super-secret-password@mongodb-testkube-0.mongodb-testkube-svc.testkube.svc.cluster.local:27017/testkube?replicaSet=mongodb-testkube&ssl=false`

but trying to execute any command leads to failure. What could be the problem?
