### ISSUE TITLE
MongoDB Metrics for Prometheus 

### ISSUE THREAD

**Issue by raneee111** [mongodb/mongodb-kubernetes-operator#1304]
**What did you do to encounter the bug?**

i am trying to start mongodb metrics ,
i tried to add 

```
  prometheus:
    username: prometheus-username
    passwordSecretRef:
      name: metrics-endpoint-password
```

to cr(oc edit MongoDBCommunity):

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  annotations:
    mongodb.com/v1.lastAppliedMongoDBVersion: 4.2.21
    productChargedContainers: All
  creationTimestamp: "2023-05-10T13:37:52Z"
  generation: 2
  name: staging-mongodb
  namespace: staging
spec:
  prometheus:
    username: prometheus-username
    passwordSecretRef:
      name: metrics-endpoint-password
  additionalMongodConfig:
    net.maxIncomingConnections: 900
  members: 3
  security:
    authentication:
      ignoreUnknownUsers: true
      modes:
      - SCRAM
    tls:
      caConfigMapRef:
        name: xxxxx
      certificateKeySecretRef:
        name: xxxxx
```

after i save the changes in existing cr 
mongodbcommunity.mongodbcommunity.mongodb.com/staging-mongodb edited
when i will open the cr it will be without Prometheus part
(cannot see any new logs in operator logs) 

how should i enable the mongodb metrics? 
**What did you expect?**
mongo db metrics will start and Prometheus part will remain in cr
**What happened instead?**
Prometheus part deleted from cr
**Screenshots**

**Operator Information**
 - Operator Version - 0.76
 - MongoDB Image used - mongodb/mongodb-kubernetes-operator

**Kubernetes Cluster Information**
 - Distribution
 - Version - Major:"1", Minor:"24", GitVersion:"v1.24.6+deccab3"
 - Image Registry location (quay, or an internal registry) - quay.io
