### ISSUE TITLE
Incorrect merging of tolerations

### ISSUE THREAD

**Issue by aikoven** [mongodb/mongodb-kubernetes-operator#1313]
**What did you do to encounter the bug?**

Created a MongoDBCommunity resource like this:

```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
spec:
  statefulSet:
    spec:
      template:
        spec:
          tolerations:
            - effect: NoSchedule
              key: pool
              operator: Equal
              value: my-pool
            - effect: NoExecute
              key: pool
              operator: Equal
              value: my-pool
```

**What did you expect?**

StatefulSet has the tolerations as specified.

**What happened instead?**

StatefulSet has only the second toleration.

**Operator Information**

 - Operator Version: 0.7.4

**Additional context**

The reason lies in problematic [merging of tolerations](https://github.com/mongodb/mongodb-kubernetes-operator/blob/f12c9532ae3e263d80db95639f412b4fb79cf9be/pkg/util/merge/merge.go#L506-L526), where they are put to a map keyed by `Key`, effectively not allowing to have multiple tolerations with the same key.
