### ISSUE TITLE
replicaSetHorizons not working with external access

### ISSUE THREAD

**Issue by eBeyond** [mongodb/mongodb-kubernetes-operator#1319]
**What did you do to encounter the bug?**
I've created a ReplicaSet with the configured horizons:
```
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  # version: "5.0.5"
  version: "6.0.5"
  replicaSetHorizons:
  - horizon: mongodb-0.<external-domain>:31181
  - horizon: mongodb-1.<external-domain>:31182
  - horizon: mongodb-2.<external-domain>:31183
```

but when trying to connect with mongo compass it took some time to timeout and I got:
`getaddrinfo EAI_AGAIN mongodb-0.mongodb-svc.mongodb.svc.<cluster-domain>`

I've tried it with several other ways to configure horizons:
```
  - mongodb-0: mongodb-0.<external-domain>:31181
  - mongodb-1: mongodb-1.<external-domain>:31182
  - mongodb-2: mongodb-2.<external-domain>:31183
```
,
```
  - horizon1: mongodb-0.<external-domain>:31181
  - horizon2: mongodb-1.<external-domain>:31182
  - horizon3: mongodb-2.<external-domain>:31183
```
,
```
  - horizon1: mongodb-0.<external-domain>:31181
    horizon2: mongodb-1.<external-domain>:31182
    horizon3: mongodb-2.<external-domain>:31183
  - horizon1: mongodb-0.<external-domain>:31181
    horizon2: mongodb-1.<external-domain>:31182
    horizon3: mongodb-2.<external-domain>:31183
  - horizon1: mongodb-0.<external-domain>:31181
    horizon2: mongodb-1.<external-domain>:31182
    horizon3: mongodb-2.<external-domain>:31183
```
or
```
  - external: "mongodb-0.<external-domain>:31181" 
    internal: "mongodb-0.mongodb-svc.mongodb.svc.<cluster-domain>:31181"
  - external: "mongodb-1.<external-domain>:31182"
    internal: "mongodb-1.mongodb-svc.mongodb.svc.<cluster-domain>:31182"
  - external: "mongodb-2.<external-domain>:31183" 
    internal: "mongodb-2.mongodb-svc.mongodb.svc.<cluster-domain>:31183"
```
Within to code horizons should be a map[string]string. As such I understand, that the value of the map is the domain. But what should be the first one?
Or more generally: What should be the key in the replicaSetHorizons? As of now I've got no idea of fixing it. (As of testing I've disabled TLS to avoid any issues with that and concentrate on the horizons)

By the way: Most of the examples above I've found in the issues in this project which are mentioned as valid. As such I'm confused... :)

Thanks
Marc

**Comment by rdxmb** [comment]
```yaml
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.5"
  replicaSetHorizons:
    - horizon: mongodb-0.DOMAIN.com:27017
    - horizon: mongodb-1.DOMAIN.com:27017
    - horizon: mongodb-2.DOMAIN.com:27017
  security:
    tls:
      enabled: true
      caConfigMapRef:
        name: mongodb-ca.crt
      certificateKeySecretRef:
        name: mongodb-tls.crt
    authentication:
      modes: ["SCRAM"]
```

works in my case. However, I am moving from this project, so I cannot give any further help.
