### ISSUE TITLE
[BUG] I have no name! && groups: cannot find name for group ID 2000

### ISSUE THREAD

**Issue by tamis-laan** [mongodb/mongodb-kubernetes-operator#1320]
**What did you do to encounter the bug?**
1. Follow the installation tutorial using helm and namespace "mongodb" as described in https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md
2. Follow the deployment guide up to step 5:
https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md

**What did you expect?**
I would expect no warning or errors when getting a shell into the pod.

**What happened instead?**
I get the following output 
```
> kubectl -n mongodb exec --stdin --tty database-0 -- /bin/bash
Defaulted container "mongod" out of: mongod, mongodb-agent, mongod-posthook (init), mongodb-agent-readinessprobe (init)
groups: cannot find name for group ID 2000
I have no name!@database-0:/$
```
This is the yaml spec, I modified it a bit:
``` yaml
 apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: 200m
                  memory: 250M
                requests:
                  cpu: 200m
                  memory: 200M
            - name: mongodb-agent
              resources:
                limits:
                  cpu: 200m
                  memory: 250M
                requests:
                  cpu: 200m
                  memory: 200M
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 40Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 40Gi
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: tmp-mongodb-secret
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: tmp-mongodb-secret
type: Opaque
stringData:
  password: mypassword
```
When trying to connect using `mongo-express` I get the following error:
```
Welcome to mongo-express
------------------------


(node:13) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:13) UnhandledPromiseRejectionWarning: MongoError: not authorized on admin to execute command { listCollections: 1, filter: {}, cursor: {}, nameOnly: false, lsid: { id: UUID("fa7feb8b-11bd-4094-8844-ec64cc6ad043") }, $clusterTime: { clusterTime: Timestamp(1688468370, 1), signature: { hash: BinData(0, 4BF7F7EB8C83F29916F96BEB9D059E46F6B5142F), keyId: 7251908994892038149 } }, $db: "admin" }
    at Connection.<anonymous> (/node_modules/mongodb/lib/core/connection/pool.js:453:61)
    at Connection.emit (events.js:314:20)
    at processMessage (/node_modules/mongodb/lib/core/connection/connection.js:456:10)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connection.js:625:15)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:13) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
And when trying to connect through my nodejs server:
```
/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:207
                    callback(new error_1.MongoServerError(document));
                             ^

MongoServerError: not authorized on admin to execute command { create: "events", lsid: { id: UUID("bb82cc65-a0ac-4100-b082-8664a9fbb421") }, $clusterTime: { clusterTime: Timestamp(1688901143, 1), signature: { hash: BinData(0, F4CB19BA8771792CF38EC03AE8E1CC8501574519), keyId: 7252440905116811265 } }, $db: "admin" }
    at Connection.onMessage (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:207:30)
    at MessageStream.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
    at MessageStream._write (/app/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MessageStream.Writable.write (node:internal/streams/writable:336:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:513:28) {
  ok: 0,
  code: 13,
  codeName: 'Unauthorized',
  '$clusterTime': {
    clusterTime: Timestamp { low: 1, high: 1688901143, unsigned: true },
    signature: {
      hash: Binary {
        sub_type: 0,
        buffer: Buffer(20) [Uint8Array] [
          244, 203,  25, 186, 135, 113,
          121,  44, 243, 142, 192,  58,
          232, 225, 204, 133,   1,  87,
           69,  25
        ],
        position: 20
      },
      keyId: Long { low: 1, high: 1688590484, unsigned: false }
    }
  },
  operationTime: Timestamp { low: 1, high: 1688901143, unsigned: true },
  [Symbol(errorLabels)]: Set(0) {}
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Stream closed EOF for default/server-7d5c78dbc9-mggwv (master)
```
