### ISSUE TITLE
How can I have both the data and logs in the same PesistentVolumes?

### ISSUE THREAD

**Issue by spacecat** [mongodb/mongodb-kubernetes-operator#1336]
I have the following resource:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: mongodb
spec:
  members: 3

... etc
... etc
... etc
```
This creates 6 `PersistentVolume`s:

```
❯ k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                           STORAGECLASS   REASON   AGE
pvc-65ea9673-724c-4050-b997-a817ecedee06   10Gi       RWO            Delete           Bound    mongodb/data-volume-mongodb-2   default                 28h
pvc-6bf91177-5a84-458d-b995-8788d3c8257a   2Gi        RWO            Delete           Bound    mongodb/logs-volume-mongodb-1   default                 28h
pvc-7badd364-8cf9-4d18-8ee1-5aa8eb1e3bff   10Gi       RWO            Delete           Bound    mongodb/data-volume-mongodb-1   default                 28h
pvc-8254442f-85d8-4c6e-85b6-7af1c7308014   2Gi        RWO            Delete           Bound    mongodb/logs-volume-mongodb-2   default                 28h
pvc-8bd60b4e-0964-4399-b631-fddd8a327ae5   2Gi        RWO            Delete           Bound    mongodb/logs-volume-mongodb-0   default                 28h
pvc-b2d81fa0-ec2f-49e6-b2cb-1f0ee7f7d363   10Gi       RWO            Delete           Bound    mongodb/data-volume-mongodb-0   default                 28h
```

Is there a way to configure the community operator so that I only end up with 3 `PersistentVolume`s in total? If so, how?
