### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by clin4** [mongodb/mongodb-kubernetes-operator#1376]
**What did you do to encounter the bug?**
1. Use community-operator from https://mongodb.github.io/helm-charts 
2. follow the example to create the cr
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: xxx-mongodb
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: xxx-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: xxx-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: xxx-user-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: xxx-user-password
type: Opaque
stringData:
  password: abc
```
3. after the 3 pods instance run, use port-forward 
k port-forward svc/xxx-mongodb-svc 27017

4.  access the instance by Robo3T with the user/pwd to connect admin

**What did you expect?**
login successfuly from robo3t with the user/pwd

**What happened instead?**
A clear and concise description of what happened instead
always stay "authentication failed"

**Screenshots**
![image](https://github.com/mongodb/mongodb-kubernetes-operator/assets/26919744/f9507ecd-4f06-4a34-ae09-11fd2d82ae5b)

**Operator Information**
 - Operator Version
 MongoDB Kubernetes Community Operator
 - MongoDB Image used
  version: "6.0.5"

**Kubernetes Cluster Information**
 - Distribution
 GKE
 - Version
 v1.27.3-gke.100
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods
