### ISSUE TITLE
Database user secret being generated before random password secret gets updated

### ISSUE THREAD

**Issue by matheus-kirchesch-btor** [mongodb/mongodb-kubernetes-operator#1377]
**What did you do to encounter the bug?**
1. Install the operator
2. Create a helm chart to deploy a mongo instance
3. Create a secret that randomly generates a password within the chart:
```
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-user-password
type: Opaque
stringData:
  password: {{ randAlphaNum 16 | quote }}
```
4. Create the mongo resource referencing the random generated password within the chart:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Release.Name }}-database
spec:
...
  users:
  - name: {{ .Values.database.user.name }}
    db: {{ .Values.database.user.database }}
    passwordSecretRef:
      name: {{ .Release.Name }}-database-user-password
      key: password
    roles:
      - name: service_role
        db: {{ .Values.database.user.database }}
    scramCredentialsSecretName: {{ .Release.Name }}-database-user
```
5. Install the chart

**What did you expect?**
I expect for:
1. the password secret to have the random password (check)
2. the mongodb to use that password to create the user (check)
3. the generated mongodb user secret to reference this password (fail)

**What happened instead?**
So, whenever I install the chart a new password is generated and mongo uses it, but it doesn't update the secret that contains the string until the next release, so this generated secret is always one step behind

**Operator Information**
 - Operator Version: 0.8.2
 - MongoDB Image used: 6.0.5

**Kubernetes Cluster Information**
 - Distribution: gke
 - Version: I don't know
 - Image Registry location (quay, or an internal registry): quay

**Additional context**

If possible, please include:
Updated password secret:
```
apiVersion: v1
data:
  password: RkpBN2dXb1o4TEN5RWZFNA==
kind: Secret
```

Outdated generated db user secret:
```
apiVersion: v1
data:
  connectionString.standard: ...
  connectionString.standardSrv: ...
  password: MTIzMzIx
  username: ...
kind: Secret
```

** Note, the previous version of the password was MTIzMzIx (base64) becauseI changed it to test
