### ISSUE TITLE
Option to set different size for PVCs

### ISSUE THREAD

**Issue by benruland** [mongodb/mongodb-kubernetes-operator#1378]
**What did you do to encounter the bug?**
I am unable to find a way to set a different size for the data PVCs of MongoDB. I need to size the PVCs larger than 10G to store more data in MongoDB

**What did you expect?**
An option in the CustomResource to set the size of the data PVCs OR an option to provide how the created PVCs should look in general.

**What happened instead?**
Operator is always creating PVCs of size 10G

**Operator Information**
 - Operator Version: v0.8.2
 - MongoDB Image: docker.io/mongodb/mongodb-community-server:6.0.8-ubi8

**Kubernetes Cluster Information**
 - OpenShift 4.11.47
 - Images are mirrored to an internal Quay Registry

**Comment by code-uri** [comment]
@benruland Could you share your deployment file? 

Below config should work.
```
 volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          storageClassName: default-storage
          resources:
            requests:
              **storage: 20Gi**
```

**Comment by benruland** [comment]
Well, this was easy. It works now. Thanks!

For reference, this is my YAML:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 2
  type: ReplicaSet
  version: "6.0.8-ubi8"
  security:
    authentication:
  users:
    - name: admin
      passwordSecretRef:
        name: example-mongodb-admin-initial-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: root
          db: admin
      scramCredentialsSecretName: example-mongodb-admin
    - name: readwrite
      passwordSecretRef:
        name: example-mongodb-readwrite-initial-password
      roles:
        - name: readWrite
          db: mydb
      scramCredentialsSecretName: example-mongodb-readwrite
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
      template:
        spec:
          containers:
          - name: mongod
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 200m
                memory: 200Mi
          - name: mongodb-agent
            resources:
              limits:
                cpu: 200m
                memory: 250Mi
              requests:
                cpu: 200m
                memory: 200Mi
          initContainers:
          - name: mongod-posthook
            resources:
              limits:
                cpu: 50m
                memory: 100Mi
          - name: mongodb-agent-readinessprobe
            resources:
              limits:
                cpu: 50m
                memory: 100Mi
```
