### ISSUE TITLE
The deployed mongodb cluster is not working

### ISSUE THREAD

**Issue by glyslxq** [mongodb/mongodb-kubernetes-operator#1381]
I deployed it according to the operation document, but it doesn't seem to be running properly. This is my first time using mongodb and I'm not sure if there's anything else I need to do

pod status
```
root@pu20:~# kubectl get pod -n mongodb 
NAME                                          READY   STATUS    RESTARTS   AGE
mongodb7-0                               2/2     Running   0          15m
mongodb7-1                               2/2     Running   0          14m
mongodb7-2                               2/2     Running   0          14m
mongodb-kubernetes-operator-6cc9b94f8-jq5q8   1/1     Running   0          30h
```
pod logs
```
root@pu20# kubectl logs mongodb7-0 -n mongodb
Defaulted container "mongod" out of: mongod, mongodb-agent, mongod-posthook (init), mongodb-agent-readinessprobe (init)
2023-09-05T09:40:53.443Z	INFO	versionhook/main.go:32	Running version change post-start hook
2023-09-05T09:40:53.445Z	INFO	versionhook/main.go:39	Waiting for agent health status...
2023-09-05T09:40:54.445Z	INFO	versionhook/main.go:45	Agent health status file not found, mongod will start
```

deploy file
```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: ipds-mongodb7
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "7.0.0"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb7
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb7
  namespace: mongodb
type: Opaque
stringData:
  password: sssss
```

**Operator Information**
 - Operator Version: 0.8.2
 - MongoDB Image used: 7.0.0

**Kubernetes Cluster Information**
 - 1.26.6
