### ISSUE TITLE
Logging solely to stdout/stderr at the specified log level

### ISSUE THREAD

**Issue by MaciekLeks** [mongodb/mongodb-kubernetes-operator#1439]
**What did you do to encounter the bug?**
Unable to:
- Force logging of only ERRORs.
- Remove logs-volume PVC.

**What did you expect?**
I expected logging at the specified log level, directed solely to stdout, without creating a logs-volume PVC.

**What happened instead?**
- The agent logs at every level.
- A log-volume is created every time.

**Operator Information**
 - v0.8.3
 - crds v0.9.0
 - MongoDB - v7.0.3
-  agent 12.0.25.7724-1 

**Kubernetes Cluster Information**
 - GKE v1.25
 - internal registry 

My current yaml:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: test-mongodb
  namespace: common-mongodb
spec:
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  agent:
    logFile: /dev/stdout
    logLevel: ERROR
    systemLog:
      destination: file
      logAppend: true
      path: /dev/stdout
  members: 3
  security:
    authentication:
      ignoreUnknownUsers: true
      modes:
      - SCRAM
  statefulSet:
    spec:
      template:
        spec: { }
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      #- metadata:
      #    name: logs-volume
      #  spec:
      #    accessModes:
      #    - ReadWriteOnce
      #    resources:
      #      requests:
      #        storage: 0Gi <--it can't be 0 :)
  type: ReplicaSet
  users:
  - db: admin
    name: admin
    passwordSecretRef:
      name: test-mongodb-admin-admin-cred
    roles:
    - db: admin
      name: clusterAdmin
    - db: admin
      name: userAdminAnyDatabase
    - db: admin
      name: root
    scramCredentialsSecretName: test-mongodb-admin-admin
  - db: eshop-order-db-int
    name: op
    passwordSecretRef:
      name: test-mongodb-eshop-order-db-int-op-cred
    roles:
    - db: eshop-order-db-int
      name: readWrite
    scramCredentialsSecretName: test-mongodb-eshop-order-db-int-op
  version: 7.0.3
```
P.S. I found related #1226 but it's not a solution to the whole problem.
