### ISSUE TITLE
[Bug] : Readiness probe failed: panic: open /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json:

### ISSUE THREAD

**Issue by shubham-cmyk** [mongodb/mongodb-kubernetes-operator#1616]
**What did you do to encounter the bug?**

Deployed the [manifest](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/mongodb.com_v1_mongodbcommunity_readiness_probe_values.yaml) 

**What did you expect?**
no error

**What happened instead?**
```
Readiness probe failed: panic: open /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json: no such file or directory goroutine 1 [running]: main.main() /workspace/cmd/readiness/main.go:226 +0x191
```

**Screenshots**

**Operator Information**
 - Operator Version `0.11.0`
 - MongoDB Image used `7.0`

**Kubernetes Cluster Information**
 - Distribution 
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

The same setup is working if i use the version `6.0.5` it the operator compatible with the image `7.x` ?

**Comment by danielloczi** [comment]
I'm facing the same issue with Kubernetes Operator v0.12.0 and Mongo Community Server v7.0.15-ubi8.

Versions:

- mongodb-kubernetes-operator 0.12.0
- mongodb-agent-ubi: 108.0.2.8729-1
- mongodb-kubernetes-operator-version-upgrade-post-start-hook: 1.0.9
- mongodb-kubernetes-readinessprobe: 1.0.22
- mongodb-community-server: 7.0.15-ubi8

Replicaset:

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
  namespace: mongo
spec:
  members: 3
  type: ReplicaSet
  version: "7.0.15-ubi8"
  statefulSet:
    spec:
      template:
        spec:
          #  Hostpath volumes are owned by root
          #  but MongoDB containers run as non root
          #  so we use an init container to change the owner of
          #  the directory (init containers run as root)
          initContainers:
            - name: change-dir-permissions-data
              command:
                - chown
                - -R
                - "2000"
                - /data
              image: busybox
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /data
                  name: data-volume
              securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0

          containers:
            - name: "mongodb-agent"
              resources:
                requests:
                  cpu: 500m
                  memory: 256Mi
                limits:
                  cpu: 1000m
                  memory: 512Mi
            - name: "mongod"
              resources:
                requests:
                  cpu: 500m
                  memory: 512Mi
                limits:
                  cpu: 2000m
                  memory: 3Gi
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "mongo"
            resources:
              requests:
                storage: 5Gi
            selector:
              matchLabels:
                type: data
        - metadata:
            name: logs-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "mongo"
            resources:
              requests:
                storage: 5Gi
            selector:
              matchLabels:
                type: logs
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        key: password
        name: mongosecret
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: my-scram
```
      
mongo-0 pod is crashloopbackoff and logs:
```
  Warning  Unhealthy         40s                kubelet            Readiness probe failed: {"level":"info","ts":"2025-01-07T10:19:43.629Z","msg":"logging configuration: &{Filename:/var/log/mongodb-mms-automation/readiness.log MaxSize:5 MaxAge:0 MaxBackups:5 LocalTime:false Compress:false size:0 file:<nil> mu:{state:0 sema:0} millCh:<nil> startMill:{done:{_:{} v:0} m:{state:0 sema:0}}}"}
{"level":"error","ts":"2025-01-07T10:19:43.630Z","msg":"health status file not avaible yet: open /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json: no such file or directory "}
```
