### ISSUE TITLE
Cluster started without users or TLS

### ISSUE THREAD

**Issue by pixie79** [mongodb/mongodb-kubernetes-operator#162]
Hi,

Following the guides and examples I created the following yaml and created a new deployment with kubectl create:

```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.7"
  users:
    - name: mongoRoot
      db: admin
      passwordSecretRef:
        name: mongo-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
  security:
    tls:
      enabled: true
      certificateKeySecretRef:
        name: mongo-pod-cert
      caConfigMapRef:
        name: ca
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              env:
                - name: MANAGED_SECURITY_CONTEXT
                  value: "true"
            - name: "mongod"
              env:
                - name: MANAGED_SECURITY_CONTEXT
                  value: "true"
```

However when checking the changemap created I can see that TLS and auth is disabled?
  "auth": {
    "disabled": true,
    "authoritativeSet": false,
    "autoAuthMechanism": "MONGODB-CR"
  },
  "tls": {
    "CAFilePath": "",
    "clientCertificateMode": "OPTIONAL"
  },

Have I missed a step?

Thanks

Mark
