### ISSUE TITLE
Support Service Binding runtime

### ISSUE THREAD

**Issue by gbaso** [mongodb/mongodb-kubernetes-operator#1625]
Service bindings are well-supported by popular frameworks like [Spring Boot](https://github.com/spring-cloud/spring-cloud-bindings) and [Quarkus](https://quarkus.io/guides/deploying-to-kubernetes#service_binding) and provide an easy and standardized way of connecting to a service.

According to #831, service binding support for the [operator](https://github.com/redhat-developer/service-binding-operator) maintained by Red Hat was introduced in 0.7.3. The operator is now deprecated in favor of the [reference implementation](https://github.com/servicebinding/runtime) of the spec, which recently released [v1.0.0](https://github.com/servicebinding/runtime/releases/tag/v1.0.0).

According to the spec, a [provisioned service](https://github.com/servicebinding/spec?tab=readme-ov-file#provisioned-service) (e.g. the mongodb `StatefulSet`) should define a `status.binding.name` field referencing a `Secret` with the following structure:

```yaml
apiVersion: v1
kind: Secret
metadata:
...
type: servicebinding.io/mongodb
stringData:
  type: "mongodb"
  host: ...
  port: ...
  uri: ...
...
```

The operator could create this secret automatically along with the current ones.
