### ISSUE TITLE
Feature Request: Add support for specifying imagePullPolicy for initContainers in MongoDB ReplicaSet CRD

### ISSUE THREAD

**Issue by mahesh-kore** [mongodb/mongodb-kubernetes-operator#1626]
We are using the MongoDB Kubernetes Operator (version: 0.11.0) to deploy a MongoDB replica set. However, we have encountered an issue where it is not possible to specify the imagePullPolicy for initContainers via the current Custom Resource Definition (CRD) of mongodbcommunity.mongodb.com/v1.

When we manually patch the StatefulSet to set the imagePullPolicy for initContainers, the MongoDB operator reverts the changes. This behavior makes it difficult to ensure that the correct image pull policy is applied in our air-gapped environment where image downloads are restricted, and we rely on local copies.

**Expected Behavior:**
The MongoDB operator should allow users to specify imagePullPolicy for initContainers directly within the CRD definition, similar to how it's supported for main containers.

**Actual Behavior:**
There is currently no option to set imagePullPolicy for initContainers in the CRD. Manually patching the StatefulSet to set imagePullPolicy is reverted by the operator.

**Use Case:**
We are working in an air-gapped environment where images need to be pulled from local storage. Without the ability to configure imagePullPolicy for initContainers, the operator attempts to pull the image from an external source, leading to failed deployments.

**Steps to Reproduce:**
Deploy MongoDB replica set using the MongoDB Kubernetes Operator.
Attempt to patch the StatefulSet to set imagePullPolicy for initContainers.
Observe that the patch is reverted by the MongoDB operator.

**Proposed Solution:**
Add support for specifying imagePullPolicy for initContainers in the MongoDB replica set CRD.

**Additional Context:**
This feature would help users in air-gapped environments to ensure that local images are used for init containers, improving reliability in such setups.

Thank you!

**Comment by mahesh-kore** [comment]
Ccould you please advise if there's any known workaround to set the imagePullPolicy for initContainers when using the current CRD?

We've attempted to manually patch the StatefulSet, but the MongoDB operator reverts the patch. If there’s any configuration we may have missed, or an interim approach before the feature can be implemented, that would be greatly appreciated.

**Comment by lasher23** [comment]
Would love to see that done. Facing the same issue

**Comment by robinlieb** [comment]
You should be able to patch the InitContainers of the ReplicaSet via the wrapper, have you tried something similar like:
```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  statefulSet:
    spec:
      template:
        spec:
          initContainers:
            - name: mongod-posthook
              imagePullPolicy: Never
```

**Comment by lucian-tosa** [comment]
Hello @mahesh-kore 
Thank you for bringing this up! 
Currently, using the statefulSet override is the way to set the imagePullPolicy per container. Does this solve your problem?

**Comment by mahesh-kore** [comment]
@robinlieb @lucian-tosa Thanks for the workaround! I’ll give it a try and let you know if any issues come up

**Comment by mahesh-kore** [comment]
I tried overriding the imagePullPolicy as recommended above, using both IfNotPresent and Never, but it didn't apply or work as expected.

```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "7.0.3"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: mongo
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongo-user-password
      roles:
        - db: "admin"
          name: "clusterAdmin"
        - db: "admin"
          name: "userAdminAnyDatabase"
        - db: "admin"
          name: "root"
        - db: "admin"
          name: "readWriteAnyDatabase"
        - db: "admin"
          name: "read"
        - db: "admin"
          name: "restore"
        - db: "admin"
          name: "backup"
      scramCredentialsSecretName: mongo-scram
      connectionStringSecretNamespace: mongo
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: mongodb
      template:
        metadata:
          labels:
           app.kubernetes.io/name: mongodb
        spec:
          initContainers:
            - name: mongod-posthook
              imagePullPolicy: IfNotPresent
          dnsConfig:
            options:
            - name: use-vc
          nodeSelector:
            role: master
          containers:
            - name: mongod
              imagePullPolicy: IfNotPresent
```
