### ISSUE TITLE
Primary change periodically

### ISSUE THREAD

**Issue by cybercoder** [mongodb/mongodb-kubernetes-operator#1629]
I don't know this is a bug or not.
I have created a NodePort service to the 0 instance in replicaset statefulset for external temporary connections.

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-svc
  name: mongodb-svc-nodeport
  namespace: db
spec:
  ports:
  - name: mongodb
    nodePort: 30017
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-0
  type: NodePort
```
But the primary node periodically changes! ( maybe voting ... )
How we can commit the 0 instance being the primary always in the replicaset?
