### ISSUE TITLE
Unauthorized/No Permission to create Database

### ISSUE THREAD

**Issue by aspeteRakete** [mongodb/mongodb-kubernetes-operator#163]
Hi there,
I am trying to deploy a mongo instance in kind with the scram_cr (with members set to 1):
```
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: example-scram-mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: 58LObjiMpxcjP1sMDW
```

I can then connect to mongodb with Robo3T or Datagrip. Authentication succeeds and I can view the admin database.
However when I am trying to create a new Database/Collection I get an unauthorized message:

```
Failed to create database 'test'.

Error:
ListCollections failed: { operationTime: Timestamp(1598951458, 1), ok: 0.0, errmsg: "command listCollections requires authentication", code: 13, codeName: "Unauthorized", $clusterTime: { clusterTime: Timestamp(1598951458, 1), signature: { hash: BinData(0, 811ABEADC3EBD1CFC3EE8256396A6D7A6EB06BBF), keyId: 6867154498687598596 } } }
```
