### ISSUE TITLE
How to change priority in 3 nodes cluster

### ISSUE THREAD

**Issue by balait4** [mongodb/mongodb-kubernetes-operator#1639]
I have 3 member cluster `(6.0.6)` and I want to set or give more priority for 2 members and less for one member. 
I tried setting `automationConfig` which is not working. Also I had set under `memberConfig` which is not working.  

```
automationConfig:
    replicaSet:
      settings:
        members:
          - _id: 0
            host: mongodb-i-srv-0.mongodb-i-srv.mongodb-i.svc.cluster.local:27017
            priority: 2
          - _id: 1
            host: mongodb-i-srv-1.mongodb-i-srv.mongodb-i.svc.cluster.local:27017
            priority: 2
          - _id: 2
            host: mongodb-i-srv-2.mongodb-i-srv.mongodb-i.svc.cluster.local:27017
            priority: 1
        electionTimeoutMillis: 10000
    processes:
          - name: mongodb-i-srv-0
            hostname: mongodb-i-srv-0.mongodb-i-srv.mongodb-i.svc.cluster.local
            processType: mongod
            version: "6.0.6"
            disabled: false
            args:
              net:
                port: 27017
              replication:
                replSetName: mongodb-i-srv
          - name: mongodb-i-srv-1
            hostname: mongodb-i-srv-1.mongodb-i-srv.mongodb-i.svc.cluster.local
            processType: mongod
            version: "6.0.6"
            disabled: false
            args:
              net:
                port: 27017
              replication:
                replSetName: mongodb-i-srv
          - name: mongodb-i-srv-2
            hostname: mongodb-i-srv-2.mongodb-i-srv.mongodb-i.svc.cluster.local
            processType: mongod
            version: "6.0.6"
            disabled: false
            args:
              net:
                port: 27017
              replication:
                replSetName: mongodb-i-srv
type: ReplicaSet
memberConfig:
  - priority: '2'
    votes: 1
  - priority: '2'
    votes: 1
  - priority: '1'
    votes: 1
```

When I tried setting this manually as well its getting revert immediately. 
```
cfg = rs.conf()
cfg.members[0].priority = 5
cfg.members[1].priority = 5
cfg.members[2].priority = 2
rs.reconfig(cfg)
```
[mongodb-configs.txt](https://github.com/user-attachments/files/17830743/mongodb-configs.txt)
