### ISSUE TITLE
example for CRD with cpu/memory settings

### ISSUE THREAD

**Issue by fireba11** [mongodb/mongodb-kubernetes-operator#176]
since the default values for cpu and memory are somewhat low .. can you provide an example (as in extend the readme probably) how to set those?
https://github.com/mongodb/mongodb-kubernetes-operator/pull/157/files looks like it should be possible

**Comment by IsNull** [comment]
Here you go:

```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb
  namespace: mongo-global
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: root # User Name
      db: admin
      passwordSecretRef:
        name: root-password
      roles:
        - name: root
          db: admin
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              resources:
                requests:
                  cpu: 200m
                  memory: 400M
                limits:
                  cpu: 1000m
                  memory: 500M
            - name: "mongod"
              resources:
                requests:
                  cpu: 1000m
                  memory: 5000M
                limits:
                  cpu: 4000m
                  memory: 8000M
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          storageClassName: ssd-retained   # Your storage class
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 50Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: root-password
  namespace: mongo-global
type: Opaque
stringData:
  password: 12345 # Plain
```
