### ISSUE TITLE
no replica set is created with kind: MongoDB

### ISSUE THREAD

**Issue by tareksalem** [mongodb/mongodb-kubernetes-operator#218]
I am running a Kubernetes cluster on google cloud and followed the instructions to create a mongodb replica set, I have installed the crds and the operator and the operator pod is running on my cluster, the last thing to do is creating the replica set, here is my yaml file to create it:

```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: i-storage-mongodb
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: Admin
      db: admin
      passwordSecretRef:
        name: i-storage-admin-db-secret
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
  statefulSet:
    spec:
      template:
        spec:
          volumes:
            - name: custom-volume
              persistentVolumeClaim:
                claimName: mongo-pvc
          containers:
            - name: mongodb-agent
              volumeMounts:
              - name: mongo-volume
                mountPath: /data/db
      volumeClaimTemplates:
      - metadata:
          name: mongo-volume
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: mongodb-storage
          resources:
            requests:
              storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: i-storage-admin-db-secret
  namespace: mongodb
type: Opaque
stringData:
  password: ***

```

I am applying this definition using

```
kubectl apply -f 
```

the kubernetes tells me the definition is create but when listing the pods I can see only the operator pod and no pods had created for this definition
