### ISSUE TITLE
alternate mongo versions, 3.6, <4.0

### ISSUE THREAD

**Issue by bewest** [mongodb/mongodb-kubernetes-operator#222]
Is it possible to run 3.6 in any configuration?

```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-hellodb
  namespace: mongodb
spec:
  members: 3
  # commenting this out works
  featureCompatibilityVersion: "3.6"
  statefulSet:
    spec:
      template:
        spec:
          containers:
          - name: mongod
            resources:
              limits:
                cpu: 150m
                memory: 256Mi
              requests:
                cpu: 30m
                memory: 50Mi
          - name: mongodb-agent
            resources:
              limits:
                cpu: 150m
                memory: 256Mi
              requests:
                cpu: 30m
                memory: 50Mi
  security:
    authentication:
      # putting SCRAM-SHA-1 is not allowed
      modes: ["SCRAM"]
  type: ReplicaSet
  users:
  - db: admin
    name: admin
    passwordSecretRef:
      name: my-hello-password
      key: password
    roles:
    - db: admin
      name: clusterAdmin
    - db: admin
      name: userAdminAnyDatabase
  # versions 3.6.3, 3.6.5 do not work here
  version: 4.2.6
---
apiVersion: v1
kind: Secret
metadata:
  name: my-hello-password
type: Opaque
stringData:
  password: admin

```

Working theory is that it will be easier to migrate versions once we are inside kubernetes and preferably not migrating both things at once.
