### ISSUE TITLE
Other pods cannot connect to replica set

### ISSUE THREAD

**Issue by lamalex** [mongodb/mongodb-kubernetes-operator#230]
I have created a mongodb replica set with the supplied yaml,

```yaml
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
    - name: lrds
      db: liftright-dev
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: readWrite
          db: liftright-dev
    
# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: 58LObjiMpxcjP1sMDW
```
but when I try to connect to this cluster from another pod, I get a SCRAM authentication error.
`Error { kind: AuthenticationError { message: "SCRAM failure: Authentication failed." }, labels: [] }`

I am connecting at  `mongodb://lrds:58LObjiMpxcjP1sMDW@mongodb-0.mongodb-svc.default.svc.cluster.local/liftright-dev?replicaSet=mongodb`

If I run `mongo --host  mongodb://lrds:58LObjiMpxcjP1sMDW@mongodb-0.mongodb-svc.default.svc.cluster.local/liftright-dev?replicaSet=mongodb` from within a `mongod` container that connection string connects and authenticates successfully.
