### ISSUE TITLE
MongoDB Pod cannot run properly if it does not run with UID:GID 0:0

### ISSUE THREAD

**Issue by caiconkhicon** [mongodb/mongodb-kubernetes-operator#233]
I follow https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md, and in this file, it deploys a MongoDB resource by applying `deploy/crds/mongodb.com_v1_mongodb_cr.yaml`, but it fails because the Secret does not exist. It looks like, the file to be used here is https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_v1_mongodb_scram_cr.yaml ?

**Comment by irajdeep** [comment]
Hi @caiconkhicon 

The instruction was changed since it refers to installing the `mongodb` crd which is contained in the file `deploy/crds/mongodb.com_mongodb_crd.yaml`.

The previously mentioned file `deploy/crds/mongodb.com_mongodb_scram_crd.yaml` doesn't exist in the repo. 
For deploying mongodb with SCRAM, probably you should look here: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/users.md

**Comment by caiconkhicon** [comment]
Hi @irajdeep , thanks for your reply. Ok I was confused.
So now, actually my question is, I follow https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md, and in this file, it deploy a MongoDB resource by applying `deploy/crds/mongodb.com_v1_mongodb_cr.yaml`, but it fails because the Secret does not exist.

PS: I will also update the original post to reflex my actual question

**Comment by caiconkhicon** [comment]
@irajdeep : Yes I did that. The steps in the doc are pretty the same as applying https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_v1_mongodb_scram_cr.yaml (a MongoDB CR + a Secret). However, now I face another issue. The container `mongod` refuses starting with the error: 
```
permissions on /var/lib/mongodb-mms-automation/authentication/keyfile are too open
```

After checking inside the container, I found that somehow the keyfile is changed into a symbolic link (even though is is mounted from the Secret)

```
# ls -lha /var/lib/mongodb-mms-automation/authentication/
total 4.0K
drwxrwsrwt 3 root daemon  120 Oct 22 09:15 .
drwxr-xr-x 5 root root   4.0K Oct 22 09:15 ..
drwxr-sr-x 2 root daemon   80 Oct 22 09:15 ..2020_10_22_09_15_27.167383947
lrwxrwxrwx 1 root root     31 Oct 22 09:15 ..data -> ..2020_10_22_09_15_27.167383947
lrwxrwxrwx 1 root root     14 Oct 22 09:15 keyfile -> ..data/keyfile
lrwxrwxrwx 1 root root     15 Oct 22 09:15 password -> ..data/password
```

The mount seems to be correct:
```
      volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: example-scram-mongodb-agent-scram-credentials
          mountPath: /var/lib/mongodb-mms-automation/authentication
        - name: healthstatus
          mountPath: /healthstatus
```

```
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: data-volume-example-scram-mongodb-0
    - name: automation-config
      secret:
        secretName: example-scram-mongodb-config
        defaultMode: 416
    - name: example-scram-mongodb-agent-scram-credentials
      secret:
        secretName: example-scram-mongodb-agent-scram-credentials
        defaultMode: 384
    - name: healthstatus
      emptyDir: {}
    - name: hooks
      emptyDir: {}
```

**Comment by bznein** [comment]
Hi @caiconkhicon, about the `permissions too open` issue, I think that's the same that was reported here: https://github.com/mongodb/mongodb-kubernetes-operator/issues/212#issuecomment-704100924

**Comment by caiconkhicon** [comment]
Hi @bznein , thanks for a hint. However, it is not my case. I don't use Openshift. 
In my case, it is because by default, it is because of the default file permission:
```
    - name: example-scram-mongodb-agent-scram-credentials
      secret:
        secretName: example-scram-mongodb-agent-scram-credentials
        defaultMode: 384
```
This setting is set by the Operator. I wonder why no one reports this issue? is it just me?

**Comment by bznein** [comment]
Hi @caiconkhicon `defaultMode` shows the decimal value of the permissions, and `384` maps to `600` octal.

It seems that something changes the permissions of the volumes from the one set by default from the operator.
This seems really close to what happens on openshift, can you provide a bit more context on where you are running the operator?

Can you also provide the output of `kubectl get sts example-scram-mongodb -o yaml` ?

**Comment by caiconkhicon** [comment]
@bznein : Thanks for enlightening me 👍 
I run on a cluster created by Rancher (RKE  cluster). 
And this is the actual permissions of the files:
```
root@example-scram-mongodb-0:/var/lib/mongodb-mms-automation/authentication/..2020_10_22_13_23_21.487024859# ls -lha
total 8.0K
drwxr-sr-x 2 root daemon  80 Oct 22 13:23 .
drwxrwsrwt 3 root daemon 120 Oct 22 13:23 ..
-rw-r----- 1 root daemon 668 Oct 22 13:23 keyfile
-rw-r----- 1 root daemon  20 Oct 22 13:23 password
```

This is the spec of the StafefulSet:
```
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: example-scram-mongodb-svc
  serviceName: example-scram-mongodb-svc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: example-scram-mongodb-svc
    spec:
      containers:
      - command:
        - agent/mongodb-agent
        - -cluster=/var/lib/automation/config/cluster-config.json
        - -skipMongoStart
        - -noDaemonize
        - -healthCheckFilePath=/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json
        - -serveStatusPort=5000
        - -useLocalMongoDbTools
        env:
        - name: AGENT_STATUS_FILEPATH
          value: /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json
        - name: AUTOMATION_CONFIG_MAP
          value: example-scram-mongodb-config
        - name: HEADLESS_AGENT
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/mongodb/mongodb-agent:10.19.0.6562-1
        imagePullPolicy: Always
        name: mongodb-agent
        readinessProbe:
          exec:
            command:
            - /var/lib/mongodb-mms-automation/probes/readinessprobe
          failureThreshold: 60
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 500M
          requests:
            cpu: 500m
            memory: 400M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/automation/config
          name: automation-config
          readOnly: true
        - mountPath: /data
          name: data-volume
        - mountPath: /var/lib/mongodb-mms-automation/authentication
          name: example-scram-mongodb-agent-scram-credentials
        - mountPath: /var/log/mongodb-mms-automation/healthstatus
          name: healthstatus
      - command:
        - /bin/sh
        - -c
        - |2

          # run post-start hook to handle version changes
          /hooks/version-upgrade

          # wait for config to be created by the agent
          while [ ! -f /data/automation-mongod.conf ]; do sleep 3 ; done ; sleep 2 ;

          # start mongod with this configuration
          exec mongod -f /data/automation-mongod.conf ;
        env:
        - name: AGENT_STATUS_FILEPATH
          value: /healthstatus/agent-health-status.json
        image: registry.hub.docker.com/library/mongo:4.2.6
        imagePullPolicy: IfNotPresent
        name: mongod
        resources:
          limits:
            cpu: "1"
            memory: 500M
          requests:
            cpu: 500m
            memory: 400M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data-volume
        - mountPath: /var/lib/mongodb-mms-automation/authentication
          name: example-scram-mongodb-agent-scram-credentials
        - mountPath: /healthstatus
          name: healthstatus
        - mountPath: /hooks
          name: hooks
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - cp
        - version-upgrade-hook
        - /hooks/version-upgrade
        image: quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
        imagePullPolicy: Always
        name: mongod-posthook
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /hooks
          name: hooks
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: mongodb-kubernetes-operator
      serviceAccountName: mongodb-kubernetes-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: automation-config
        secret:
          defaultMode: 416
          secretName: example-scram-mongodb-config
      - name: example-scram-mongodb-agent-scram-credentials
        secret:
          defaultMode: 384
          secretName: example-scram-mongodb-agent-scram-credentials
      - emptyDir: {}
        name: healthstatus
      - emptyDir: {}
        name: hooks
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10G
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: example-scram-mongodb-598db79f88
  observedGeneration: 1
  replicas: 1
  updateRevision: example-scram-mongodb-598db79f88
  updatedReplicas: 1
```

**Comment by caiconkhicon** [comment]
@bznein : an assumption/question from me: Why the `defaultMode` is still 384, while I am showing the spec in YAML?

**Comment by bznein** [comment]
This is interesting. If you look at the stateful set, it has permission `384`, which is `600` octal, which would be `rw-------` (https://chmodcommand.com/chmod-0600/), while the actual file has permission `rw-r-----` which corresponds to `640`. 

This is the exact same issue that on openshift is reported; I can't find any similar issue on rancher's github but might be worth trying to create a minimal repro of this issue on rancher to verify it

**Comment by caiconkhicon** [comment]
Another small test from me: I create another Pod and mount the same Secret. In this case, the permission is right as I expect. Thus, I think it is sth to do with MongoDB (e.g. a process change the permission of the file (which does not seem to be, since Secret is ReadOnly), MongoDB image has a special setting)

**Comment by bznein** [comment]
Hi @caiconkhicon, this is certainly puzzling.

So just to confirm, you are able to mount a secret to a pod with permissions `384` (`600`) and it gets correctly mounted with those?

The operator mounts the secret with the permission shows in the statefulset specs, so if that is not what ends up with used we will need to figure out what's happening there

**Comment by caiconkhicon** [comment]
Yes, that's what I observed. I will tell you if I have more info/test

**Comment by caiconkhicon** [comment]
It is very puzzling. 
I did other tests, using the Pod manifest. **Please note that I replace the mongodb image with nginx image !!!** So it is sth wrong with the manifest, not the image (?)

**1. Keep the manifest. Set the permission for each file:**
```
  - name: example-scram-mongodb-agent-scram-credentials
    secret:
      secretName: example-scram-mongodb-agent-scram-credentials
      items:
        - key: keyfile
          path: keyfile
          mode: 0600
        - key: password
          path: password
          mode: 0644
```
Then `kubectl describe` output is:
```
  - name: example-scram-mongodb-agent-scram-credentials
    secret:
      defaultMode: 420
      items:
      - key: keyfile
        mode: 384
        path: keyfile
      - key: password
        mode: 420
        path: password
```
The actual file permissions are:
```
-rw-r----- 1 root daemon 668 Oct 22 14:13 keyfile 
-rw-r--r-- 1 root daemon  20 Oct 22 14:13 password
```

**2.  Keep the manifest. Set the default permission**
```
  - name: example-scram-mongodb-agent-scram-credentials
    secret:
      secretName: example-scram-mongodb-agent-scram-credentials
      defaultMode: 384
```
Then `kubectl describe` output is:
```
  - name: example-scram-mongodb-agent-scram-credentials
    secret:
      defaultMode: 384
      secretName: example-scram-mongodb-agent-scram-credentials
```
The actual file permissions are:
```
-rw-r----- 1 root daemon 668 Oct 22 14:13 keyfile 
-rw-r----- 1 root daemon  20 Oct 22 14:13 password
```

**3. Use a simple Pod manifest**
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: databases
spec:
  containers:
    - name: web
      image: nginx
      volumeMounts:
        - name: example-scram-mongodb-agent-scram-credentials
          mountPath: /var/lib/mongodb-mms-automation/authentication
        - name: pgadmin4
          mountPath: /var/lib/mongodb-mms-automation/pgadmin4
  volumes:
    - name: example-scram-mongodb-agent-scram-credentials
      secret:
        secretName: example-scram-mongodb-agent-scram-credentials
        defaultMode: 0600
    - name: pgadmin4
      secret:
        secretName: pgadmin4
        defaultMode: 0600
```

Works like a charm:
```
-rw------- 1 root root 668 Oct 22 14:15 keyfile
-rw------- 1 root root  20 Oct 22 14:15 password
```

**Comment by caiconkhicon** [comment]
It seems that 416 (or rw-r-----) is the low-limit, because if I set it to 420, things work as expected

**Comment by caiconkhicon** [comment]
@bznein : I found the culprit:

```
  securityContext:
    fsGroup: 1
    supplementalGroups:
    - 1
```
This is from the Pod manifest. I don't find it in the StatefulSet manifest.

**Comment by bznein** [comment]
@caiconkhicon thanks! This was a very interesting investigation!

This might be something that happens only when deploying on Rancher. 
I'll try to reproduce it as soon as possible and will file an internal ticket for tracking.

In the meantime, you are more than welcome to submit a PR to our repo if you think you can fix it yourself!

**Comment by caiconkhicon** [comment]
@bznein : I found the issue. I explain it here, then you can think of how to fix it from the point of view of MongoDB operator.

So, in our cluster, we have PodSecurityPolicy (PSP) named `restricted-psp` (it is set up by Rancher, but the same setup can happen in many cases, since it is a security best practice). This PSP has this rule: 
```
  Fs Group:
    Ranges:
      Max:  65535
      Min:  1
    Rule:   MustRunAs
  Run As User:
    Rule:  RunAsAny
  Supplemental Groups:
    Ranges:
      Max:  65535
      Min:  1
    Rule:   MustRunAs
```

Because of that, the mounted Volumes Pod is forced to run with the groupID 1 (Read more: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods). That's why we have:
```
  securityContext:
    fsGroup: 1
    supplementalGroups:
    - 1
```

I didn't notice it at first:
```
-rw-r----- 1 root daemon 668 Oct 22 14:13 keyfile 
-rw-r--r-- 1 root daemon  20 Oct 22 14:13 password
```
```
-rw------- 1 root root 668 Oct 22 14:15 keyfile
-rw------- 1 root root  20 Oct 22 14:15 password
```

Do you see the difference? In the case where the permission is wrong, the group is `daemon`. 

My fix is to give the serviceAccount `mongodb-kubernetes-operator` the permission to use a more powerful PSP (i.e. can use the group ID 0).

I don't know how should we fix the mongoDB Operator deployment, but I would suggest we make it somehow so that the deployment fails when it cannot runs as root:root
