### ISSUE TITLE
Default configuration doesn't expose 27017 by default

### ISSUE THREAD

**Issue by srknc** [mongodb/mongodb-kubernetes-operator#238]
Hi,
Following the documentation here, I've created CRD (https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/crds/mongodb.com_mongodb_crd.yaml) and operator (https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/deploy/operator.yaml and other files)
Finally defined `MongoDB` resources below(1).
Kubernetes cluster creates operator `mongodb-kubernetes-operator-5fbdcddd4c-tpvq9` and 3 pods (as members: 3)
`mongodb-cluster-0`, `mongodb-cluster-1`, `mongodb-cluster-2`

Operator very positive about the cluster with log below;
```
Successfully finished reconciliation	{"ReplicaSet": "infra/mongodb-cluster", "MongoDB.Spec:": {"members":3,"type":"ReplicaSet","version":"3.6","featureCompatibilityVersion":"3.6","security":{"authentication":{"modes":["SCRAM"]},"tls":{"enabled":false,"optional":false,"certificateKeySecretRef":{"name":""},"caConfigMapRef":{"name":""}}},"users":[{"name":"username","db":"admin","passwordSecretRef":{"name":"mongodb-cluster-password","key":""},"roles":[{"db":"admin","name":"readWrite"}]}],"statefulSet":{"spec":{"selector":null,"template":{"metadata":{"creationTimestamp":null},"spec":{"containers":null}},"serviceName":"","updateStrategy":{}}},"additionalMongodConfig":{}}, "MongoDB.Status:": {"mongoUri":"mongodb://mongodb-cluster-0.mongodb-cluster-svc.infra.svc.cluster.local:27017,mongodb-cluster-1.mongodb-cluster-svc.infra.svc.cluster.local:27017,mongodb-cluster-2.mongodb-cluster-svc.infra.svc.cluster.local:27017","phase":"Running","currentStatefulSetReplicas":3,"currentMongoDBMembers":3}}
```

Whatever I do, I'm not able to connect to cluster;

```mongo "mongodb://mongodb-cluster-0.mongodb-cluster-svc.infra.svc.cluster.local:27017,mongodb-cluster-1.mongodb-cluster-svc.infra.svc.cluster.local:27017,mongodb-cluster-2.mongodb-cluster-svc.infra.svc.cluster.local:27017"```
```
mongo --host mongodb-cluster-svc 
```
Even with pod ips.

When I check one of the pod definition getting from cluster;
```
...
Containers:
  mongodb-agent:
    Container ID:  docker://3946052521fd6d496db201d53eb9fb120afb164cd327f8f47eda83247b9b5ac8
    Image:         quay.io/mongodb/mongodb-agent:10.19.0.6562-1
    Image ID:      docker-pullable://quay.io/mongodb/mongodb-agent@sha256:790c2670ef7cefd61cfaabaf739de16dbd2e07dc3b539add0da21ab7d5ac7626
    Port:          <none>
    Host Port:     <none>
...
```
I would expect pod to expose 27017 port

Am I missing something here?

(1)
```
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb-cluster
spec:
  members: 3
  type: ReplicaSet
  #version: "4.2.6"
  version: "3.6"
  featureCompatibilityVersion: "3.6"
  clusterName: mongodb-cluster
  logLevel: INFO # default value
  persistent: true
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: username
      db: admin
      passwordSecretRef:
        name: mongodb-cluster-password
      roles:
        - name: readWrite
          db: admin
  podSpec:
    cpuRequests: 2
    cpu: 4 #limit
    memoryRequests: 2Gi #limit
    memory: 4Gi
    persistence:
      single:  # https://docs.mongodb.com/kubernetes-operator/master/reference/k8s-operator-specification/#spec.podSpec.persistence.single
      # single: Has Kubernetes Operator create one Persistent Volume Claim and mount all three directories for data, journal, and logs to the same Persistent Volume.
        storage: 100Gi
        storageClass: standard #Make sure to set the StorageClass reclaimPolicy to Retain. This ensures that data is retained when a Persistent Volume Claim is removed.
        labelSelector:
          matchLabels:
            storage: "persistent-mongodb"

```
