### ISSUE TITLE
mongodump failes to authenticate

### ISSUE THREAD

**Issue by haroonb** [mongodb/mongodb-kubernetes-operator#250]
Hello I'm trying to validate the operator for our production environment. I'm currently trying backup and restore scenarios, but I can't seem to get it to mongodump. It seems, that my user can't access the db, but if I go into the db using mongo und switch the db it works fine. 

Thanks for any assistance you can provide.

```
root@example-scram-mongodb-0:/# mongodump --gzip --archive=/tmp/full.archive --password=12345678 --username=my-user --authenticationDatabase=admin --authenticationMechanism=SCRAM-SHA-256
2020-11-17T13:26:48.175+0000    Failed: error creating intents to dump: error creating intents for database admin: error getting collections for database `admin`: (Unauthorized) not authorized on admin to execute command { listCollections: 1, filter: {}, lsid: { id:
UUID("413df0a9-74b3-4916-8619-0299126874bd") }, $clusterTime: { clusterTime: Timestamp(1605619604, 1), signature: { hash: BinData(0, 9C90FD63B06248BABC6B120E606AC61DE2F4A2E4), keyId: 6895737067955814403 } }, $db: "admin", $readPreference: { mode: "primaryPreferred" } }
root@example-scram-mongodb-0:/# mongo --password 12345678 --username my-user
MongoDB shell version v4.2.6
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("51dc1e74-7a59-4843-a0fc-e5113dad2d15") }
MongoDB server version: 4.2.6
Server has startup warnings:
2020-11-16T14:59:58.554+0000 I  STORAGE  [initandlisten]
2020-11-16T14:59:58.555+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2020-11-16T14:59:58.555+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2020-11-16T14:59:59.285+0000 I  CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2020-11-16T14:59:59.285+0000 I  CONTROL  [initandlisten]
---
Enable MongoDB's free cloud-based monitoring service, which will then receive and display
metrics about your deployment (disk utilization, CPU, operation statistics, etc).

The monitoring data will be available on a MongoDB website with a unique URL accessible to you
and anyone you share the URL with. MongoDB may use this information to make product
improvements and to suggest MongoDB products and deployment options to you.

To enable free monitoring, run the following command: db.enableFreeMonitoring()
To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---

example-scram-mongodb:PRIMARY> use admin
switched to db admin
example-scram-mongodb:PRIMARY> show collections
system.users
system.version
example-scram-mongodb:PRIMARY> exit
bye
root@example-scram-mongodb-0:/#
```
```
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: example-scram-mongodb
spec:
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              resources:
                requests:
                  cpu: 20m
                  memory: 40M
                limits:
                  cpu: 1000m
                  memory: 500M
            - name: "mongod"
              resources:
                requests:
                  cpu: 10m
                  memory: 50M
                limits:
                  cpu: 4000m
                  memory: 8000M
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          storageClassName: rook-ceph-block   # Your storage class
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1G
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: 12345678
```

**Comment by rrey** [comment]
Same problem on my side by just testing connection from another pod.
```
$ mongo "mongodb://xxxxxx-fr-mongo-svc:27017/?replicaSet=xxxxxx-mongo" --username xxxxxx-admin --password xxxxxx --authenticationDatabase admin
MongoDB shell version v3.6.8
connecting to: mongodb://xxxxxx-mongo-svc:27017/?replicaSet=xxxxxx-mongo
2020-11-18T14:39:48.401+0000 I NETWORK  [thread1] Starting new replica set monitor forxxxxxx-mongo/xxxxxx-mongo-svc:27017
2020-11-18T14:39:48.404+0000 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to xxxxxx-mongo-svc:27017 (1 connections now open to xxxxxx-mongo-svc:27017 with a 5 second timeout)
2020-11-18T14:39:48.405+0000 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] changing hosts to xxxxxx-mongo/xxxxxx-mongo-0.xxxxxx-mongo-svc.xxxxxx.svc.cluster.local:27017 from xxxxxx-mongo/xxxxxx-mongo-svc:27017
2020-11-18T14:39:48.406+0000 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to xxxxxx-mongo-0.xxxxxx-mongo-svcxxxxxx.svc.cluster.local:27017 (1 connections now open to xxxxxx-mongo-0.xxxxxx-mongo-svc.xxxxxx.svc.cluster.local:27017 with a 5 second timeout)
Implicit session: session { "id" : UUID("82973a8e-ab34-4dfe-be57-3d420a5157d0") }
MongoDB server version: 4.2.6
WARNING: shell and server versions do not match
2020-11-18T14:39:48.411+0000 E QUERY    [thread1] Error: Authentication failed. :
DB.prototype._authOrThrow@src/mongo/shell/db.js:1608:20
@(auth):6:1
@(auth):1:2
exception: login failed
```

This [documentation ](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/users.md) says that the user's password should be in "plain text". It seems to be what @haroonb did in his yaml, but secret are supposed to be base64 encoded. (Even if I tried both method and none seems working).

**Comment by rrey** [comment]
Found my problem.
First, secret really have to be plain text in the manifest. Seem odd to me to do something like that :/
Second, my connection issue came from the client side. I was in ubuntu 20 container image that contains mongo v3 which seems to be unable to do SCRAM-SHA-256.

I added an explicit reference to SHA-256 in my connection string as specified [here](https://docs.mongodb.com/drivers/node/fundamentals/authentication/mechanisms#scram-sha-256):
```
mongo "mongodb://xxxxxx-fr-mongo-svc:27017/?replicaSet=xxxxxx-mongo&authMechanism=SCRAM-SHA-256" --username xxxxxx-admin --password xxxxxx --authenticationDatabase admin"
```

which lead to the following error at client side:
```
020-11-18T17:06:28.157+0000 E QUERY    [thread1] Error: can't authenticate against replica set node astuvet-fr-mongo-0.astuvet-fr-mongo-svc.astuvet-fr.svc.cluster.local:27017: SASL mechanism SCRAM-SHA-256 is not supported :
```

I upgraded the client by using the mongo apt repo and got `v4.4.2`. With that client login worked properly.

**Comment by theburi** [comment]
This issue is labeled as stale because it has been open for more than 30 days with no activity. Remove stale label or comment or this will be closed in a few days.

**Comment by ebarped** [comment]
Hi!
I was having a similar problem, but it all were due to authorization problems.
I added the backup role to my admin user, in this way, and it solved the problem:
```
  users:
    - name: admin
      db: admin
      passwordSecretRef: 
        name: mongodb-admin-pass
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: backup
          db: admin
```
