### ISSUE TITLE
Cannot access.  ReplicaSetNoPrimary.  Seems incompatible with 4.2.7+

### ISSUE THREAD

**Issue by MichaelJCole** [mongodb/mongodb-kubernetes-operator#259]
Hello, the Mongodb K8s Operator created a replicaset, but I can't seem to access it from my apps.

ReplicaSet definition:
```
# This uses https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb-drama
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.2"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      passwordSecretRef:
        name: mongodb-admin-secret
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-admin-scram

    - name: drama
      passwordSecretRef:
        name: mongodb-drama-secret
      roles:
        - name: dbOwner
          db: drama
      scramCredentialsSecretName: mongodb-drama-scram
```

Attempting to connect this to a Mongo-Express docker image, I've tried these hostnames:
```
 ME_CONFIG_MONGODB_SERVER: "mongodb-drama-0.mongodb-drama-svc.default.svc.cluster.local"
 ME_CONFIG_MONGODB_SERVER: "mongodb-drama-svc.default.svc.cluster.local"
```

Error from Mongo-Express pod:
```
Waiting for mongodb-drama-0.mongodb-drama-svc.default.svc.cluster.local:27017...
/docker-entrypoint.sh: connect: Connection refused
/docker-entrypoint.sh: line 14: /dev/tcp/mongodb-drama-0.mongodb-drama-svc.default.svc.cluster.local/27017: Connection refused
```

Attempting to connect from my custom Parse server: 
```
  PARSE_SERVER_DATABASE_URI: "mongodb://drama:secret@mongodb-drama-svc.default.svc.cluster.local:27017/admin?replicaSet=mongodb-drama"
```

Gives this error:
```
MongoServerSelectionError: connect ECONNREFUSED 10.1.0.196:27017
    at Timeout._onTimeout (/app/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) {
      'mongodb-drama-svc.default.svc.cluster.local:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
```

I noticed the service doesn't have a Cluster IP, should it?

```
$ kubectl describe svc mongodb-drama-svc
Name:              mongodb-drama-svc
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          app=mongodb-drama-svc
Type:              ClusterIP
IP:                None
Port:              <unset>  27017/TCP
TargetPort:        27017/TCP
Endpoints:         10.1.0.195:27017,10.1.0.196:27017,10.1.0.197:27017
Session Affinity:  None
Events:            <none>
```

To install the Operator in my cluster, I'm using these files from the `deploy` folder:
![image](https://user-images.githubusercontent.com/1504790/101119706-87dfb280-35b1-11eb-82a4-00b7bc008c40.png)
in a kustomization.yaml
```
resources:
  # cert-manager manages certificates on ingress
  - cert-manager/cert-manager.yaml

  # dashboard is kubernetes dashboard
  # https://github.com/kubernetes/dashboard
  - dashboard/dashboard.yaml
  - dashboard/dashboard-auth.yaml

  # Creates MongoDB Kubernetes Operator in default namespace
  # https://github.com/mongodb/mongodb-kubernetes-operator
  - mongodb-kubernetes-operator/crds/mongodb.com_mongodb_crd.yaml
  - mongodb-kubernetes-operator/operator/service_account.yaml
  - mongodb-kubernetes-operator/operator/role.yaml
  - mongodb-kubernetes-operator/operator/role_binding.yaml
  - mongodb-kubernetes-operator/operator/operator.yaml
```

Similar to: https://github.com/mongodb/mongodb-kubernetes-operator/issues/238

What am I missing?  Thank you!
