### ISSUE TITLE
Can't figure out how to get PersistentVolumeClaims to work

### ISSUE THREAD

**Issue by bocajim** [mongodb/mongodb-kubernetes-operator#261]
Hello, running in AKS with kubernetes 1.18.

When I run, I get this error:

  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  **Warning  FailedScheduling        22m (x3 over 22m)  default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.**
  Normal   Scheduled               22m                default-scheduler        Successfully assigned prod-us/mongodb-2 to aks-nodepool1-68759764-vmss000002
  Normal   SuccessfulAttachVolume  22m                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-d234f318-bb4b-4d8b-8f2f-f7663594d966"
  Normal   Started                 22m                kubelet                  Started container mongod-posthook
  Normal   Pulling                 22m                kubelet                  Pulling image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2"
  Normal   Pulled                  22m                kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2"
  Normal   Created                 22m                kubelet                  Created container mongod-posthook
  Normal   Pulled                  22m                kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-agent:10.15.1.6468-1"
  Normal   Pulling                 22m                kubelet                  Pulling image "quay.io/mongodb/mongodb-agent:10.15.1.6468-1"
  Normal   Created                 22m                kubelet                  Created container mongodb-agent
  Normal   Started                 22m                kubelet                  Started container mongodb-agent
  Normal   Pulled                  22m                kubelet                  Container image "mongo:4.2.6" already present on machine
  Normal   Created                 22m                kubelet                  Created container mongod
  Normal   Started                 22m                kubelet                  Started container mongod
  Warning  Unhealthy               21m                kubelet                  Readiness probe failed:

The problem isn't benign because it is creating a default PVC of 10GB, but I only want 1GB.

```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: root
      db: admin
      passwordSecretRef:
        name: mongodb-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: root
          db: admin
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongodb-agent
              persistentVolumeClaim:
                claimName: mongodb-data
            - name: mongodb
              persistentVolumeClaim:
                claimName: mongodb-data
          volumeClaimTemplates:
            - metadata:
                name: mongodb-data
              spec:
                accessModes:
                  - ReadWriteOnce
                storageClassName: managed-premium
                resources:
                  requests:
                    storage: 1Gi
```
