### ISSUE TITLE
Run replicaset with out authentication

### ISSUE THREAD

**Issue by Binyamse** [mongodb/mongodb-kubernetes-operator#301]
I want to deploy mongo replicaset with out auth and the crd seems to make it required despite what the doc says [here](https://docs.mongodb.com/kubernetes-operator/master/reference/k8s-operator-specification/#spec.security.authentication.enabled)

Sample manifest
``` 
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: example-mongodb
spec:
  members: 2
  type: ReplicaSet
  version: "4.2.6"
  persistent: true
  security:
      authentication:
           enabled: false
replication:
  replSetName: testA
podSpec:
    cpu: '0.5'
    memory: 512M
```

error i received

```
* spec.security.authentication.modes: Required value
* spec.users: Required value
```
