### ISSUE TITLE
Requests and limits

### ISSUE THREAD

**Issue by maxaggedon** [mongodb/mongodb-kubernetes-operator#307]
**What did you do to encounter the bug?**
1. Set up request and limits in cr like explained in other older issues
```
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongo-agent
              resources:
                requests:
                  cpu: 200m
                  memory: 100M
                limits:
                  cpu: 400m
                  memory: 200M
            - name: mongod
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
```
2. Deploy `kubectl apply -f deploy/crds/mongodb.com_v1_mongodbcommunity_cr.yaml`
3. Logs in the first pod show :
```
Events:
  Type     Reason            Age                  From                    Message
  ----     ------            ----                 ----                    -------
  Normal   SuccessfulCreate  114s                 statefulset-controller  create Claim data-volume-mongodb-0 Pod mongodb-0 in StatefulSet mongodb success
  Warning  FailedCreate      32s (x15 over 114s)  statefulset-controller  create Pod mongodb-0 in StatefulSet mongodb failed error: Pod "mongodb-0" is invalid: spec.containers[0].image: Required value
```

**What did you expect?**
Image to be the default one, like when no template for containers is specified

**What happened instead?**
I'm forced to deploy first without resource config and describe the pods to get the default image and set it in my config

**Operator Information**
 - 0.4.0 and 0.5.0

**Kubernetes Cluster Information**
 - 1.19

**Additional context**
The goal is to setup a dev database with restricted resources
