### ISSUE TITLE
Cannot create Database or collection and authenticate with newly created user from mongo shell

### ISSUE THREAD

**Issue by akshay654** [mongodb/mongodb-kubernetes-operator#361]
Hi,

We are trying to create a database from mongoshell after successfully logging into the primary Db, Following are the commands.
1. mongo --host <ip> --port 27017 --username <username> --password <password> --authenticationDatabase <dbName>  - With this command we are able to successfully authenticate into a particular database created while deploying theYAML file alongwith the admin database, We are able to create collections add data.
2. But when we try to create a new database after logging in using any other cred like the admin DB creds and execute command in following order
a - use testdb
b - db.createUser(
{
	user: "test",

	pwd: "test",

	roles:[{role: "dbAdmin" , db:"testdb"}],

	mechanisms: ["SCRAM-SHA-256"],
});
c - The user is created successfully, but to create any collection or insert someting in db i need to first authenticate with that use, so when executing below command
d - 
db.auth("test", "test")

Getting the following error - 

Error: Authentication failed.
0

But all this steps work for the Databse and users created from the deployment yaml files in the operator crds.

Please do let me know if any more information needed from my end.

**Comment by chatton** [comment]
Hi @akshay654 

If you manually create any MongoDB users, they will be removed as they are not configured via the CRD. In your case, you could specify your user via the CR.

Adding the following to your CR definition should be equivalent to creating the user through the shell

```yaml

  users:
    - name: test
      db: test
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-test-user-password
      roles:
        - name: dbAdmin
          db: testdb
      scramCredentialsSecretName: my-test-user-scram
```

and make sure to create a password

```yaml

---
apiVersion: v1
kind: Secret
metadata:
  name: my-test-user-password
type: Opaque
stringData:
  password: test

```
