### ISSUE TITLE
mongodb.com_v1_mongodbcommunity_cr.yaml - 3 pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by XamYp** [mongodb/mongodb-kubernetes-operator#364]
Hello,

I have tried deploying mongodb with kubernetes but I am having a problem. I use an on premise environment (vmware) with three virtual machines, a master and two nodes. The installed version is v1.20.4.
I followed the [first tutorial to install the operator](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md). I created all the elements in the "mongo" namespace.

I encounter an error when I try to deploy `kubectl apply -f config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml --namespace mongo`. When I type the command `kubectl describe pod/example-mongodb-0 -n mongo`

Below is a screenshot of my error message :
![04-23-01-03-2021](https://user-images.githubusercontent.com/35339236/109518425-84719f80-7aaa-11eb-8d31-4e5d8e57f653.png)

![04-24-01-03-2021](https://user-images.githubusercontent.com/35339236/109518587-a834e580-7aaa-11eb-9ca6-92412819e151.png)

With this command `k describe statefulsets.apps example-mongodb -n mongo` : 
![04-28-01-03-2021](https://user-images.githubusercontent.com/35339236/109519188-4d4fbe00-7aab-11eb-88ae-7643ea5bc102.png)

I tried adding this before my deployment but it didn't work ...

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: mongo-volume
  hostPath:
    path: "/mnt/data"
```

I have seen other similar issues but no answers and this did not solve my problem.

Thank you in advance for your help !

**Comment by yuswitayudi** [comment]
same issue

**Comment by jyyoo0530** [comment]
Same issue. Pls check my deployment and pv, sc yaml.
I am new to kubernetes and mongodb operator.

sc.yaml
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongod-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongo-agent-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```
pv.yaml
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongod1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongod-sc
  local:
    path: /database/mongodb/mongod1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongod2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongod-sc
  local:
    path: /database/mongodb/mongod2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongod3
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongod-sc
  local:
    path: /database/mongodb/mongod3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: agent1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-agent-sc
  local:
    path: /database/mongodb/agent1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: agent2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-agent-sc
  local:
    path: /database/mongodb/agent2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: agent3
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-agent-sc
  local:
    path: /database/mongodb/agent3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master
```

replicaset.yaml
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replicaset
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: password-admin
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: admin-scram
    - name: vaultuser
      db: admin
      passwordSecretRef:
        name: password-user1
      roles:
        - name: readWrite
          db: vault
      scramCredentialsSecretName: user-scram1
  statefulSet:
    spec:
      serviceName: mongodb-statefulset
      selector: {}
      template:
        spec:
          containers:
            - name: mongod
              volumeMounts:
                - name: mongod-pvc
                  mountPath: /data/mongod
            - name: mongodb-agent
              volumeMounts:
                - name: mongo-agent-pvc
                  mountPath: /data/agent
      volumeClaimTemplates:
        - metadata:
            name: mongod-pvc
          spec:
            storageClassName: mongod-sc
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 20Gi
        - metadata:
            name: mongo-agent-pvc
          spec:
            storageClassName: mongo-agent-sc
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 20Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: password-admin
type: Opaque
stringData:
  password: xxxxxxx
---
apiVersion: v1
kind: Secret
metadata:
  name: password-user1
type: Opaque
stringData:
  password: xxxxxxx
```

This show below,
```
name@host:~$ kubectl get pvc -n mongodb
NAME                                   STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS     AGE
data-volume-mongodb-replicaset-0       Pending                                                       13m
mongo-agent-pvc-mongodb-replicaset-0   Pending                                      mongo-agent-sc   13m
mongod-pvc-mongodb-replicaset-0        Pending                                      mongod-sc        13m
```
I am not sure why 'data-volume' pvc triggered even with customized statefulset.
Is mongodb community operator still incomplete for persistent volume? or error in my deployment? Please kindly review my error..Thanks.. :)

**Comment by yuswitayudi** [comment]
> Same issue. Pls check my deployment and pv, sc yaml.
> I am new to kubernetes and mongodb operator.
> 
> sc.yaml
> 
> ```
> ---
> kind: StorageClass
> apiVersion: storage.k8s.io/v1
> metadata:
>   name: mongod-sc
> provisioner: kubernetes.io/no-provisioner
> volumeBindingMode: WaitForFirstConsumer
> allowVolumeExpansion: true
> ---
> kind: StorageClass
> apiVersion: storage.k8s.io/v1
> metadata:
>   name: mongo-agent-sc
> provisioner: kubernetes.io/no-provisioner
> volumeBindingMode: WaitForFirstConsumer
> allowVolumeExpansion: true
> ```
> 
> pv.yaml
> 
> ```
> ---
> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: mongod1
> spec:
>   capacity:
>     storage: 20Gi
>   accessModes:
>     - ReadWriteOnce
>   persistentVolumeReclaimPolicy: Retain
>   storageClassName: mongod-sc
>   local:
>     path: /database/mongodb/mongod1
>   nodeAffinity:
>     required:
>       nodeSelectorTerms:
>         - matchExpressions:
>             - key: kubernetes.io/hostname
>               operator: In
>               values:
>                 - master
> ---
> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: mongod2
> spec:
>   capacity:
>     storage: 20Gi
>   accessModes:
>     - ReadWriteOnce
>   persistentVolumeReclaimPolicy: Retain
>   storageClassName: mongod-sc
>   local:
>     path: /database/mongodb/mongod2
>   nodeAffinity:
>     required:
>       nodeSelectorTerms:
>         - matchExpressions:
>             - key: kubernetes.io/hostname
>               operator: In
>               values:
>                 - master
> ---
> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: mongod3
> spec:
>   capacity:
>     storage: 20Gi
>   accessModes:
>     - ReadWriteOnce
>   persistentVolumeReclaimPolicy: Retain
>   storageClassName: mongod-sc
>   local:
>     path: /database/mongodb/mongod3
>   nodeAffinity:
>     required:
>       nodeSelectorTerms:
>         - matchExpressions:
>             - key: kubernetes.io/hostname
>               operator: In
>               values:
>                 - master
> ---
> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: agent1
> spec:
>   capacity:
>     storage: 20Gi
>   accessModes:
>     - ReadWriteOnce
>   persistentVolumeReclaimPolicy: Retain
>   storageClassName: mongo-agent-sc
>   local:
>     path: /database/mongodb/agent1
>   nodeAffinity:
>     required:
>       nodeSelectorTerms:
>         - matchExpressions:
>             - key: kubernetes.io/hostname
>               operator: In
>               values:
>                 - master
> ---
> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: agent2
> spec:
>   capacity:
>     storage: 20Gi
>   accessModes:
>     - ReadWriteOnce
>   persistentVolumeReclaimPolicy: Retain
>   storageClassName: mongo-agent-sc
>   local:
>     path: /database/mongodb/agent2
>   nodeAffinity:
>     required:
>       nodeSelectorTerms:
>         - matchExpressions:
>             - key: kubernetes.io/hostname
>               operator: In
>               values:
>                 - master
> ---
> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: agent3
> spec:
>   capacity:
>     storage: 20Gi
>   accessModes:
>     - ReadWriteOnce
>   persistentVolumeReclaimPolicy: Retain
>   storageClassName: mongo-agent-sc
>   local:
>     path: /database/mongodb/agent3
>   nodeAffinity:
>     required:
>       nodeSelectorTerms:
>         - matchExpressions:
>             - key: kubernetes.io/hostname
>               operator: In
>               values:
>                 - master
> ```
> 
> replicaset.yaml
> 
> ```
> apiVersion: mongodbcommunity.mongodb.com/v1
> kind: MongoDBCommunity
> metadata:
>   name: mongodb-replicaset
> spec:
>   members: 3
>   type: ReplicaSet
>   version: "4.2.6"
>   security:
>     authentication:
>       modes: ["SCRAM"]
>   users:
>     - name: admin
>       db: admin
>       passwordSecretRef:
>         name: password-admin
>       roles:
>         - name: clusterAdmin
>           db: admin
>         - name: userAdminAnyDatabase
>           db: admin
>       scramCredentialsSecretName: admin-scram
>     - name: vaultuser
>       db: admin
>       passwordSecretRef:
>         name: password-user1
>       roles:
>         - name: readWrite
>           db: vault
>       scramCredentialsSecretName: user-scram1
>   statefulSet:
>     spec:
>       serviceName: mongodb-statefulset
>       selector: {}
>       template:
>         spec:
>           containers:
>             - name: mongod
>               volumeMounts:
>                 - name: mongod-pvc
>                   mountPath: /data/mongod
>             - name: mongodb-agent
>               volumeMounts:
>                 - name: mongo-agent-pvc
>                   mountPath: /data/agent
>       volumeClaimTemplates:
>         - metadata:
>             name: mongod-pvc
>           spec:
>             storageClassName: mongod-sc
>             accessModes: [ "ReadWriteOnce" ]
>             resources:
>               requests:
>                 storage: 20Gi
>         - metadata:
>             name: mongo-agent-pvc
>           spec:
>             storageClassName: mongo-agent-sc
>             accessModes: [ "ReadWriteOnce" ]
>             resources:
>               requests:
>                 storage: 20Gi
> 
> ---
> apiVersion: v1
> kind: Secret
> metadata:
>   name: password-admin
> type: Opaque
> stringData:
>   password: xxxxxxx
> ---
> apiVersion: v1
> kind: Secret
> metadata:
>   name: password-user1
> type: Opaque
> stringData:
>   password: xxxxxxx
> ```
> 
> This show below,
> 
> ```
> name@host:~$ kubectl get pvc -n mongodb
> NAME                                   STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS     AGE
> data-volume-mongodb-replicaset-0       Pending                                                       13m
> mongo-agent-pvc-mongodb-replicaset-0   Pending                                      mongo-agent-sc   13m
> mongod-pvc-mongodb-replicaset-0        Pending                                      mongod-sc        13m
> ```
> 
> I am not sure why 'data-volume' pvc triggered even with customized statefulset.
> Is mongodb community operator still incomplete for persistent volume? or error in my deployment? Please kindly review my error..Thanks.. :)

I solved the issue with create persistence volume and persistence volume claim by manual, and with storageclass is 'manual'. Can you show me describe pvc from mongod-pvc-mongodb-replicaset-0 ?

**Comment by jyyoo0530** [comment]
> I solved the issue with create persistence volume and persistence volume claim by manual, and with storageclass is 'manual'. Can you show me describe pvc from mongod-pvc-mongodb-replicaset-0 ?

Hi,

pvc status,
```
Name:          mongod-pvc-mongodb-replicaset-0
Namespace:     mongodb
StorageClass:  mongod-sc
Status:        Pending
Volume:        
Labels:        app=mongodb-replicaset-svc
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       mongodb-replicaset-0
Events:
  Type    Reason                Age                  From                         Message
  ----    ------                ----                 ----                         -------
  Normal  WaitForFirstConsumer  4m46s                persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  WaitForPodScheduled   4s (x19 over 4m34s)  persistentvolume-controller  waiting for pod mongodb-replicaset-0 to be scheduled
```
Can you share the piece of your pv/sc/deployment yaml files includes volume mounting parts to compare with mine, if possible? Thanks..!!

**Comment by XamYp** [comment]
> Same issue. Pls check my deployment and pv, sc yaml.

Hello, can you attach your yaml files in your message please? Specifically the volume claim, the volume claim persist?

Thank you

**Comment by jyyoo0530** [comment]
> > Same issue. Pls check my deployment and pv, sc yaml.
> 
> Hello, can you attach your yaml files in your message please? Specifically the volume claim, the volume claim persist?
> 
> Thank you

Hello, 

All of the contents in the deployment,pv,sc files are included in my previous question in the Code Block :)
For the volume claim part, you can see `volumeClaimTemplates` from my deployment.yaml.

Hope you already solved this issue so as to advise me.

**Comment by XamYp** [comment]
> > > Same issue. Pls check my deployment and pv, sc yaml.
> > 
> > 
> > Hello, can you attach your yaml files in your message please? Specifically the volume claim, the volume claim persist?
> > Thank you
> 
> Hello,
> 
> All of the contents in the deployment,pv,sc files are included in my previous question in the Code Block :)
> For the volume claim part, you can see `volumeClaimTemplates` from my deployment.yaml.
> 
> Hope you already solved this issue so as to advise me.

Hello,

Sorry my question was addressed to @yuswitayudi ^^

**Comment by yuswitayudi** [comment]
Hai

> > > > Same issue. Pls check my deployment and pv, sc yaml.
> > > 
> > > 
> > > Hello, can you attach your yaml files in your message please? Specifically the volume claim, the volume claim persist?
> > > Thank you
> > 
> > 
> > Hello,
> > All of the contents in the deployment,pv,sc files are included in my previous question in the Code Block :)
> > For the volume claim part, you can see `volumeClaimTemplates` from my deployment.yaml.
> > Hope you already solved this issue so as to advise me.
> 
> Hello,
> 
> Sorry my question was addressed to @yuswitayudi ^^

Hay @XamYp this is my pv and pvc yaml file

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-volume-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-volume-2"

```

pvc yaml

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-example-mongodb-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-example-mongodb-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```
By the way this metadata.name from pvc is same with pvc mongodb kubernetes operator automatically created. And i insert the pvc yaml below mongodb.com_v1_mongodbcommunity_cr.yaml file.

Thanks.
