### ISSUE TITLE
RBAC issue with Operator v0.5.1 on OpenShift 4.5: the MongoDBCommunity CR fails

### ISSUE THREAD

**Issue by axelbarjon** [mongodb/mongodb-kubernetes-operator#367]
**What did you do to encounter the bug?**
1. Applied v0.5.1 CRD, Role (for the namespace not clusterwide), Role Bindings and service account
```
config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
config/rbac/role.yaml
config/rbac/service_account.yaml
config/rbac/role_binding.yaml
```
2. Applied the following Manager (for OpenShift)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-kubernetes-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-kubernetes-operator
  template:
    metadata:
      labels:
        name: mongodb-kubernetes-operator
    spec:
      serviceAccountName: mongodb-kubernetes-operator
      containers:
        - name: mongodb-kubernetes-operator
          image: quay.io/mongodb/mongodb-kubernetes-operator:0.5.1
          command:
            - /usr/local/bin/entrypoint
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MANAGED_SECURITY_CONTEXT
              value: 'true'
            - name: OPERATOR_NAME
              value: "mongodb-kubernetes-operator"
            - name: AGENT_IMAGE # The MongoDB Agent the operator will deploy to manage MongoDB deployments
              value: quay.io/mongodb/mongodb-agent:10.27.0.6772-1
            - name: READINESS_PROBE_IMAGE
              value: quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.1
            - name: VERSION_UPGRADE_HOOK_IMAGE
              value: quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
            - name: MONGODB_IMAGE
              value: "library/mongo"
            - name: MONGODB_REPO_URL
              value: "registry.hub.docker.com"
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 50Mi
```
3. Added the secrets for my mongoDB users
4. Tried to deploy the following MongoDBCommunity CR:

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-dev
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.3"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: admin-scram
    - name: rootUser
      db: admin
      passwordSecretRef:
        name: root-password
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: root-scram
  statefulSet:
    spec:
      serviceName: mongodb-dev-svc
      selector: {}
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              env:
                - name: MANAGED_SECURITY_CONTEXT
                  value: "true"
            - name: "mongod"
              env:
                - name: MANAGED_SECURITY_CONTEXT
                  value: "true"
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
```
5. I get the following status for my MongoDBCommunity CR YAML:
```
status:
  currentMongoDBMembers: 3
  currentStatefulSetReplicas: 3
  message: >-
    Error creating/updating StatefulSet: error creating/updating StatefulSet:
    statefulsets.apps "mongodb-dev" is forbidden: cannot set
    blockOwnerDeletion if an ownerReference refers to a resource you can't set
    finalizers on: , <nil>
  mongoUri: ''
  phase: Failed
```

**What did you expect?**
I expect the CR to create successfully the StatefulSet

**What happened instead?**
CR deployment stays in Failed status

**Operator Information**
 - Operator Version: 0.5.1
 - MongoDB Image used: 4.4.3 from registry.hub.docker.com

**Kubernetes Cluster Information**
 - Distribution: Openshift
 - Version: 4.5
 - Image Registry location (quay, or an internal registry): quay
