### ISSUE TITLE
The operator fails to instantiate a database with an error on agent-health-status

### ISSUE THREAD

**Issue by davesargrad** [mongodb/mongodb-kubernetes-operator#410]
**What did you do to encounter the bug?**
I created the operator following the process [here](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md).

I then tried to create a mongodb.. but it fails with a crashloopbackoff

```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: learning-center-mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: changeme

```

LOGS PV: 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-logs-pv
  labels:
    app: learning-center-mongodb-svc
spec:
  capacity:
    storage: 10Gi
  claimRef:
    namespace: default
    name: logs-volume-learning-center-mongodb-0
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/storage/mongo/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - qatar.corp.sensis.com

```

Data PV

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  labels:
    app: learning-center-mongodb-svc
spec:
  capacity:
    storage: 10Gi
  claimRef:
    namespace: default
    name: data-volume-learning-center-mongodb-0
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/storage/mongo/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - qatar.corp.sensis.com

```

Mongo seems to be able to write to that local storage since we see these folders get created.

```
[root@qatar mongo]# ls -altr data
total 0
drwxrwxrwx 4 root root 30 Mar 31 09:27 ..
drwxr-sr-x 2 root 2000  6 Mar 31 13:34 configdb
drwxr-sr-x 2 root 2000  6 Mar 31 13:34 db
drwxrwsrwx 4 root 2000 32 Mar 31 13:34 .
[root@qatar mongo]# ls -altr logs
total 0
drwxrwxrwx 4 root root 30 Mar 31 09:27 ..
drwxr-sr-x 2 root 2000  6 Mar 31 13:34 healthstatus
drwxrwsrwx 3 root 2000 26 Mar 31 13:34 .
[root@qatar mongo]# pwd
/home/storage/mongo
[root@qatar mongo]# hostname
qatar.corp.sensis.com

```

**What did you expect?**
No CrashloopBackoff

**What happened instead?**
CrashLoopBackoff

```
[dsargrad@malta cfg]$ kubectl get pv
NAME            CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                           STORAGECLASS    REASON   AGE
mongo-data-pv   10Gi       RWO            Retain           Bound    default/data-volume-learning-center-mongodb-0   local-storage            171m
mongo-logs-pv   10Gi       RWO            Retain           Bound    default/logs-volume-learning-center-mongodb-0   local-storage            178m
[dsargrad@malta cfg]$ kubectl get pvc
NAME                                    STATUS   VOLUME          CAPACITY   ACCESS MODES   STORAGECLASS    AGE
data-volume-learning-center-mongodb-0   Bound    mongo-data-pv   10Gi       RWO            local-storage   168m
logs-volume-learning-center-mongodb-0   Bound    mongo-logs-pv   10Gi       RWO            local-storage   168m
[dsargrad@malta cfg]$ kubectl get pods
NAME                                           READY   STATUS             RESTARTS   AGE
learning-center-mongodb-0                      1/2     CrashLoopBackOff   18         168m
mongodb-kubernetes-operator-6bc49857dc-clsq4   1/1     Running            0          22h

```

**Screenshots**

```
[dsargrad@malta cfg]$ kubectl logs -f learning-center-mongodb-0 -c mongod
2021-03-31T17:34:17.408Z        INFO    versionhook/main.go:33  Running version change post-start hook
2021-03-31T17:34:17.408Z        INFO    versionhook/main.go:40  Waiting for agent health status...
2021-03-31T17:34:18.408Z        ERROR   versionhook/main.go:48  Error getting the agent health file: error opening file: open /healthstatus/agent-health-status.json: no such file or directory
main.main
        /go/cmd/versionhook/main.go:48
runtime.main
        /usr/local/go/src/runtime/proc.go:203

```

**Operator Information**
 - Operator Version 
     - Image:         quay.io/mongodb/mongodb-kubernetes-operator:0.5.2

**Kubernetes Cluster Information**
 - Distribution
 - Version : 1.20
 - Image Registry location (quay, or an internal registry)

**Comment by bznein** [comment]
Hi @davesargrad,

this looks like the same issue reported in #406,

that error message is expected, however the error actually comes from the other container.

Can you try changing your `MONGODB_AGENT` tag to `quay.io/mongodb/mongodb-agent:10.29.0.6830-1` and see if the issue is fixed? 

Thanks!

**Comment by davesargrad** [comment]
@bznein Thanks for your fast response.. How do I change that tag?

**Comment by davesargrad** [comment]
My bad.. I did call that:

`kubectl create -f config/manager/manager.yaml --namespace default`

**Comment by bznein** [comment]
Hi @davesargrad, yes you need this line here: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/manager/manager.yaml#L35

let me know if that works!

Regards

**Comment by davesargrad** [comment]
Ok.. Looks like the value was 10.27....

```
     containers:
        - name: mongodb-kubernetes-operator
          image: quay.io/mongodb/mongodb-kubernetes-operator:0.5.2
          command:
            - /usr/local/bin/entrypoint
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mongodb-kubernetes-operator"
            - name: AGENT_IMAGE # The MongoDB Agent the operator will deploy to manage MongoDB deployments
              value: quay.io/mongodb/mongodb-agent:10.27.0.6772-1

```

**Comment by davesargrad** [comment]
Ok.. I've recreated the operator with 10.29..

```
[dsargrad@malta manager]$ kubectl describe pod  mongodb-kubernetes-operator-674c554bc4-g2g64
Name:         mongodb-kubernetes-operator-674c554bc4-g2g64
Namespace:    default
Priority:     0
Node:         chad.corp.sensis.com/10.93.98.23
Start Time:   Wed, 31 Mar 2021 15:18:25 -0400
Labels:       name=mongodb-kubernetes-operator
              pod-template-hash=674c554bc4
Annotations:  cni.projectcalico.org/podIP: 192.169.1.3/32
              cni.projectcalico.org/podIPs: 192.169.1.3/32
Status:       Running
IP:           192.169.1.3
IPs:
  IP:           192.169.1.3
Controlled By:  ReplicaSet/mongodb-kubernetes-operator-674c554bc4
Containers:
  mongodb-kubernetes-operator:
    Container ID:  docker://b00d84e3092d33ec4cb08535a267e92273de4a1c47a9c578e896fa5d8657b4df
    Image:         quay.io/mongodb/mongodb-kubernetes-operator:0.5.2
    Image ID:      docker-pullable://quay.io/mongodb/mongodb-kubernetes-operator@sha256:3ea8935ce639ef43ca1aa25ff244719a163d6e081f398674eb678f8bd475bdfa
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/entrypoint
    State:          Running
      Started:      Wed, 31 Mar 2021 15:18:26 -0400
    Ready:          True
    Restart Count:  0
    Environment:
      WATCH_NAMESPACE:             default (v1:metadata.namespace)
      POD_NAME:                    mongodb-kubernetes-operator-674c554bc4-g2g64 (v1:metadata.name)
      OPERATOR_NAME:               mongodb-kubernetes-operator
      AGENT_IMAGE:                 quay.io/mongodb/mongodb-agent:10.29.0.6830-1
      VERSION_UPGRADE_HOOK_IMAGE:  quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
      READINESS_PROBE_IMAGE:       quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.1
      MONGODB_IMAGE:               library/mongo
      MONGODB_REPO_URL:            registry.hub.docker.com
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-kubernetes-operator-token-ldwsr (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  mongodb-kubernetes-operator-token-ldwsr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-kubernetes-operator-token-ldwsr
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  13s   default-scheduler  Successfully assigned default/mongodb-kubernetes-operator-674c554bc4-g2g64 to chad.corp.sensis.com
  Normal  Pulling    14s   kubelet            Pulling image "quay.io/mongodb/mongodb-kubernetes-operator:0.5.2"
  Normal  Pulled     13s   kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator:0.5.2" in 369.862623ms
  Normal  Created    13s   kubelet            Created container mongodb-kubernetes-operator
  Normal  Started    13s   kubelet            Started container mongodb-kubernetes-operator

```

**Comment by davesargrad** [comment]
Yay

```
[dsargrad@malta cfg]$ kubectl get pods
NAME                                           READY   STATUS    RESTARTS   AGE
learning-center-mongodb-0                      2/2     Running   0          32s
mongodb-kubernetes-operator-674c554bc4-g2g64   1/1     Running   0          2m27s

```

**Comment by davesargrad** [comment]
What is the best way for me to stand up a pod that uses the mongod command line to test out my database? 

Also is it true that I can only connect to this database from a node within the cluster? I'd like to also test it by connecting from a node outside the cluster.

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/113286250-f01d7700-92b9-11eb-8491-c36aed99af73.png)

**Comment by davesargrad** [comment]
Far better results if I use

`mongo "mongodb://learning-center-mongodb-svc.default.svc.cluster.local:27017/?replicaSet=learning-center-mongodb" --username my-user --password changeme --authenticationDatabase admin`

Services
![image](https://user-images.githubusercontent.com/48793689/113291131-8fde0380-92c0-11eb-95f0-0a840a78512c.png)

Replicasets
![image](https://user-images.githubusercontent.com/48793689/113291168-a1bfa680-92c0-11eb-9c60-ed9b0a8792ae.png)

**Comment by bznein** [comment]
> What is the best way for me to stand up a pod that uses the mongo command line client to test out my database?

I think deploying a simple `mongodb` pod could be done with something like this:

` kubectl create deployment --image=mongo mongo`

> Also is it true that I can only connect to this database from a node within the cluster? I'd like to also test it by connecting from a node outside the cluster.

Yes, we don't support for now a way to access the db from outside the cluster

I think some people in the community have tried different ways to achieve this but I can't help you with it, I'm sorry

**Comment by davesargrad** [comment]
@bznein Hi. Thanks for your help. You are quite responsive. I don't really need to connect from outside the cluster.. it just seemed like an interesting way to test. Anyways, at this point I am good to go.

Thanks again.

**Comment by davesargrad** [comment]
Hi @bznein 

When I create a database using the following the user can't seem to write to any databases:


```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: learning-center-mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
```

This is the failure that I see on insert:

![image](https://user-images.githubusercontent.com/48793689/113760540-56ecc700-96e4-11eb-8ffa-02f346a10408.png)

How can I modify the roles so that the user can do writes?
