### ISSUE TITLE
unable to create replicaset from sample

### ISSUE THREAD

**Issue by umrikar** [mongodb/mongodb-kubernetes-operator#464]
Hi,
   I followed steps on https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md#deploy-a-replica-set

but pods remained in pending state, as volume claims were not available , is there any additional step required to perform before this?

Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  2m39s (x800 over 19h)  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.

Image:      registry.hub.docker.com/library/mongo:4.2.6

**Comment by jwenjian** [comment]
Same  issue, attach below output of `kubectl describe pvc logs-volume-example-mongodb-0`

```
Name:          logs-volume-example-mongodb-0
Namespace:     default
StorageClass:
Status:        Pending
Volume:
Labels:        app=example-mongodb-svc
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       example-mongodb-0
Events:
  Type    Reason         Age                     From                         Message
  ----    ------         ----                    ----                         -------
  Normal  FailedBinding  3m16s (x962 over 4h3m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

```

**Comment by chatton** [comment]
Hi @umrikar @jwenjian 

by default the operator will use whatever the current default storageclass is. This can be different based on your provider. You are able to specify a storageclass of your choosing.

You can refer to #157 with examples for this.

Please let me know if this helps you fix the problem!

**Comment by umrikar** [comment]
@chatton , can i specify my own persistent volume and claim in statefulset, i did try it but its taking data-volume and logs-volume only,

apiVersion: mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.0.6

can i specify persistent volumes and claims inside above manifest, i did try but it didnt change anything it was still using default volume and claims,is there any other way to use my own persistent volumes and claims

**Comment by umrikar** [comment]
> 
> 
> Hi @umrikar @jwenjian
> 
> by default the operator will use whatever the current default storageclass is. This can be different based on your provider. You are able to specify a storageclass of your choosing.
> 
> You can refer to #157 with examples for this.
> 
> Please let me know if this helps you fix the problem!

i looked at example given there and tried to apply it i got below error
**no matches for kind "MongoDB" in version "mongodb.com/v1"**

`apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: volume-claim-templates-mdb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  persistent: true
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "my-storage-class"
            resources:
              requests:
                storage: 1Gi`

**Comment by tobias-neubert** [comment]
Hi, I too am not able to create a mongodb stateful with a different error. But your resource definition looks strange to me. The definition of the storage to use is not as described here: https://docs.mongodb.com/kubernetes-operator/v1.10/reference/k8s-operator-specification/. At the end of this section you can find an example. Nowhere in that description I can find the use of a volumeClaimTemplates section. 

I currently try to use a hetzner volume (hetzner.com) like so:

```
spec:
  members: 1
  type: ReplicaSet
  persistent: true
  version: "4.2.6"
  podSpec:
    persistence:
      single:
        storage: "8Gi"
        storageClass: hcloud-volumes
        labelSelector:
          matchExpressions:
            - { key: app, operator: In, values: [ myapp ] }
            - { key: type, operator: In, values: [ mongodb ] }
```

I have a volume definition matching the matchExpression from above:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume
  labels:
    app: myapp
    type: mongodb
spec:
  storageClassName: hcloud-volumes
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    volumeHandle: "my-volume-id"
    driver: csi.hetzner.cloud
    fsType: ext4

```

With this, the StatefulSet that is being created reports the following error:

```
create Claim logs-volume-system-mongodb-0 for Pod system-mongodb-0 in StatefulSet system-mongodb failed error: persistentvolumeclaims "logs-volume-system-mongodb-0" is forbidden: Internal error occurred: 2 default StorageClasses were found
```

So, maybe it helps. And if so, maybe you are able to solve the "forbidden" error and tell me how :-)

**Comment by tobias-neubert** [comment]
Ok, No you are right, volumeClaimTemplate works. I think I am confused about the available documentation :-) The solution that works for me is described here: https://github.com/mongodb/mongodb-kubernetes-operator/issues/460

**Comment by jwenjian** [comment]
I tried with custom storage class (LPV) OK with members == 1

**Comment by umrikar** [comment]
Hi,
      I have below PV and PVC which is present for all nodes in my k8s cluster , i want to use same to bind volumes in pods created using statefulset, is there way to do it.
**#PV**
```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: storage-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data/lxa/mongo/"
```

#**PVC**
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```

**I did try like below to use same persistent volume but it didn't work, It was still looking for claims logs-volume-system-mongodb-0 and data-volume-system-mongodb-0**

---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: system-mongodb
  labels:
    app: moderetic
    type: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: moderetic
      db: moderetic
      passwordSecretRef:
        name: mongodb-secret
      roles:
        - name: clusterAdmin
          db: moderetic
        - name: userAdminAnyDatabase
          db: moderetic
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    storage.wiredTiger.engineConfig.cacheSizeGB: 1.5
  persistent: true
  statefulSet:
    spec:
      template:
        spec:
          volumes:
              - name: logs-volume
                persistentVolumeClaim:
                    claimName: storage-volume-claim
              - name: data-volume
                persistentVolumeClaim:
                    claimName: storage-volume-claim
          containers:
            - name: mongod
              resources:
               requests:
                  cpu: 1
                  memory: 1Gi
                limits:
                  memory: 8Gi
            - name: mongodb-agent
              resources:
                requests:
                  memory: 50Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
