### ISSUE TITLE
Unable to make PodAntiAffinity works with Operator 0.6.0

### ISSUE THREAD

**Issue by jmcollin78** [mongodb/mongodb-kubernetes-operator#472]
**What did you do to encounter the bug?**
I try many combination to make PodAntiAffinity works without success.
found in reading the code (but I'm not a Go dev):
```
  stateFulSet:
     spec:
       template:
         spec:
           affinity:
             podAntiAffinity:
               preferredDuringSchedulingIgnoredDuringExecution:
                 - podAffinityTerm:
                    labelSelector:
                       matchLabels:
                       -  app: mongodb-core-svc
                    topologyKey: "kubernetes.io/hostname"
                  weight: 100
```
or like found here: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
```
...
     template:
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                      - key: app
                        operator: In
                        values:
                        - mongodb-core-svc
                    topologyKey: "kubernetes.io/hostname"
```
or like found here: https://github.com/mongodb/mongodb-kubernetes-operator/issues/426

```
      template:
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app: mongodb-core-svc
                    topologyKey: "kubernetes.io/hostname"
```

**What did you expect?**
Each pod should be located on a different node (seen with kubernetes describe nodes).
Ideally a documentation or a code example should show how to configure this.

**What happened instead?**
All pods are located on the same node, and a "Pod errors: Unschedulable" occurs due to colocalisation.

**Operator Information**
 - Operator Version: 0.6.0
 - MongoDB Image used: 4.4.5

**Kubernetes Cluster Information**
 - Distribution : 1.18.17-gke.100
 - Version
 - Image Registry location: quay

**Comment by jmcollin78** [comment]
Hello, I've got finally makes it works successfully with this configuration:

```
statefulSet:
  spec:
     template:
        spec:
          # This seems to work
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: topology.kubernetes.io/zone
                - weight: 50
                  podAffinityTerm:
                    topologyKey: kubernetes.io/hostname
```

I hope this will helps someone.

May be a little documentation about this or an example is a good idea.
Note: it don't works with `requiredDuringSchedulingIgnoredDuringExecution`
