### ISSUE TITLE
"logs-volume-system-mongodb-0" is forbidden: Internal error occurred

### ISSUE THREAD

**Issue by tobias-neubert** [mongodb/mongodb-kubernetes-operator#473]
Hi, most likely this is not a bug but I made a mistake. But because I cannot find any more information that can help solving the problem, I want to ask for help here.

The StatefulSet that is being created by the operator reports the following error and I don't know what to do.

```
create Claim logs-volume-system-mongodb-0 for Pod system-mongodb-0 
in StatefulSet system-mongodb failed error: persistentvolumeclaims 
"logs-volume-system-mongodb-0" is forbidden: Internal error occurred: 2 default StorageClasses were found
```

The definition of the ReplicaSet is as follows:

```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: system-mongodb
  labels:
    app: moderetic
    type: mongodb
spec:
  members: 1
  type: ReplicaSet
  persistent: true
  version: "4.2.6"
  logLevel: INFO
  podSpec:
    persistence:
      single:
        storage: "8Gi"
        storageClass: hcloud-volumes
        labelSelector:
          matchExpressions:
            - { key: app, operator: In, values: [ moderetic ] }
            - { key: type, operator: In, values: [ mongodb ] }
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: moderetic
      db: moderetic
      passwordSecretRef:
        name: mongodb-secret
      roles:
        - name: clusterAdmin
          db: moderetic
        - name: userAdminAnyDatabase
          db: moderetic
      scramCredentialsSecretName: moderetic-scram-secret
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
```

The volume that I want the pod to use is defined as follows:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume
  labels:
    app: moderetic
    type: mongodb
spec:
  storageClassName: hcloud-volumes
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    volumeHandle: "XXXXXXXX"
    driver: csi.hetzner.cloud
    fsType: ext4
```

it is backed by a volume I created at hetzner.com. I am using other volumes for other pods there already, so I know that it works in general.

I am using the mongodb-kubernetes-operator:0.6.0 in its own namespace. The mongodb resource is being created in a different namespace. I followed the instructions in the README of the operator to accomplish this.

Find attached the result ```kubectl describe statefulset system-mongodb -n moderetic-dev```

I am thankful for any help you can provide.

Tobias
[system-mongodb.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6446360/system-mongodb.txt)
