### ISSUE TITLE
Operator overwrites Pod annotations

### ISSUE THREAD

**Issue by caiorcferreira** [mongodb/mongodb-kubernetes-operator#482]
**What did you do to encounter the bug?**
If deploying a Replica set with the below `MongoDBCommunity`, the Pod annotations defined on the `statefulSet.template.metadata` are overwritten by the annotation `agent.mongodb.com/version` after the `mongodb-agent` reachs its goal state.

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: sandbox-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.13"
  featureCompatibilityVersion: "4.2"
  security:
    tls:
      optional: true
      enabled: true
      certificateKeySecretRef:
        name: sandbox-mongodb-cert
      caConfigMapRef:
        name: sandbox-mongodb-ca
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: admin
    - name: exporter
      db: admin
      passwordSecretRef:
        name: exporter-password
      roles:
        - name: clusterMonitor
          db: admin
        - name: read
          db: local
      scramCredentialsSecretName: exporter
  statefulSet:
    spec:
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: "9216"
        spec:
          terminationGracePeriodSeconds: 90
          containers:
            - name: mongod
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "2"
                  memory: 1250M
                requests:
                  cpu: "2"
                  memory: 1000M
            - name: mongodb-agent
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "1"
                  memory: 650M
                requests:
                  cpu: "1"
                  memory: 500M
            - name: mongodb-monitor
              env:
                - name: EXPORTER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: exporter-password
                      key: password
                - name: MONGODB_URI
                  value: mongodb://exporter:$(EXPORTER_PASSWORD)@127.0.0.1:27017/
              image: interal-registry.io/monitor:1.0.0
              imagePullPolicy: IfNotPresent
              ports:
              - name: metrics
                containerPort: 9216
                protocol: TCP
              resources:
                limits:
                  cpu: "0.5"
                  memory: 800M
                requests:
                  cpu: "0.5"
                  memory: 500M
```

I belive the code responsible for this behaviour is this function: https://github.com/mongodb/mongodb-kubernetes-operator/blob/ad71d9494e388327f8575dd7f284cf13f08fa8d5/pkg/readiness/pod/podannotation.go#L14-L32

**What did you expect?**
The annotations should be preserved on the Pod definition.

**What happened instead?**
The Pod annotations are being overwritten.

**Operator Information**
 - Operator Version: v0.6.0
 - MongoDB Image used: mongo:4.2.13
