### ISSUE TITLE
Cannot add label and additional port to the default clusterIP service

### ISSUE THREAD

**Issue by dgdevops** [mongodb/mongodb-kubernetes-operator#487]
Hello Everyone,

I am trying to add custom port & label to the default clusterIP service (<rs_name>-svc) in order to enable metric scraping for Prometheus. To achieve this Prometheus is looking for kubernetes service(s) with a specific label & port name.
As I checked the default service that the Operator creates would be a great fit if it had the label and custom port Prometheus is looking for. Is there any way to add additional port and label to the default clusterIP service from code?

**Default svc**:
```
spec:
  ports:
      protocol: TCP
      port: 27017
      targetPort: 27017
```

**Modified svc**:
```
  labels:
    app: mongodb-exporter
spec:
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
    - name: mongodb-exporter
      protocol: TCP
      port: 9216
      targetPort: 9216
```

Thank you for the help
