### ISSUE TITLE
Node affinity error on udpate

### ISSUE THREAD

**Issue by steeling** [mongodb/mongodb-kubernetes-operator#489]
On a regular update, getting a node affinity error 

```
  Warning  FailedScheduling  15h   default-scheduler  0/1 nodes are available: 1 node(s) had volume node affinity conflict.
```

I believe this is due to the PVC being attached to the node, and the pod not being able to reattach to that specific node. Any tips to avoid this?

**Comment by irajdeep** [comment]
Hi @steeling, indeed this seems to be a PVC/Node infrastructure issue. 

There are some ideas mentioned in this link: https://stackoverflow.com/questions/51946393/kubernetes-pod-warning-1-nodes-had-volume-node-affinity-conflict. Could you please try them out and let's know if it works?

**Comment by steeling** [comment]
I ended up just deleting all the PVC's and the pods and recreating, since this was in a dev cluster. Since these PVC's are created by the operator, is there a way to implement a fix? I'm a little afraid of this happening in production.

Is there a way to accomplish this through the operator to specify the affinity, or better yet to prefer not node-bound PVC's?

**Comment by antonlisovenko** [comment]
hi @steeling 

could you please provide the specification of the replica set Custom Resource you are creating/updating?
I'm interested if you provide the PVC templates specification as the Operator doesn't create any PVCs.

This is a working example of the PVC templates: https://github.com/mongodb/mongodb-kubernetes-operator/blob/2c77ad7f25661a0a35253b9860d2491a636606bb/controllers/testdata/volume_claim_templates_mdb.yaml

**Comment by steeling** [comment]
Gotcha, ya I didn't add any originally, is that the recommendation? Note this is on AKS

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.4"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-admin-password
      roles:
        - name: readWrite
          db: production
      scramCredentialsSecretName: mongodb
```
