### ISSUE TITLE
PVC is always created with fixed 10Gi for data and 2Gi for logs no matter what is specify in deployment

### ISSUE THREAD

**Issue by vasRK** [mongodb/mongodb-kubernetes-operator#510]
pvc is always created with fixed 10Gi for data and 2Gi for logs no matter what is specify

**What did you expect?**
pvc is not created with 64Gi, always PVC size is set to 10Gi

**Screenshots**

<img width="1440" alt="upload_mongo" src="https://user-images.githubusercontent.com/11040197/119811769-169c0f00-bf05-11eb-9933-0df6c0a363bd.png">

**Operator Information**
 - Operator Version: quay.io/mongodb/mongodb-kubernetes-operator:0.6.0
 - MongoDB Image used: 4.2.6

**Kubernetes Cluster Information**
 - Distribution: Ubuntu 18.04.5 LTS
 - Version : 1.18.4
 - Image Registry location : quay

Deployment yaml
 - `---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: rush-mongodb
spec:
  persistent: true
  members: 1
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: ffbadmin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  podSpec:
    # `podTemplate.spec.containers[].resources` should be specified otherwise, WiredTiger
    # cache won't be calculated properly by MongoDB daemon.

    # "multiple" persistence allows to mount different directories to different
    # Persistent Volumes
    persistence:
      multiple:
        data:
          storage: 64Gi
        journal:
          storage: 4Gi
        logs:
          storage: 2Gi

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: `

**Comment by bznein** [comment]
Hi @vasRK,

it looks like the spec you are using are coming from our enterprise operator. In the community operator we do not have fields such as `persistence.single` and `persistence.multiple`.


The following is an example of how you can modify the resource to specify a 64Gi storage for the data volume:


```
apiVersion: mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: change-data-volume-mdb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            resources:
              requests:
                storage: 64Gi
```
