### ISSUE TITLE
mongodb-agent on OpenShift fails to get current user

### ISSUE THREAD

**Issue by bliemli** [mongodb/mongodb-kubernetes-operator#58]
When deploying the operator on OpenShift, the mongodb Pods from the StatefulSet fail to start:

```
$ oc logs mongodb-0 -c mongodb-agent
panic: Failed to get current user: user: unknown userid 1001130000
 
goroutine 1 [running]:
com.tengen/cm/util.init.3()
        /data/mci/bd62cd177fa9529ccacb53e13b1bf2a3/mms-automation/build/go-dependencies/src/com.tengen/cm/util/user.go:14 +0xe5
```

**Comment by chatton** [comment]
Hi @bliemli 

In order for the operator to run correctly in Openshift, you'll need to add the following environment variable to the operator pod

```yaml
            - name: MANAGED_SECURITY_CONTEXT
              value: 'true'
```

so the full deployment would be 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-kubernetes-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-kubernetes-operator
  template:
    metadata:
      labels:
        name: mongodb-kubernetes-operator
    spec:
      serviceAccountName: mongodb-kubernetes-operator
      containers:
        - name: mongodb-kubernetes-operator
          image: quay.io/mongodb/mongodb-kubernetes-operator:0.0.6
          command:
          - mongodb-kubernetes-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MANAGED_SECURITY_CONTEXT
              value: 'true'
            - name: OPERATOR_NAME
              value: "mongodb-kubernetes-operator"
            - name: AGENT_IMAGE # The MongoDB Agent the operator will deploy to manage MongoDB deployments
              value: quay.io/mongodb/mongodb-agent:10.13.0.6199-1
            - name: PRE_STOP_HOOK_IMAGE
              value: quay.io/mongodb/mongodb-kubernetes-operator-pre-stop-hook:1.0.0

```
