### ISSUE TITLE
external connection to mongodb replicaset from loadbalancer ip

### ISSUE THREAD

**Issue by samaiyayashraj** [mongodb/mongodb-kubernetes-operator#591]
So I'm trying to connect to the MongoDB replica set from a mongo shell installed on my local system. 
Below is the YAML I'm using for the deployment . 
I'm creating a service of type LoadBalancer to access the MongoDB replica set from outside of the K8s cluster.
Getting an authentication error when I try to access from outside but it works fine when exec in one of the MongoDB pods & run the same command.
Is it not possible to connect to MongoDB replicaset even if I use service type loadbalancer or NodePort from outside k8s cluster ????????

---

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-0
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-0-admin-password
      roles:
        - name: root
          db: admin
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-0
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  persistent: true
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: 200m
                  memory: 1Gi
                limits:
                  memory: 5Gi
            - name: mongodb-agent
              resources:
                requests:
                  memory: 50Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: vsan-bloc-sc
            resources:
              requests:
                storage: 50G
        - metadata:
            name: logs-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: vsan-bloc-sc
            resources:
              requests:
                storage: 10G

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-0-admin-password
type: Opaque
stringData:
  password: admin


---
apiVersion: v1
kind: Service
metadata:
  name: mongodbcommunity
spec:
  selector:
    app: mongodb-0-svc
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer
```

**The error**
mongo --username admin --password admin --authenticationDatabase admin --host 10.166.125.100 --port 27017

`MongoDB shell version v3.6.3
connecting to: mongodb://10.166.125.100:27017/admin?ssl=false
MongoDB server version: 4.4.5
WARNING: shell and server versions do not match
2021-06-23T08:22:36.946+0530 E QUERY    [thread1] Error: Authentication failed. :
DB.prototype._authOrThrow@src/mongo/shell/db.js:1608:20
@(auth):6:1
@(auth):1:2
exception: login failed`

**Comment by dgdevops** [comment]
@samaiyayashraj , based on the error the connection to the exposed replicaset member was successful and you are facing just an authentication error due to wrong credentials. The user/role configuration looks alright, check the content of the "mongodb-0-admin-password" secret to double-check the password. Additionally, if you have multiple replicasets in the Kubernetes cluster make sure to double check the IP of the LoadBalancer as well.

**Comment by ruodingt** [comment]
Hi @samaiyayashraj, @dgdevops 

Thanks for sharing your experience here.

Based on your reply I have crafted my version as well.

I was be able to connect to the secondary replica successfully. Secondary replica seems to be read only and i cannot write anything into that.

I think the Load Balancer will just redirect any request randomly to one of the 3 replica. I am very confused about how to write an proper service for this replicaSet.

Could you give me some hints how to build a proper `Service` to connect to the primary replica?

Many thanks,
Ruoding

```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: Makefog3333*
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: example-mongodb-svc
#    tier: backend
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
```
