### ISSUE TITLE
MongoDB Metrics Export

### ISSUE THREAD

**Issue by bartlomiejwulff** [mongodb/mongodb-kubernetes-operator#633]
Hello,

as far as I can see, there is no option to activate any prometheus metrics exporter for mongo here. Can you please suggest some solution which allow to export mongoDB related metrics to prometheus?

Thanks in advance,
Bartlomiej

**Comment by dgdevops** [comment]
@bartlomiejwulff,
You can inject a mongodb-exporter sidecar into your statefulset under `spec.statefulSet.spec.template.spec.containers`

**Comment by bartlomiejwulff** [comment]
@dgdevops 
Hi,

thanks for the answer. I have added an sidecar container to my template as follow:

```
- name: mongodb-exporter
              image: bitnami/mongodb-exporter:0.20.6
              command: ["/bin/sh"]
              args: ["-c", '/opt/bitnami/mongodb-exporter/bin/mongodb_exporter --discovering-mode --mongodb.indexstats-colls=someDBs --mongodb.collstats-colls=someDBs --web.listen-address=":9216" --web.telemetry-path="/metrics" --mongodb.direct-connect=false --mongodb.uri="mongodb://${DBUSER}:${DBPASS}@${DBURL}/admin?ssl=false"']
              imagePullPolicy: Always
              env:
                - name: DBURL
                  value: "localhost:27017"
                - name: DBUSER
                  value: "metrics-user"
                - name: DBPASS
                  valueFrom:
                    secretKeyRef:
                      name: metrics-user
                      key: password
              ports:
              - name: metrics
                containerPort: 9216
                protocol: TCP
              resources:
                limits:
                  cpu: "500m"
                  memory: 800M
                requests:
                  cpu: "500m"
                  memory: 500M
              securityContext:
                allowPrivilegeEscalation: false
```
