### ISSUE TITLE
Question about configuring a simple external access

### ISSUE THREAD

**Issue by unbornchikken** [mongodb/mongodb-kubernetes-operator#634]
Hi,

I want to configure a simple external access without the ttl magic. Just created a mongodb replica set with the docs provided [there](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md).

Then I've created three services to get the ports opened:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: mongodb-server-0
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30001
  selector:
    name: mongodb-server-0
    
---

kind: Service
apiVersion: v1
metadata:
  name: mongodb-server-1
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30002
  selector:
    name: mongodb-server-1

---

kind: Service
apiVersion: v1
metadata:
  name: mongodb-server-2
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30003
  selector:
    name: mongodb-server-2
```

The ports are open and listening, I can telnet in. But I cannot access it from MongoDB compass, it says:

"connection <monitor> to 127.0.0.1:30001 closed"

Connection string is: 

mongodb://admin:password@localhost:30001,localhost:30002,localhost:30003/admin?ssl=false

Does anyone have an advice? Thanks.
