### ISSUE TITLE
Resource is invalid "status.version" errors

### ISSUE THREAD

**Issue by tliron** [mongodb/mongodb-kubernetes-operator#676]
**What did you expect?**
The operator is unable to update the CR's status and the logs are showing errors like this:
```
2021-08-06T16:29:06.553Z	ERROR	controllers/replica_set_controller.go:230	Error updating the status of the MongoDB resource: MongoDBCommunity.mongodbcommunity.mongodb.com "open5gs-mongodb" is invalid: status.version: Required value	{"ReplicaSet": "workspace/open5gs-mongodb"}
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.Reconcile
	/workspace/controllers/replica_set_controller.go:230
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
```
**More context**
Operator version 0.7.0.

Trying with various versions of MongoDB: 5.0.2, 4.4.8, 4.2.6

**Comment by tliron** [comment]
Workaround for now is to comment out [this line](https://github.com/mongodb/mongodb-kubernetes-operator/blob/ed9ec900804bef5f1fb278a39b29038d0feac604/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml#L332).

**Comment by FlorentinaSimlinger** [comment]
Hi @tliron, unfortunately we weren't able to reproduce this error. Would you be able to share the custom resource yaml you are applying? Thanks

**Comment by tliron** [comment]
Sure:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity

metadata:
  name: open5gs-mongodb
  labels:
    app.kubernetes.io/name: open5gs-mongodb
    app.kubernetes.io/instance: open5gs-mongodb
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: open5gs
    app.kubernetes.io/managed-by: open5gs

spec:
  type: ReplicaSet
  members: 3
  version: 5.0.2
  security:
    authentication:
      modes: [ SCRAM ]
  users:
  - name: user
    db: admin
    passwordSecretRef:
      name: open5gs-mongodb-user-password
    roles:
    - name: root
      db: admin
    scramCredentialsSecretName: scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    storage.wiredTiger.engineConfig.cacheSizeGB: 0.25
  # The defaults are 10GB persistent volume claims, we will reduce them here
  statefulSet:
    spec:
      volumeClaimTemplates:
      - metadata:
          name: data-volume
          labels:
            app.kubernetes.io/name: open5gs-mongodb
            app.kubernetes.io/instance: open5gs-mongodb-data
            app.kubernetes.io/version: $VERSION
            app.kubernetes.io/component: 5g
            app.kubernetes.io/part-of: open5gs
            app.kubernetes.io/managed-by: open5gs
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
      - metadata:
          name: logs-volume
          labels:
            app.kubernetes.io/name: open5gs-mongodb
            app.kubernetes.io/instance: open5gs-mongodb-logs
            app.kubernetes.io/version: $VERSION
            app.kubernetes.io/component: 5g
            app.kubernetes.io/part-of: open5gs
            app.kubernetes.io/managed-by: open5gs
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

---

apiVersion: v1
kind: Secret

metadata:
  name: open5gs-mongodb-user-password

type: Opaque
stringData:
  password: password
```
