### ISSUE TITLE
Unable to run mongo server

### ISSUE THREAD

**Issue by dragonknight88** [mongodb/mongodb-kubernetes-operator#701]
**What did you do to encounter the bug?**
1. Followed operator install
2. Deploying rs. https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md

**What did you expect?**
1. mongod is running on container mongod

**What happened instead?**
1. mongod script commands failing on file access issue

```
2021-08-31T22:04:19.938Z	INFO	versionhook/main.go:34	Running version change post-start hook
2021-08-31T22:04:19.939Z	INFO	versionhook/main.go:41	Waiting for agent health status...
2021-08-31T22:04:20.939Z	ERROR	versionhook/main.go:49	Error getting the agent health file: could not open file: open /healthstatus/agent-health-status.json: no such file or directory
main.main
	/go/cmd/versionhook/main.go:49
runtime.main
	/usr/local/go/src/runtime/proc.go:225
```

**Screenshots**

**Operator Information**
 - v0.6.2
 - v4.4.0

**Kubernetes Cluster Information**
 - On premise
 - k8s 1.19.5
 - quay, docker.io

**yaml**
 ```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: demo-mongodb
  namespace: demo
  labels:
    app: "demo-mongodb"
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.0"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: 
        name: my-user-password-1
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: demo-mongodb
  statefulSet:
    spec:
      selector:
        matchLabels:
          app: demo-mongodb
        template:
          metadata:
            labels:
              app: demo-mongodb
          spec:
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
              fsGroup: 2000
            containers:
              - name: mongod
                securityContext:
                  runAsNonRoot: true
              - name: mongodb-agent
                securityContext:
                  runAsNonRoot: true
            initContainers:
              - name: mongod-posthook
                securityContext:
                  runAsNonRoot: true
              - name: mongodb-agent-readinessprobe
                securityContext:
                  runAsNonRoot: true
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
```
