### ISSUE TITLE
Resource request and limits not configurable in helmchart

### ISSUE THREAD

**Issue by freerk** [mongodb/mongodb-kubernetes-operator#703]
I've installed the operator via the helm-chart and found out that the resource requirements are not controlled via the values.yaml but 'hard-coded' in the operator deployment.

These resource requirements are quite huge, especially when trying to install the operator on a smaller cluster.

Now defaulting to:
```
resources:
  limits:
    cpu: 1100m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 200Mi
```

These should be configurable through settings in the values.yaml.
