### ISSUE TITLE
Cannot add a ImagePullSecret to the Statefulset template.

### ISSUE THREAD

**Issue by joshho** [mongodb/mongodb-kubernetes-operator#713]
**What did you do to encounter the bug?**
mongo CR
```
spec:
....
  statefulSet:
    spec:
      template:
        metadata:
          annotations:
....
        spec:
          imagePullSecrets:
            - name: "my-entitlement-key"
```

```
11 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.MongoDBCommunity: failed to list *v1.MongoDBCommunity: v1.MongoDBCommunityList.Items: []v1.MongoDBCommunity: v1.MongoDBCommunity.Spec: v1.MongoDBCommunitySpec.Users: []v1.MongoDBUser: Type: StatefulSetConfiguration: v1.StatefulSetConfiguration.SpecWrapper: unmarshalerDecoder: json: cannot unmarshal string into Go struct field PodSpec.template.spec.imagePullSecrets of type v1.LocalObjectReference, error found in #10 byte of ...|ystem"}}]}},"type":"|..., bigger context ...|sName":"rook-cephfs","volumeMode":"Filesystem"}}]}},"type":"ReplicaSet","users":[{"db":"admin","name|...
```

**What did you expect?**
Image PullSecret to be added to mongo STS

**What happened instead?**
Mongo Operator failed to merge it.

**Screenshots**

**Operator Information**
 - 0.52
 - MongoDB Image used

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by irajdeep** [comment]
Hi @joshho, I couldn't reproduce this issue. I used the following YAML to create the resource with `imagePullsecrets` and it was created successfully. Please make sure you have the correct roles and serviceAccount configured for the operator.

Pasting the yaml spec:

```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-specify-pod-resources
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.0"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: "foo"
# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: <your-password-here>
```
