### ISSUE TITLE
EmptyDir for data-volume and log-volume

### ISSUE THREAD

**Issue by petrovicboban** [mongodb/mongodb-kubernetes-operator#742]
It would be very helpful for users CI pipelines in testing phases, to start mongodb instance(s) with no data, populates initial data and proceed with testing on each run.

**What did you do to encounter the bug?**

```
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.5"
  statefulSet:
    spec:
      template:
       spec:
         volumes:
           - name: data-volume
             emptyDir: {}
           - name: log-volume
             emptyDir: {}
```

**What did you expect?**
I expect a pod to start with empty directory for data-volume and log-volume.

**What happened instead?**
Those volumes are still defined as VolumeClaimTemplates, and pod can't start if claims are not bound.

```
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-volume-mongodb-0
  - name: logs-volume
    persistentVolumeClaim:
      claimName: logs-volume-mongodb-0
```

**Operator Information**
 - v0.6.0

**Kubernetes Cluster Information**
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
