### ISSUE TITLE
Cannot verify if Mongo is communicating with other mongo pods with TLS

### ISSUE THREAD

**Issue by joshho** [mongodb/mongodb-kubernetes-operator#757]
**What did you do to encounter the bug?**
Deploy Mongo with:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: sysqa-mongodb
spec:
  additionalMongodConfig:
    net.maxIncomingConnections: 900
  members: 3
  security:
    authentication:
      ignoreUnknownUsers: true
      modes:
      - SCRAM
    tls:
      caConfigMapRef:
        name: sysqa-mongodb-cert-ca-cm
      certificateKeySecretRef:
        name: sysqa-mongodb-cert
      enabled: true
  type: ReplicaSet
  users:
  - db: admin
    name: root
    passwordSecretRef:
      key: mongodbRootPassword
      name: mongodb-authsecret
    roles:
    - db: admin
      name: clusterAdmin
    - db: admin
      name: userAdminAnyDatabase
    - db: admin
      name: readWriteAnyDatabase
    scramCredentialsSecretName: root-scram2
  - db: a_db
    name: metadata
    passwordSecretRef:
      key: mongodbMetadataPassword
      name: mongodb-authsecret
    roles:
    - db: a_db
      name: dbOwner
    scramCredentialsSecretName: metadata-scram2
  version: 4.2.16
```

**What did you expect?**
Logs to show the connection information between mongo pods.

**What happened instead?**
Logs show this:
```
oc logs sysqa-mongodb-0 -c mongod| less

2021-10-20T20:04:38.100Z        INFO    versionhook/main.go:34  Running version change post-start hook
2021-10-20T20:04:38.100Z        INFO    versionhook/main.go:41  Waiting for agent health status...
2021-10-20T20:04:39.100Z        ERROR   versionhook/main.go:49  Error getting the agent health file: could not open file: open /healthstatus/agent-health-status.json: no such file or directory
main.main
        /go/cmd/versionhook/main.go:49
runtime.main
        /usr/local/go/src/runtime/proc.go:225
```

**Screenshots**

**Operator Information**
 - 0.5.2
 - Image is 4.2.16 - MongoDB Image used

**Kubernetes Cluster Information**
 - Distribution OCP 4.6.16
 - Version - v1.20.0+9689d22 (K8)
 - Image Registry location - quay

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods
