### ISSUE TITLE
[Question] Is it possible to rotate root credentials outside of CRD? 

### ISSUE THREAD

**Issue by spartanox** [mongodb/mongodb-kubernetes-operator#772]
**What did you do to encounter the bug?**
1. Install operator locally
2. Deploy a replica set with mongo 5 and admin user with root role.
3. install and innit hashicorp Vault for key management
4. Add connection string of created database to vault and check it works
5. When the connection succeed, vault ask me to rotate root credentials and I accept
6. Credentials rotate successfully but when try to make something else with new credentials, vault tell me that there is some error.

**What did you expect?**
I expect that Vault can work with the new credentials and create new roles and users

**What happened instead?**
Vault show me an error every time I rotate  the credentials specified in the manifest, but when I edit the generated password to the same password specified in the manifest, everything work again. 

**Operator Information**
 - Operator Version: v0.7.0
 - MongoDB Image used: 5.0.3

**Manifest**:

```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: my-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.3"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: root
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-admin-password
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: admin-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-admin-password
type: Opaque
stringData:
  password: root

```
