### ISSUE TITLE
Adding replicas to replicaset doesn't work

### ISSUE THREAD

**Issue by michalschott** [mongodb/mongodb-kubernetes-operator#779]
**What did you do to encounter the bug?**
1. install mongodb-community-operator (chart 0.7.1, watch all namespaces)
2. provision MongoDB:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-database
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-database
  namespace: default
subjects:
  - kind: ServiceAccount
    name: mongodb-database
roleRef:
  kind: Role
  name: mongodb-database
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mongodb
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-selfsigned-ca
  namespace: default
spec:
  commonName: mongodb-selfsigned-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    name: mongodb
    kind: Issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: mongodb-selfsigned-ca-root-secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mongodb-ca-issuer
  namespace: default
spec:
  ca:
    secretName: mongodb-selfsigned-ca-root-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-tls-secret
  namespace: default
spec:
  dnsNames:
    - "*.example-mongodb-svc.default.svc.cluster.local"
  issuerRef:
    group: cert-manager.io
    name: mongodb-ca-issuer
    kind: Issuer
  secretName: mongodb-tls-secret
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
  namespace: default
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.10"
  security:
    tls:
      enabled: true
      certificateKeySecretRef:
        name: mongodb-tls-secret
      caCertificateSecretRef:
        name: mongodb-selfsigned-ca-root-secret
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits: {}
                requests: {}
            - name: mongodb-agent
              resources:
                limits: {}
                requests: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-password
  namespace: default
type: Opaque
stringData:
  password: admin
```

**What did you expect?**
I'd expect 3 pods of MongoDB running.

**What happened instead?**
Controller is stuck in `ReplicaSet is not yet ready, retrying in 10 seconds`.

```
mongodb-kubernetes-operator-b59b76896-9n6ph mongodb-kubernetes-operator 2021-11-12T17:31:39.686Z	INFO	controllers/replica_set_controller.go:132	Reconciling MongoDB	{"ReplicaSet": "default/example-mongodb"}
mongodb-kubernetes-operator-b59b76896-9n6ph mongodb-kubernetes-operator 2021-11-12T17:31:39.686Z	DEBUG	controllers/replica_set_controller.go:134	Validating MongoDB.Spec	{"ReplicaSet": "default/example-mongodb"}
mongodb-kubernetes-operator-b59b76896-9n6ph mongodb-kubernetes-operator 2021-11-12T17:31:39.686Z	DEBUG	controllers/replica_set_controller.go:143	Ensuring the service exists	{"ReplicaSet": "default/example-mongodb"}
mongodb-kubernetes-operator-b59b76896-9n6ph mongodb-kubernetes-operator 2021-11-12T17:31:39.697Z	INFO	controllers/replica_set_controller.go:390	The service already exists... moving forward: services "example-mongodb-svc" already exists	{"ReplicaSet": "default/example-mongodb"}
mongodb-kubernetes-operator-b59b76896-9n6ph mongodb-kubernetes-operator 2021-11-12T17:31:39.697Z	INFO	controllers/mongodb_tls.go:40	Ensuring TLS is correctly configured	{"ReplicaSet": "default/example-mongodb"}
mongodb-kubernetes-operator-b59b76896-9n6ph mongodb-kubernetes-operator 2021-11-12T17:31:39.697Z	INFO	controllers/mongodb_tls.go:94	Successfully validated TLS config	{"ReplicaSet": "default/example-mongodb"}
mongodb-kubernetes-operator-b59b76896-9n6ph mongodb-kubernetes-operator 2021-11-12T17:31:39.697Z	INFO	controllers/replica_set_controller.go:277	TLS is enabled, creating/updating TLS secret	{"ReplicaSet": "default/example-mongodb"}
mongodb-kubernetes-operator-b59b76896-9n6ph mongodb-kubernetes-operator 2021-11-12T17:31:39.702Z	DEBUG	controllers/replica_set_controller.go:348	Enabling TLS on an existing deployment, the StatefulSet must be updated first{"ReplicaSet": "default/example-mongodb"}
mongodb-kubernetes-operator-b59b76896-9n6ph mongodb-kubernetes-operator 2021-11-12T17:31:39.702Z	INFO	controllers/replica_set_controller.go:288	Creating/Updating StatefulSet	{"ReplicaSet": "default/example-mongodb"}
mongodb-kubernetes-operator-b59b76896-9n6ph mongodb-kubernetes-operator 2021-11-12T17:31:39.717Z	DEBUG	controllers/replica_set_controller.go:298	Ensuring StatefulSet is ready, with type: RollingUpdate	{"ReplicaSet": "default/example-mongodb"}
mongodb-kubernetes-operator-b59b76896-9n6ph mongodb-kubernetes-operator 2021-11-12T17:31:39.717Z	INFO	controllers/mongodb_status_options.go:110	ReplicaSet is not yet ready, retrying in 10 seconds
```

MongoDB pods are stuck:
```
NAME                READY   STATUS    RESTARTS   AGE
example-mongodb-0   1/2     Running   0          22m
example-mongodb-1   2/2     Running   0          20m
example-mongodb-2   2/2     Running   0          19m
```

agent-0:
```
example-mongodb-0 mongodb-agent [2021-11-12T17:35:14.533+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [17:35:14.533] clusterConfig unchanged
example-mongodb-0 mongodb-agent [2021-11-12T17:35:14.630+0000] [.info] [src/mongoctl/processctl.go:Update:3263] <example-mongodb-0> [17:35:14.630] <DB_WRITE> Updated with query map[] and update [{$set [{agentFeatures [StateCache]} {nextVersion 2}]}] and upsert=true on local.clustermanager
example-mongodb-0 mongodb-agent [2021-11-12T17:35:14.641+0000] [.info] [src/director/director.go:computePlan:280] <example-mongodb-0> [17:35:14.641] ... process has a plan : WaitRsConfCommitted
example-mongodb-0 mongodb-agent [2021-11-12T17:35:14.642+0000] [.info] [src/director/director.go:tracef:794] <example-mongodb-0> [17:35:14.642] Running step: 'WaitRsConfCommitted' of move 'WaitRsConfCommitted'
example-mongodb-0 mongodb-agent [2021-11-12T17:35:14.642+0000] [.info] [src/director/director.go:tracef:794] <example-mongodb-0> [17:35:14.642] because
example-mongodb-0 mongodb-agent [All the following are true:
example-mongodb-0 mongodb-agent     ['currentState.Up' = true]
example-mongodb-0 mongodb-agent     ['currentState.IsPrimary' = true]
example-mongodb-0 mongodb-agent     [CurrentState is in initialized rs :
example-mongodb-0 mongodb-agent         ['currentState.IsInReplSet' = true]
example-mongodb-0 mongodb-agent         ['currentState.ReplSetConf' != <nil> ('currentState.ReplSetConf' = ReplSetConfig{id=example-mongodb,version=1,commitmentStatus=true,configsvr=false,protocolVersion=1,forceProtocolVersion=false,writeConcernMajorityJournalDefault=true,members={id:0,HostPort:example-mongodb-0.example-mongodb-svc.default.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},settings=map[catchUpTakeoverDelayMillis:30000 catchUpTimeoutMillis:-1 chainingAllowed:true electionTimeoutMillis:10000 getLastErrorDefaults:map[w:1 wtimeout:0] getLastErrorModes:map[] heartbeatIntervalMillis:2000 heartbeatTimeoutSecs:10 replicaSetId:ObjectID("618e9f37f59e165408bef14e")]})]
example-mongodb-0 mongodb-agent     ]
example-mongodb-0 mongodb-agent     ['desiredState.ReplSetConf' != <nil> ('desiredState.ReplSetConf' = ReplSetConfig{id=example-mongodb,version=0,commitmentStatus=true,configsvr=false,protocolVersion=1,forceProtocolVersion=false,writeConcernMajorityJournalDefault=,members={id:0,HostPort:example-mongodb-0.example-mongodb-svc.default.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},{id:1,HostPort:example-mongodb-1.example-mongodb-svc.default.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},settings=map[]})]
example-mongodb-0 mongodb-agent ]
example-mongodb-0 mongodb-agent [2021-11-12T17:35:14.643+0000] [.info] [src/director/director.go:planAndExecute:564] <example-mongodb-0> [17:35:14.643] Step=WaitRsConfCommitted as part of Move=WaitRsConfCommitted in plan failed : <example-mongodb-0> [17:35:14.643] Postcondition not yet met for step WaitRsConfCommitted because
example-mongodb-0 mongodb-agent ['currentState.ReplSetConf.Members' != 'desiredState.ReplSetConf.Members' : ([{"_id":0,"arbiterOnly":false,"buildIndexes":true,"hidden":false,"host":"example-mongodb-0.example-mongodb-svc.default.svc.cluster.local:27017","priority":1,"secondaryDelaySecs":0,"tags":{},"votes":1}]) vs. ([{"_id":0,"arbiterOnly":false,"buildIndexes":true,"hidden":false,"host":"example-mongodb-0.example-mongodb-svc.default.svc.cluster.local:27017","priority":1,"secondaryDelaySecs":0,"tags":{},"votes":1},{"_id":1,"arbiterOnly":false,"buildIndexes":true,"hidden":false,"host":"example-mongodb-1.example-mongodb-svc.default.svc.cluster.local:27017","priority":1,"secondaryDelaySecs":0,"tags":{},"votes":1}])].
example-mongodb-0 mongodb-agent  Recomputing a plan...
example-mongodb-0 mongodb-agent [2021-11-12T17:35:15.555+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [17:35:15.554] clusterConfig unchanged
example-mongodb-0 mongod {"t":{"$date":"2021-11-12T17:35:15.672+00:00"},"s":"I",  "c":"SHARDING", "id":20997,   "ctx":"conn82","msg":"Refreshed RWC defaults","attr":{"newDefaults":{}}}
example-mongodb-0 mongodb-agent [2021-11-12T17:35:15.679+0000] [.info] [src/mongoclientservice/mongoclientservice.go:func1:1573] [17:35:15.679] Testing auth with username __system db=local to example-mongodb-0.example-mongodb-svc.default.svc.cluster.local:27017 (local=false) connectMode=SingleConnect ipversion=0 tls=true
example-mongodb-0 mongod {"t":{"$date":"2021-11-12T17:35:15.680+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"10.87.56.221:46034","connectionId":598,"connectionCount":5}}
example-mongodb-0 mongod {"t":{"$date":"2021-11-12T17:35:15.687+00:00"},"s":"W",  "c":"NETWORK",  "id":23234,   "ctx":"conn598","msg":"No SSL certificate provided by peer"}
example-mongodb-0 mongod {"t":{"$date":"2021-11-12T17:35:15.687+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn598","msg":"client metadata","attr":{"remote":"10.87.56.221:46034","client":"conn598","doc":{"driver":{"name":"mongo-go-driver","version":"v1.3.8+prerelease"},"os":{"type":"linux","architecture":"amd64"},"platform":"go1.15.9","application":{"name":"MongoDB Automation Agent v11.0.5.6963 (git: 65ba9b52de741e00e747a80f1a93442f9fe40695)"}}}}
example-mongodb-0 mongod {"t":{"$date":"2021-11-12T17:35:15.688+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"10.87.56.221:46036","connectionId":599,"connectionCount":6}}
example-mongodb-0 mongod {"t":{"$date":"2021-11-12T17:35:15.696+00:00"},"s":"W",  "c":"NETWORK",  "id":23234,   "ctx":"conn599","msg":"No SSL certificate provided by peer"}
example-mongodb-0 mongod {"t":{"$date":"2021-11-12T17:35:15.697+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn599","msg":"client metadata","attr":{"remote":"10.87.56.221:46036","client":"conn599","doc":{"driver":{"name":"mongo-go-driver","version":"v1.3.8+prerelease"},"os":{"type":"linux","architecture":"amd64"},"platform":"go1.15.9","application":{"name":"MongoDB Automation Agent v11.0.5.6963 (git: 65ba9b52de741e00e747a80f1a93442f9fe40695)"}}}}
example-mongodb-0 mongodb-agent [2021-11-12T17:35:15.735+0000] [.info] [src/mongoctl/processctl.go:GetKeyHashes:1985] <example-mongodb-0> [17:35:15.735] Able to successfully auth to example-mongodb-0.example-mongodb-svc.default.svc.cluster.local:27017 (local=false) using desired auth key
example-mongodb-0 mongod {"t":{"$date":"2021-11-12T17:35:15.731+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn599","msg":"Authentication succeeded","attr":{"mechanism":"SCRAM-SHA-256","speculative":false,"principalName":"__system","authenticationDatabase":"local","remote":"10.87.56.221:46036","extraInfo":{}}}
```

agent-1:
```
example-mongodb-1 mongodb-agent [2021-11-12T17:36:07.259+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [17:36:07.258] clusterConfig unchanged
example-mongodb-1 mongodb-agent [2021-11-12T17:36:08.063+0000] [.info] [src/mongoctl/processctl.go:Update:3263] <example-mongodb-1> [17:36:08.063] <DB_WRITE> Updated with query map[] and update [{$set [{agentFeatures [StateCache]} {nextVersion 2}]}] and upsert=true on local.clustermanager
example-mongodb-1 mongodb-agent [2021-11-12T17:36:08.114+0000] [.info] [src/director/director.go:computePlan:280] <example-mongodb-1> [17:36:08.114] ... process has a plan : WaitRsInit,WaitFeatureCompatibilityVersionCorrect
example-mongodb-1 mongodb-agent [2021-11-12T17:36:08.114+0000] [.info] [src/director/director.go:tracef:794] <example-mongodb-1> [17:36:08.114] Running step: 'WaitRsInit' of move 'WaitRsInit'
example-mongodb-1 mongodb-agent [2021-11-12T17:36:08.114+0000] [.info] [src/director/director.go:tracef:794] <example-mongodb-1> [17:36:08.114] because
example-mongodb-1 mongodb-agent [All the following are true:
example-mongodb-1 mongodb-agent     ['currentState.Up' = true]
example-mongodb-1 mongodb-agent     ['currentState.CanRsInit' = false]
example-mongodb-1 mongodb-agent     ['desiredState.ReplSetConf' != <nil> ('desiredState.ReplSetConf' = ReplSetConfig{id=example-mongodb,version=0,commitmentStatus=false,configsvr=false,protocolVersion=1,forceProtocolVersion=false,writeConcernMajorityJournalDefault=,members={id:0,HostPort:example-mongodb-0.example-mongodb-svc.default.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},{id:1,HostPort:example-mongodb-1.example-mongodb-svc.default.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},settings=map[]})]
example-mongodb-1 mongodb-agent     ['currentState.ReplSetConf' = <nil>]
example-mongodb-1 mongodb-agent ]
example-mongodb-1 mongodb-agent [2021-11-12T17:36:08.115+0000] [.info] [src/director/director.go:planAndExecute:564] <example-mongodb-1> [17:36:08.115] Step=WaitRsInit as part of Move=WaitRsInit in plan failed : <example-mongodb-1> [17:36:08.115] Postcondition not yet met for step WaitRsInit because
example-mongodb-1 mongodb-agent ['currentState.ReplSetConf' = <nil>].
example-mongodb-1 mongodb-agent  Recomputing a plan...
example-mongodb-1 mongodb-agent [2021-11-12T17:36:08.262+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [17:36:08.262] clusterConfig unchanged
```

**Operator Information**
 - Operator Version
 - MongoDB Image used

**Kubernetes Cluster Information**
EKS 1.20

**Additional context**
If members is set to 1, it works perfectly. There is something wrong with adding replicas to existing replica set.

Based on https://github.com/mongodb/helm-charts/blob/7c7641eb3b5ca6c716e44afae9bf99351f7b644d/charts/community-operator/templates/mongodbcommunity_cr_with_tls.yaml

**Comment by chatton** [comment]
Hi @michalschott would you be able to provide the `kubectl describe` output for the StatefulSet? There may be some information there about why the last member is not coming up.

I notice you've explicitly removed the resource limits here

```yaml
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits: {}
                requests: {}
            - name: mongodb-agent
              resources:
                limits: {}
                requests: {}
```

This could potentially cause an issue with the resource limits in the cluster. Have you tried specifying values for this and deploying the resource again?
