### ISSUE TITLE
simple example operator deployment . not authorized to execute command

### ISSUE THREAD

**Issue by ElyRonen** [mongodb/mongodb-kubernetes-operator#784]
**What did you do to encounter the bug?**

1. following this guide: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md
    downloading the controller on the same namespace.

- `k apply -f mongodbcommunity.mongodb.com_mongodbcommunity.yaml`

- `kubectl apply -k config/rbac`

- `kubectl create -f config/manager/manager.yaml`

checking if the operator pod is running properly:
operator pod running successfully!

2. following this guide: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md

the only change made is:
changed password as required, and added a StatefulSet section within the Yaml. the Yaml looks as follows:

```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
      spec:
        volumeClaimTemplates:
          - metadata:
              name: logs-volume
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 4Gi
# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: bestpassword

-----
```

- `kubectl apply -f config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml`

checking if the secret was created properly:
my-user-password secret was created successfully!
also, 3 example-mongo-db pods are running successfully!

- `kubectl get secret example-mongodb-admin-my-user -o json | jq -r '.data | with_entries(.value |= @base64d)'`

password received is the password configured - bestpassword - output received:
```

{
  "connectionString.standard": "mongodb://my-user:bestpassword@example-mongodb-0.example-mongodb-svc.elastic-system.svc.cluster.local:27017,example-mongodb-1.example-mongodb-svc.elastic-system.svc.cluster.local:27017,example-mongodb-2.example-mongodb-svc.elastic-system.svc.cluster.local:27017/admin?ssl=false",
  "connectionString.standardSrv": "mongodb+srv://my-user:bestpassword@example-mongodb-svc.elastic-system.svc.cluster.local/admin?ssl=false",
  "password": "bestpassword",
  "username": "my-user"
}

```

trying to connect to mongo:

-  `k run mongoshell -it --rm --restart=Never --image=mongo -- bash`

inside the comment prompt - using the connection string:

- `mongosh "mongodb+srv://my-user:bestpassword@example-mongodb-svc.elastic-system.svc.cluster.local/admin?ssl=false"`

connected to mongo. inside mongo, trying to insert new data:

- `use mydb`

- `db.movie.insert({"name":"tutorials point"})`

getting the following error:

`not authorized on mydb to execute command { insert: "movie", documents: [ { name: "tutorials point", _id: ObjectId('619648cc6703949422c9e1a4') } ], ordered: true, lsid: { id: UUID("92bf761b-3033-408f-8425-4851e8724301") }, txnNumber: 1, $clusterTime: { clusterTime: Timestamp(1637238952, 11), signature: { hash: BinData(0, F0B8605E74181764FB6952E91E1352AA44A880A4), keyId: 7031885499719483395 } }, $db: "mydb" }
`

seems like although I'm supposed to be an admin user - I'm not authorized to do anything in the DB, I can access admin DB but nothing more than that.

**What did you expect?**
I was expecting to have the option to write data into DB's to have full admin access and create new DB's.

**What happened instead?**
seems that I'm not authorized to perform any action inside mongo following the community guide

**Operator Information**
```
Container ID:  docker://78bb81d8e781ec3fd4cf76e79e3a96c4f247ed5a1a2a4a877b61222adef7a3de
    Image:         quay.io/mongodb/mongodb-kubernetes-operator:0.7.1
    Image ID:      docker-pullable://quay.io/mongodb/mongodb-kubernetes-operator@sha256:0d485fcacd4d47895e7d805d157d5bc64cab3ce614eec6b6becb051c9df0a3e0

```
**Kubernetes Cluster Information**
 cluster EKS on us-east-2 

 - Version:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```
