### ISSUE TITLE
Having issues when trying to set limits to the mongod container

### ISSUE THREAD

**Issue by mrik974** [mongodb/mongodb-kubernetes-operator#804]
Hi all :) 
I tried to install a mongodb ReplicaSet with CPU and RAM limitations using the operator?
Here's my file : 
``` ---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  namespace: mongodb
  name: mongodb-2
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "0,5"
                  memory: "512M"
  users:
    - name: test
      db: admin
      passwordSecretRef: 
        name: mongodb-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
```

**What did you expect?**
The cluster up and running with effective limitations applied to the mongod container

**What happened instead?**
The operator pod logs this message : 
```
W1207 19:00:34.378852      10 reflector.go:441] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: watch of *v1.MongoDBCommunity ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: v1.MongoDBCommunity.Spec: v1.MongoDBCommunitySpec.Users: []v1.MongoDBUser: Type: StatefulSetConfiguration: v1.StatefulSetConfiguration.SpecWrapper: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|2M\"}}}]}}}},\"type\":\"|..., bigger context ...|ces\":{\"limits\":{\"cpu\":\"0,5\",\"memory\":\"512M\"}}}]}}}},\"type\":\"ReplicaSet\",\"users\":[{\"db\":\"admin\",\"name|...") has prevented the request from succeeding
```

**Operator Information**
 - Operator version : `quay.io/mongodb/mongodb-kubernetes-operator:0.7.2`
 - MongoDB version : The default version

**Kubernetes Cluster Information**
 - OVH cluster
 - 1.22.2
 - Quay

I may be doing something wrong but I don't know what.

**Comment by mrik974** [comment]
Fixed it, leaving it in case someone falls into the same issue. 
I just inverted the `users` and the `statefulSet` specs...

Here's my template now : 
```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  namespace: mongodb
  name: mongodb-2
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: hospitalidee
      db: admin
      passwordSecretRef: 
        name: mongodb-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: 500m
                  memory: 512M
```
