### ISSUE TITLE
'currentState.Fickle.AllRsMembersUp() ' = false

### ISSUE THREAD

**Issue by seimic** [mongodb/mongodb-kubernetes-operator#821]
**What did you do to encounter the bug?**

Simple deployment of crds, operator and MongoDBCommunity.

1. Operator helm chart values

```yml
agent:
  name: mongodb-agent
  version: 11.0.5.6963-1
community-operator-crds:
  enabled: false
createResource: false
database:
  name: mongodb-database
mongodb:
  name: mongo
  repo: docker.io
namespace: foris-nosql
operator:
  deploymentName: mongodb-kubernetes-operator
  name: mongodb-kubernetes-operator
  operatorImageName: mongodb-kubernetes-operator
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 256m
      memory: 256Mi
  version: 0.7.2
readinessProbe:
  name: mongodb-kubernetes-readinessprobe
  version: 1.0.6
registry:
  agent: quay.io/mongodb
  operator: quay.io/mongodb
  pullPolicy: Always
  readinessProbe: quay.io/mongodb
  versionUpgradeHook: quay.io/mongodb
resource:
  members: 3
  name: mongodb-replica-set
  tls:
    caCertificateSecretRef: tls-ca-key-pair
    certManager:
      certDuration: 8760h
      renewCertBefore: 720h
    certificateKeySecretRef: tls-certificate
    enabled: true
    useCertManager: false
  version: 4.4.0
versionUpgradeHook:
  name: mongodb-kubernetes-operator-version-upgrade-post-start-hook
  version: 1.0.3
```

2. MongoDB

```yml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  namespace: foris-nosql
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.6"
  security:
    authentication:
      modes: ["SCRAM-SHA-256", "SCRAM-SHA-1"]
      ignoreUnknownUsers: true
    tls:
      enabled: false # Disabled to make sure its not the reason
#      caCertificateSecretRef:
#        name: mongodb-ca-secret
#      certificateKeySecretRef:
#        name: mongodb-tls-secret
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-admin-secret
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      selector:
        matchLabels:
          app: mongodb
      template:
        metadata:
          labels:
            app: mongodb
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: app
                          operator: In
                          values:
                            - mongodb
                    topologyKey: kubernetes.io/hostname
          securityContext:
            fsGroup: 2000
            runAsUser: 2000
          containers:
          - name: mongodb-agent
            readinessProbe:
              failureThreshold: 30
              initialDelaySeconds: 10
            resources:
              limits:
                cpu: "0.5"
                memory: 512M
              requests:
                cpu: "0.2"
                memory: 256M
          - name: mongod
            resources:
              limits:
                cpu: "1"
                memory: 2Gi
              requests:
                cpu: "0.5"
                memory: 1Gi
          initContainers:
          - name: mongodb-agent-readinessprobe
            securityContext:
              runAsNonRoot: true
              runAsUser: 2000
          - name: mongod-posthook
            securityContext:
              runAsNonRoot: true
              runAsUser: 2000
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: 
            - ReadWriteOnce
            storageClassName: longhorn-default
            resources:
              requests:
                storage: 10Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes:
            - ReadWriteOnce
            storageClassName: longhorn-single
            resources:
              requests:
                storage: 2Gi
```

**What did you expect?**
Funtional mongo replicaset (statefulset)

**What happened instead?**
mongo-agent remains in endless loop waiting for replicaset to become available.

![image](https://user-images.githubusercontent.com/34323525/146347930-81c4dadb-895e-4b75-91de-46dd38067d90.png)
Volumes are fine too
![image](https://user-images.githubusercontent.com/34323525/146349452-28d7a746-1a54-4d8d-9368-d7546c8094db.png)

Log from first node
```log
Recomputing a plan...
[2021-12-16T09:40:02.139+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [09:40:02.139] clusterConfig unchanged
[2021-12-16T09:40:03.011+0000] [.info] [src/mongoclientservice/mongoclientservice.go:func1:1573] [09:40:03.011] Testing auth with username __system db=local to mongodb-0.mongodb-svc.foris-nosql.svc.cluster.local:27017 (local=false) connectMode=SingleConnect ipversion=0 tls=false
[2021-12-16T09:40:03.076+0000] [.info] [src/mongoctl/processctl.go:GetKeyHashes:1985] <mongodb-0> [09:40:03.076] Able to successfully auth to mongodb-0.mongodb-svc.foris-nosql.svc.cluster.local:27017 (local=false) using desired auth key
[2021-12-16T09:40:03.109+0000] [.info] [src/mongoctl/processctl.go:Update:3263] <mongodb-0> [09:40:03.109] <DB_WRITE> Updated with query map[] and update [{$set [{agentFeatures [StateCache]} {nextVersion 1}]}] and upsert=true on local.clustermanager
[2021-12-16T09:40:03.147+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [09:40:03.147] clusterConfig unchanged
[2021-12-16T09:40:03.189+0000] [.info] [src/director/director.go:computePlan:280] <mongodb-0> [09:40:03.189] ... process has a plan : WaitAllRsMembersUp,RsInit,WaitFeatureCompatibilityVersionCorrect
[2021-12-16T09:40:03.189+0000] [.info] [src/director/director.go:tracef:794] <mongodb-0> [09:40:03.189] Running step: 'WaitAllRsMembersUp' of move 'WaitAllRsMembersUp'
[2021-12-16T09:40:03.189+0000] [.info] [src/director/director.go:tracef:794] <mongodb-0> [09:40:03.189] because
[All the following are true:
['currentState.Up' = true]
['desiredState.ReplSetConf' != <nil> ('desiredState.ReplSetConf' = ReplSetConfig{id=mongodb,version=0,commitmentStatus=false,configsvr=false,protocolVersion=1,forceProtocolVersion=false,writeConcernMajorityJournalDefault=,members={id:0,HostPort:mongodb-0.mongodb-svc.foris-nosql.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},{id:1,HostPort:mongodb-1.mongodb-svc.foris-nosql.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},{id:2,HostPort:mongodb-2.mongodb-svc.foris-nosql.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},settings=map[]})]
]
[2021-12-16T09:40:03.189+0000] [.info] [src/director/director.go:planAndExecute:564] <mongodb-0> [09:40:03.189] Step=WaitAllRsMembersUp as part of Move=WaitAllRsMembersUp in plan failed : <mongodb-0> [09:40:03.189] Postcondition not yet met for step WaitAllRsMembersUp because
['currentState.Fickle.AllRsMembersUp() ' = false].
Recomputing a plan...
... Here it repeats in endles loop
```

Second and third nodes in WaitRSInit state. ['currentState.ReplSetConf' = <nil>]

```log
Recomputing a plan...
--
Thu, Dec 16 2021 10:36:05 am | [2021-12-16T09:36:05.572+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [09:36:05.572] clusterConfig unchanged
Thu, Dec 16 2021 10:36:06 am | [2021-12-16T09:36:06.102+0000] [.info] [src/mongoclientservice/mongoclientservice.go:func1:1573] [09:36:06.102] Testing auth with username __system db=local to mongodb-1.mongodb-svc.foris-nosql.svc.cluster.local:27017 (local=false) connectMode=SingleConnect ipversion=0 tls=false
Thu, Dec 16 2021 10:36:06 am | [2021-12-16T09:36:06.128+0000] [.info] [src/mongoctl/processctl.go:GetKeyHashes:1985] <mongodb-1> [09:36:06.128] Able to successfully auth to mongodb-1.mongodb-svc.foris-nosql.svc.cluster.local:27017 (local=false) using desired auth key
Thu, Dec 16 2021 10:36:06 am | [2021-12-16T09:36:06.156+0000] [.info] [src/mongoctl/processctl.go:Update:3263] <mongodb-1> [09:36:06.156] <DB_WRITE> Updated with query map[] and update [{$set [{agentFeatures [StateCache]} {nextVersion 1}]}] and upsert=true on local.clustermanager
Thu, Dec 16 2021 10:36:06 am | [2021-12-16T09:36:06.234+0000] [.info] [src/director/director.go:computePlan:280] <mongodb-1> [09:36:06.234] ... process has a plan : WaitRsInit,WaitFeatureCompatibilityVersionCorrect
Thu, Dec 16 2021 10:36:06 am | [2021-12-16T09:36:06.234+0000] [.info] [src/director/director.go:tracef:794] <mongodb-1> [09:36:06.234] Running step: 'WaitRsInit' of move 'WaitRsInit'
Thu, Dec 16 2021 10:36:06 am | [2021-12-16T09:36:06.234+0000] [.info] [src/director/director.go:tracef:794] <mongodb-1> [09:36:06.234] because
Thu, Dec 16 2021 10:36:06 am | [All the following are true:
Thu, Dec 16 2021 10:36:06 am | ['currentState.Up' = true]
Thu, Dec 16 2021 10:36:06 am | ['currentState.CanRsInit' = false]
Thu, Dec 16 2021 10:36:06 am | ['desiredState.ReplSetConf' != <nil> ('desiredState.ReplSetConf' = ReplSetConfig{id=mongodb,version=0,commitmentStatus=false,configsvr=false,protocolVersion=1,forceProtocolVersion=false,writeConcernMajorityJournalDefault=,members={id:0,HostPort:mongodb-0.mongodb-svc.foris-nosql.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},{id:1,HostPort:mongodb-1.mongodb-svc.foris-nosql.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},{id:2,HostPort:mongodb-2.mongodb-svc.foris-nosql.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},settings=map[]})]
Thu, Dec 16 2021 10:36:06 am | ['currentState.ReplSetConf' = <nil>]
Thu, Dec 16 2021 10:36:06 am | ]
Thu, Dec 16 2021 10:36:06 am | [2021-12-16T09:36:06.235+0000] [.info] [src/director/director.go:planAndExecute:564] <mongodb-1> [09:36:06.235] Step=WaitRsInit as part of Move=WaitRsInit in plan failed : <mongodb-1> [09:36:06.235] Postcondition not yet met for step WaitRsInit because
Thu, Dec 16 2021 10:36:06 am | ['currentState.ReplSetConf' = <nil>].
Thu, Dec 16 2021 10:36:06 am | Recomputing a plan...
```

**Operator Information**
community-operator-crds:0.7.2
community-operator:0.7.2
mongo:4.4.6 

**Kubernetes Cluster Information**
 - Rancher RKE2 v1.21.7+rke2r1
 - Image Registry location: quay for operator, docker for mongodb

**Comment by rodrigovalin** [comment]
Hello @seimic; thanks for reporting this issue.

The problem is with your `MongoDB` resource. You need to change the `selector.matchLabels` and `template.metadata.labels` in `spec.statefulSet.spec` from:

```
  statefulSet:
    spec:
      selector:
        matchLabels:
          app: mongodb
      template:
        metadata:
          labels:
            app: mongodb
```

To

```
  statefulSet:
    spec:
      selector:
        matchLabels:
          app: mongodb-svc
      template:
        metadata:
          labels:
            app: mongodb-svc
```

This will get this resource to a Running state.

Closing this for now; please reopen if you have any other questions.
