### ISSUE TITLE
Dynamic Provisioning of Persistent Volume Claim not working with Ceph-CSI (claim Selector is not supported)

### ISSUE THREAD

**Issue by hoba84** [mongodb/mongodb-kubernetes-operator#829]
**What did you do to encounter the bug?**
Following the tutorial [Run Secure Containerized MongoDB Deployments Using the MongoDB Community Kubernetes operator](https://www.mongodb.com/blog/post/run-secure-containerized-mongodb-deployments-using-the-mongo-db-community-kubernetes-oper), it seems that dynamic provisioning is not working with custom storage classes.

1. Following the tutorial linked above, create: CRD, namespace (mongodb), operator, rbac, secret.
2. Having ceph-csi configured and tested (with one pod having a PVC attached, being able to read/write files to the mounted filesystem inside the container).
3. One and only storage class in the cluster is:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-rbd-sc
provisioner: rbd.csi.ceph.com
parameters:
   clusterID: ** stripped **
   pool: my-prd-k8s-hdd
   imageFeatures: layering
   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
   csi.storage.k8s.io/provisioner-secret-namespace: prd-my-storage
   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
   csi.storage.k8s.io/node-stage-secret-namespace: prd-my-storage
reclaimPolicy: Delete
mountOptions:
   - discard
```

4. Apply the following replica set:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replica-set
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.0"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-mongodb-user
      db: admin
      passwordSecretRef: 
        name: my-mongodb-user-password # the name of the secret we created
      roles: # the roles that we want to the user to have
        - name: readWrite
          db: myDb
      scramCredentialsSecretName: mongodb-replica-set
  statefulSet:
    spec:
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes: [" ReadWriteOnce "]
          storageClassName: csi-rbd-sc
          resources:
            requests:
              storage: 1Gi
          selector:
            matchLabels:
              type: data
      - metadata:
          name: logs-volume
        spec:
          accessModes: [" ReadWriteOnce "]
          storageClassName: csi-rbd-sc
          resources:
            requests:
              storage: 1Gi
          selector:
            matchLabels:
              type: logs
```

**What did you expect?**
Replica set gets created and pods ener running state with PVC mounted.

**What happened instead?**
Pod **mongodb-replica-set-0** gets stuck with status:
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  35s   default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
```

Two PVC are created (data, logs) but are stuck in status pending:
```
❯ kubectl get pvc -n mongodb
NAME                                STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-volume-mongodb-replica-set-0   Pending                                      csi-rbd-sc     2m40s
logs-volume-mongodb-replica-set-0   Pending                                      csi-rbd-sc     2m39s
```

Status of PVC is:
```
❯ kubectl describe pvc -n mongodb data-volume-mongodb-replica-set-0
Name:          data-volume-mongodb-replica-set-0
Namespace:     mongodb
StorageClass:  csi-rbd-sc
Status:        Pending
Volume:
Labels:        app=mongodb-replica-set-svc
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
               volume.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       mongodb-replica-set-0
Events:
  Type     Reason                Age                   From                                                                                              Message
  ----     ------                ----                  ----                                                                                              -------
  Normal   Provisioning          72s (x10 over 5m26s)  rbd.csi.ceph.com_csi-rbdplugin-provisioner-6946bb54bb-bnb7s_879b3695-07bb-4b8d-b5b3-dc034bab5447  External provisioner is provisioning volume for claim "mongodb/data-volume-mongodb-replica-set-0"
  Warning  ProvisioningFailed    72s (x10 over 5m26s)  rbd.csi.ceph.com_csi-rbdplugin-provisioner-6946bb54bb-bnb7s_879b3695-07bb-4b8d-b5b3-dc034bab5447  failed to provision volume with StorageClass "csi-rbd-sc": claim Selector is not supported
  Normal   ExternalProvisioning  7s (x24 over 5m26s)   persistentvolume-controller                                                                       waiting for a volume to be created, either by external provisioner "rbd.csi.ceph.com" or manually created by system administrator
```

Not clear what to do with message: **claim Selector is not supported**

**Operator Information**
 - quay.io/mongodb/mongodb-kubernetes-operator:**0.7.2**
 - quay.io/mongodb/mongodb-agent:**11.0.5.6963-1**

**Kubernetes Cluster Information**
- microk8s (v1.23.0)
- ceph pacific with ceph-csi
