### ISSUE TITLE
Incompatible with Restricted PodSecurityPolicy Because InitContainers Run as Root

### ISSUE THREAD

**Issue by haslersn** [mongodb/mongodb-kubernetes-operator#833]
In K8s clusters using the Restricted policy of [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/), the MongoDB Pods cannot be created for two reasons:

1. The PodSpec is missing the following:

   ```yaml
   securityContext:
     seccompProfile:
       type: RuntimeDefault
   ```

2. The InitContainers (`mongod-posthook` & `mongodb-agent-readinessprobe`) run as root.

**What did you expect?**

MongoDB operator should be compatible with clusters enforcing the Restricted policy, i.e., the default seccomp profile should be used for all Pods and all (init) containers should run as non-root.

**Workaround**

I don't know any full workaround. There's the following workaround for 1., but 2. still needs to be fixed to support environments with the Restricted policy.

```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
spec:
  statefulSet:
    spec:
      template:
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
```

**Operator Information**

- Operator Version: 2329b89f612ed8d43c7ab16e3e334e823cab44bb
- MongoDB Image used: `registry.hub.docker.com/library/mongo:4.2.6`, `quay.io/mongodb/mongodb-agent:10.29.0.6830-1`, `quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2`, `quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.1`

**Kubernetes Cluster Information**

kubeadm K8s 1.19 on bare metal Debian 10
