### ISSUE TITLE
class storage of AWS 

### ISSUE THREAD

**Issue by FridMehdi** [mongodb/mongodb-kubernetes-operator#843]
how to use class storge of AWS for example ? 

```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: wizz-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
volumeClaimTemplates:
- metadata:
    name: datavolume
  spec:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "efs-sc"
    resources:
      requests:
        storage: 1Gi

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
```
I get the folowing issue by appliying the folowing commande 
```
kubectl apply -f mongodb-kubernetes-operator/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml
```

```
error: error validating "mongodb-kubernetes-operator/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml": error validating data: ValidationError(MongoDBCommunity): unknown field "volumeClaimTemplates" in com.mongodb.mongodbcommunity.v1.MongoDBCommunity; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by antonputra** [comment]
You can override any attribute of the statefulset, including volumeClaimTemplate. It should be something like this
```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: wizz-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      volumeClaimTemplates:
      - apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          storageClassName: "efs-sc"
          resources:
            requests:
              storage: 40G
          volumeMode: Filesystem
```
