### ISSUE TITLE
ReplicaSets restarts after about 24 to 48 hours

### ISSUE THREAD

**Issue by JensHor** [mongodb/mongodb-kubernetes-operator#849]
**What did you do to encounter the bug?**
Not really a bug, but a question. I am using Mongodb Kubernetes Operator hosted on GKE with the following yaml configuration:

``` yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replica-set
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.7"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin 
      db: admin
      passwordSecretRef:
        name: mongodb-admin-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram

  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: 10m
                  memory: 100M
                requests:
                  cpu: 10m
                  memory: 100M
            - name: mongodb-agent
              resources:
                limits:
                  cpu: 10m
                  memory: 100M
                requests:
                  cpu: 10m
                  memory: 100M
```

I have the problem that all 1 to 2 days one of the replica set pods is restarted causing my application to have no longer access to the database. I already opened an issue on the repo of the mongodb library i am using to figure out how to detect changes in the connection and reconnect. 

My connection String looks like this:

```dart
Db(
  'mongodb://$_userName:$_password@'
  '$_replicaSet-0.$_service.$_namespace.svc.cluster.local:$_port,'
  '$_replicaSet-1.$_service.$_namespace.svc.cluster.local:$_port,'
  '$_replicaSet-2.$_service.$_namespace.svc.cluster.local:$_port/'
  '$_database?'
  'authSource=admin&authMechanism=SCRAM-SHA-256&'
  'readPreference=primary&'
  'ssl=false',
)
```

**What did you expect?**
I am expecting that the replica sets are not restarting.

**Operator Information**
 - Operator Version: `release.json` file contains a version of `0.7.2`
 - MongoDB Image used: 4.2.7

**Kubernetes Cluster Information**
 - Distribution: 1.21.5-gke.1302
 - Version: 1.21.5-gke.1302
 - Image Registry location (quay, or an internal registry)

**Additional context**

I'll provide database logs once the error occurs again. But maybe this is a known problem or a misconfiguration from by me.
