### ISSUE TITLE
replicaSetHorizons with multiple horizons seems not to work

### ISSUE THREAD

**Issue by seimic** [mongodb/mongodb-kubernetes-operator#851]
**What did you do to encounter the bug?**

Defined two horizons for a 3 instances replicaset. External and Internal.

```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  namespace: mongodb-ns
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.5"
  replicaSetHorizons:
  - external: "mongodb-0.my-domain.com:27017"
  - external: "mongodb-1.my-domain.com:27018"
  - external: "mongodb-2.my-domain.com:27019"
  - internal: "mongodb-shared.mongodb-ns.svc.cluster.local:27017"
  - internal: "mongodb-shared.mongodb-ns.svc.cluster.local:27018"
  - internal: "mongodb-shared.mongodb-ns.svc.cluster.local:27019"
...
```

The field is named in plural, so I assume it should be possible to define more than one set of horizon definitions.
The only requirement was, they match the amount of replicaset instances. Not sure, what I'm missing here.

**What did you expect?**

I would expect both horizons to appear in the configuration (internal and external)

**What happened instead?**

The configuration generated by the operator contains only the first horizon defined (external). Changing the order of the horizons results in one horizon too, this time the internal one. I was expecting both to appear in configuration. SNI seems to work for the external one.

```yaml
"replicaSets": [
  {
    "_id": "mongodb",
    "members": [
      {
        "_id": 0,
        "host": "mongodb-0",
        "priority": 1,
        "arbiterOnly": false,
        "votes": 1,
        "horizons": {
          "external": "mongodb-0.my-domain.com:27017"
        }
      },
      {
        "_id": 1,
        "host": "mongodb-1",
        "priority": 1,
        "arbiterOnly": false,
        "votes": 1,
        "horizons": {
          "external": "mongodb-1.my-domain.com:27018"
        }
      },
      ...
    ]
    ...
  }
]
```

**Operator Information**
 - Operator Version: 0.7.2
 - Mongodb Version: 5.0.5

**Kubernetes Cluster Information**
 - Rancher RKE2: v1.21.8+rke2r1
 - Image Registry location: quay

**Additional context**

All this is an attempt to make the replicaset accessible from another cluster within same local network.
There are no errors in operator log.

**Comment by priyolahiri** [comment]
Please look at the [sample](https://github.com/mongodb/mongodb-kubernetes-operator/tree/master/config/samples/external_access) and the [docs](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/external_access.md) for help on configuring external access. The way you are configuring it now is unsupported.

**Comment by seimic** [comment]
Hi,

thanks for your response. The way I do it is almost exactly same as in the example and documentation, except in example there is only one horizon. It works with a single external address, but not with two horizons. The question was, how to expose the service twice. I would like to expose it to local clusters using cilium global services. For this purpose there is the second service "mongodb-shared.mongodb-ns.svc.cluster.local".

Kind regards,
Michael

**Comment by priyolahiri** [comment]
Currently, only one entry can be specified per replicaset member.

**Comment by seimic** [comment]
OK, this means the statement "You may add multiple external mappings per host." in this documentation is not valid.
https://docs.mongodb.com/kubernetes-operator/master/tutorial/connect-from-outside-k8s/ (See: spec.connectivity
.replicaSetHorizons)
Hmm... OK. We try to live with one :)

**Comment by priyolahiri** [comment]
The docs you are referring to are for the Enterprise Operator and this is the Community Operator. Having said that, good point on the multiple external mappings per host. Let me try and see if I can find anything on specifying multiple split horizon entries for each replicaset member.

**Comment by mircea-cosbuc** [comment]
Hi @seimic , to configure multiple horizons for your replica set, you would need to specify multiple entries in `replicaSetHorizons` for every member of your replica set (rewriting your example):
```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  namespace: mongodb-ns
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.5"
  replicaSetHorizons:
  - external: "mongodb-0.my-domain.com:27017"
    internal: "mongodb-shared.mongodb-ns.svc.cluster.local:27017"
  - external: "mongodb-1.my-domain.com:27018"
    internal: "mongodb-shared.mongodb-ns.svc.cluster.local:27018"
  - external: "mongodb-2.my-domain.com:27019"
    internal: "mongodb-shared.mongodb-ns.svc.cluster.local:27019"
...
```
I hope this clarifies the requirement that the number of entries in `replicaSetHorizons` must match the number of members in your replica set.
