### ISSUE TITLE
Mongod fails to  start in First Replicaset

### ISSUE THREAD

**Issue by jdowling-last** [mongodb/mongodb-kubernetes-operator#863]
**What did you do to encounter the bug?**
1. Installed the operator with default setting into  the mongodb namespace:

```
git clone https://github.com/mongodb/mongodb-kubernetes-operator.git
cd mongodb-kubernetes-operator
kubectl create namespace mongodb
kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
kubectl apply -k config/rbac/ --namespace mongodb
kubectl apply -f config/manager/manager.yaml --namespace mongodb
```
2. For the replicas, the sample used was mongodb.com_v1_mongodbcommunity_cr.yaml.  I changed the name from example-mongodb to polis-mongodb and set the password.

3. My persistent storage plugin is csi-driver-nfs. The PVCs were created manually and bound during the replica creation. First pvc set follows:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume-polis-mongodb-0-pv
  namespace: mongodb
  labels:
    volume: data-volume-polis-mongodb-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-nfs-storage
  nfs:
    # NFS server's definition
    path: /myPath/data-volume-polis-mongodb-0
    server: my.server.com
    readOnly: false

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # any PVC name
  name: data-volume-polis-mongodb-0
  namespace: mongodb
spec:
  selector:
    matchLabels:
      volume: data-volume-polis-mongodb-0
  accessModes:
  # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
  - ReadWriteOnce
  resources:
     requests:
       # storage size to use
       storage: 5Gi

kind: PersistentVolume
metadata:
  name: logs-volume-polis-mongodb-0-pv
  namespace: mongodb
  labels:
    volume: logs-volume-polis-mongodb-0
spec:
  capacity:
    storage: 2Gi
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-nfs-storage
  nfs:
    # NFS server's definition
    path: /myPath/logs-volume-polis-mongodb-0
    server: my.server.com
    readOnly: false

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # any PVC name
  name: logs-volume-polis-mongodb-0
  namespace: mongodb
spec:
  selector:
    matchLabels:
      volume: logs-volume-polis-mongodb-0
  accessModes:
  # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
  - ReadWriteOnce
  resources:
     requests:
       # storage size to use
       storage: 2Gi
```
4. I create the replica set and the first replica hangs:

`kubectl apply -f mongodb-kubernetes-operator/config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml -n mongodb`

```
kubectl get all -n mongodb
NAME                                               READY   STATUS    RESTARTS   AGE
pod/mongodb-kubernetes-operator-5cb466865f-mhdbz   1/1     Running   0          30h
pod/polis-mongodb-0                                1/2     Running   0          26s

NAME                        TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
service/polis-mongodb-svc   ClusterIP   None         <none>        27017/TCP   26s

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mongodb-kubernetes-operator   1/1     1            1           5d6h

NAME                                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/mongodb-kubernetes-operator-5cb466865f   1         1         1       5d6h

NAME                             READY   AGE
statefulset.apps/polis-mongodb   0/3     26s
```
The pvcs bind, but pod events report that the readiness probe failed after mongodb-agent started:
```
...
 Normal   Created    3m                    kubelet            Created container mongodb-agent
  Normal   Started    2m59s                 kubelet            Started container mongodb-agent
  Warning  Unhealthy  98s (x10 over 2m51s)  kubelet            Readiness probe failed:
```
Digging through the container logs, I see that mongod is not ready, but I don't see anything in the logs to explain why.

**What did you expect?**
A replicaset with three members running

**What happened instead?**
Mongod fails to  start in first member

**Screenshots**

**Operator Information**
 - Operator Version: MongoDB Kubernetes Operator 0.7.2
 - MongoDB Image used: docker.io/mongo:4.2.6

**Kubernetes Cluster Information**
 - Distribution: Kubespray on Ubuntu
 - Version: v1.23.1
 - Image Registry location: quay
