### ISSUE TITLE
Recommended settings for faster startup...

### ISSUE THREAD

**Issue by seimic** [mongodb/mongodb-kubernetes-operator#869]
Hi,

not reporting a bug but I would like to ask for recommended configuration to make the deployment more "resilient".
We experience the problem the replicaset needs more than one minute (at good days) to initialize each instance. 
This causes connection errors and the database(s) are not reachable for some time. 

Example: Upgrade of CNI in cluster forces pods to restart. Whole cluster is already upgraded and mongodb is the only
deployment still busy with itself in init state. Databases like cockroachdb, mariadb etc. need only few seconds to reattach
pvcs and (re)start instances. What's wrong here?

Do you see anything wrong in the following setup?
Any hint to make it initialize faster and become more bullet proof for cluster upgrades would be appreciated. :)
Its always an adventure to upgrade anything because of mongodb.

Versions: 

- Community Operator: 0.7.2
- MongoDB: 5.0.5

```yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  namespace: mongodb
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.5"
  replicaSetHorizons:
  ...
  security:
  ...
  users:
  ...
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      selector:
        matchLabels:
          app: mongodb-svc
      template:
        metadata:
          labels:
            app: mongodb-svc
        spec:
          affinity:
          ...
          securityContext:
            runAsNonRoot: true
            runAsUser: 2000
          containers:
          - name: mongodb-agent
            readinessProbe:
              failureThreshold: 30
              initialDelaySeconds: 10
              timeoutSeconds: 3
            resources:
            ...
          - name: mongod
            resources:
              ...
          initContainers:
          - name: mongodb-agent-readinessprobe
            securityContext:
              runAsNonRoot: true
              runAsUser: 2000
          - name: mongod-posthook
            securityContext:
              runAsNonRoot: true
              runAsUser: 2000
      volumeClaimTemplates:
      ...
```

Kind regards,
Michael

**Comment by mircea-cosbuc** [comment]
Hi Michael,

There's nothing jumping out to me in your setup. You could increase the resource requests which could improve the start-up time, but not dramatically. The automation agent is directing the start-up, having each pod restarted, reach a goal state and synchronise with the rest of the cluster. We're not optimising the start-up speed since it's not a common operation and is also out of the bounds of the operator's capabilities.

**Comment by seimic** [comment]
Hi Mircea,

thanks for your answer. The resource settings are as follows (3 instances in replicaset):
```yaml
  containers:
  - name: mongodb-agent
    readinessProbe:
      failureThreshold: 30
      initialDelaySeconds: 10
      timeoutSeconds: 3
    resources:
      limits:
        cpu: "0.5"
        memory: 512M
      requests:
        cpu: "0.2"
        memory: 256M
  - name: mongod
    resources:
      limits:
        cpu: "2"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 4Gi
```
I try to use higher values for the agent. 0.5 CPU is maybe not enough. It's hard to figure out what it really needs.
All deployments like cilium, longhorn, cockroachdb and many others are available within few seconds after a node upgrade/restart (Kubernetes upgrade or security upgrades at OS level). 
Everything waits for CNI to become available first... this are maybe 5-10 seconds. Longhorn upgrades than almost immediately after CNI is available. Cockroachdb starts over in about 5 seconds after attaching volumes from longhorn.
I was looking for a way to delay the upgrades because of this (https://github.com/rancher/system-upgrade-controller/discussions/177), but this results in manual steps (Upgrade of cluster nodes one by one watching mongodb to start :) ). 
I guess it's related to the readiness probes somehow. I will try few things in a test cluster to find out the reason.
We used mongodb in the past in a simple replicaset setup and never experienced similar problems.

Kind regards,
Michael
