### ISSUE TITLE
TLS certificate content update fails to rollout automation config update

### ISSUE THREAD

**Issue by maxgio92** [mongodb/mongodb-kubernetes-operator#874]
**What did you do to encounter the bug?**
Steps to reproduce the chicken-and-egg behaviour:
- Update a certificate TLS (e.g. adding a new SAN); the `Secret` will be named the same, the content is changed.
- mongod fails to find the certificate file, as the `Secret` generated by the operator has a key named as the hashed cert PEM file and that hash is changed as content did. Insted, the configuration is not already updated with new x509 certificate file path.
- The configuration won't be updated until mongod (and the mongo-agent) is ready ([as for](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/controllers/replica_set_controller.go#L377))

**What did you expect?**
An update of the automation config, before the StatefulSet rollout happens (as like [this](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/controllers/replica_set_controller.go#L388)), otherwise I need to manually fix the configuration with right filepaths (`Secret`'s hashed certificate filename key).

**What happened instead?**
The automation configuration is not updated until the StatefulSet is ready, which won't until the automation configuration will be.

**Operator Information**
 - Operator version: 0.7.2
 - Operator image registry: Quay
 - MongoDB Image used: docker.io/mongo:5.0.4

**Kubernetes Cluster Information**
 - Distribution: none
 - Version:  v1.21.4

**Additional context**

**`MongoDBCommunity` manifest**
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: my-service-mongodb5
spec:
  members: 4
  replicaSetHorizons:
  <my_horizon_DNS_records>
  security:
    authentication:
      modes:
      - SCRAM
    tls:
      caConfigMapRef:
        name: my-service-mongodb5-ca
      certificateKeySecretRef:
        name: my-service-mongodb5-tls
      enabled: true
  statefulSet:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: my-service-mongodb5
          topologySpreadConstraints:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: my-service-mongodb5
            maxSkew: 1
            topologyKey: failure-domain.beta.kubernetes.io/zone
            whenUnsatisfiable: DoNotSchedule
  type: ReplicaSet
  users:
    <my_users>
  version: 5.0.4
```

**`Certificate.cert-manager.io/v1alpha2` manifest, related to the TLS setup**
```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: my-service-mongodb5-certificate
spec:
  commonName: <my_CN>
  dnsNames:
  <my_SANs>
  issuerRef:
    kind: Issuer
    name: <my issuer>
  secretName: my-service-mongodb5-tls
```
