### ISSUE TITLE
connection string from secret does not work unmodified

### ISSUE THREAD

**Issue by stocksr** [mongodb/mongodb-kubernetes-operator#878]
**What did you do to encounter the bug?**
1, Install the operator and create a replica set
2. Install a instance of mongo express - pulling the connection string from the created secret 
```  
 - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            secretKeyRef:
              key: connectionString.standard
              name: cluster-mongodb-admin-manager
```
3. mongo express logs this error 
```
Could not connect to database using connectionString: mongodb://manager:password@cluster-mongodb-0.cluster-mongodb-svc.mongodb.svc.cluster.local:27017,cluster-mongodb-1.cluster-mongodb-svc.mongodb.svc.cluster.local:27017,cluster-mongodb-2.cluster-mongodb-svc.mongodb.svc.cluster.local:27017/admin?ssl=false"
UnhandledPromiseRejectionWarning: MongoError: seed list contains no mongos proxies, replicaset connections requires the parameter replicaSet to be supplied in the URL
```

**What did you expect?**
I expected the connection string to work out the box

**What happened instead?**
I needed to update the connectionString to append `&replicaSet=cluster-mongodb` to the end, at which point it started working.
 
**Operator Information**
 - Operator Version: :0.7.2
 - MongoDB Image used: 5.0.6
