### ISSUE TITLE
Credentials secret creation fails when user name contains underscore

### ISSUE THREAD

**Issue by maxgio92** [mongodb/mongodb-kubernetes-operator#879]
**What did you do to encounter the bug?**
I defined a user name with _underscore_ in it ("_").

**What did you expect?**
That the credentials `Secret` would have been created with dash ("-") instead of underscore ("_") characters. 

**What happened instead?**
I defined a user name with _underscore_ in it. The credentials `Secret` tried to be created will have `metadata.name` with characters not replaced and with a value which is not conform to the RFC 1123. 

**Logs**
```
controllers/replica_set_controller.go:236     Could not update connection string secrets: Secret "myservice-mongodb5-admin-prometheus_exporter" is invalid: metadata.name: Invalid value: "myservice-mongodb5-admin-prometheus_exporter": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') 
```

**Operator Information**
 - Operator version: 0.7.2
 - Operator image registry: Quay
 - MongoDB Image used: docker.io/mongo:5.0.4

**Kubernetes Cluster Information**
 - Distribution: none
 - Version:  v1.21.4

**Additional context**
MongoDB manifest snippet:

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: myservice-mongodb5
spec:
  [...]
  users:
    name: prometheus_exporter
    passwordSecretRef:
      name: myservice-mongodb5-prometheus-exporter-user-password
    roles:
    - db: admin
      name: clusterMonitor
    - db: local
      name: read
    scramCredentialsSecretName: myservice-mongodb5-prometheus-exporter-user-scram
  version: 5.0.4
```
