### ISSUE TITLE
Replica Set and Persistent Volume

### ISSUE THREAD

**Issue by Miccolomi** [mongodb/mongodb-kubernetes-operator#894]
Hello to all,
in my lab, on kubernetes cluster completely empty,  I tried to install the last version of Community Kubernetes Operator:

1) Install Community Kubernetes Operator --> OK

- kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
- kubectl apply -k config/rbac/ --namespace mongodb
- kubectl create -f config/manager/manager.yaml --namespace mongodb

everything works fine !.

2) Install MongoDBCommunity Resource

-  kubectl apply -f config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml --namespace mongodb

after this, the result is: Stateful Sets error :" 0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims. "

Persistent Volume Claims are created 
Persistent Volumes no...
Storage Classes empty..
Pod Status -->  obviously stays in Pending

What did I do wrong?
Thank you for your help

**Comment by Miccolomi** [comment]
I try to create StorageClass:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mic-local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

and 2 Persistent Volume

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-volume-1"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-volume-2"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
```

in "mongodb.com_v1_mongodbcommunity_cr.yaml" add PersistentVolumeClaim:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-example-mongodb-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-volume-example-mongodb-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
```

this work... but only if ReplicaSet have only 1  members.

If I try to scale at 3 the error is the same... 

" 0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims" 

Thanks
