### ISSUE TITLE
 Authentication failed v0.7.2 new Installation

### ISSUE THREAD

**Issue by rtudo** [mongodb/mongodb-kubernetes-operator#904]
**What did you do to encounter the bug?**
1. from tag v0.7.2, install operator and the following database resource

```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    name: mongodb
    app: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.9"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-admin-pass
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-admin-user
  statefulSet:
    spec:
      selector:
        matchLabels:
          app: mongodb
          name: mongodb
      template:
        metadata:
          labels:
            app: mongodb
            name: mongodb
        spec:
          # resources can be specified by applying an override
          # per container name.
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "1"
                  memory: 1000M
                requests:
                  cpu: "0.5"
                  memory: 500M
            - name: mongodb-agent
              resources:
                limits:
                  cpu: "0.3"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: name
                          operator: In
                          values:
                            - mongodb
                    topologyKey: kubernetes.io/hostname

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-pass
type: Opaque
stringData:
  password: pass

```

2. connect to the database 
`kubectl exec -it mongodb-0 -c mongod -- mongo -u admin --authenticationDatabase admin -p pass`
3. Face the Authentication Failed Error like below
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/9086206/155320732-bc973d0e-f5df-4abe-95b5-60afb7706341.png">
4. See errors flowing through the pod
<img width="1738" alt="image" src="https://user-images.githubusercontent.com/9086206/155320032-f1629cc1-6e58-466a-a7fa-2ea0ece34c9a.png">

**What did you expect?**
I expect to be logged in to the mongodb using the credentials for the user I have defined in the database resource
**What happened instead?**
I get `Authentication Failed` and see errors in the mongod container

**Screenshots**
MongodbCommunity Resource is in pending state
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/9086206/155320169-d288779c-8574-420b-a9d7-f5bbb6cf9652.png">

But replicaset is in ready state:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/9086206/155320499-b8b08b72-3be8-4fd1-ac9f-78feba64c363.png">

**Operator Information**
 - Operator Version - v0.7.2
 - MongoDB Image used - docker.io/mongo:4.2.9

**Kubernetes Cluster Information**
 - Distribution v1.19.15-eks-9c63c4
 - Versionv1.19.15
 - Image Registry location (quay, or an internal registry) quay

**Additional context**
Images in the database Pod:
quay.io/mongodb/mongodb-agent:11.0.5.6963-1
docker.io/mongo:4.2.9
quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.3
quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.6

Images in the operator Pod:
quay.io/mongodb/mongodb-kubernetes-operator:0.7.2
