### ISSUE TITLE
MongoDBCommunity deployment fails using major.minor MDB version

### ISSUE THREAD

**Issue by joellord** [mongodb/mongodb-kubernetes-operator#924]
**What did you do to encounter the bug?**
I followed the steps from the documentation to create a MongoDBCommunity to deploy a 4.4 cluster
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mern-k8s-db
  labels:
    app: mern-k8s
    component: db
spec:
  members: 2
  type: ReplicaSet
  version: "4.4"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mdb-community-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mdb-secret
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
```

**What did you expect?**
I expected the operator to use the image `mongo:4.4`

**What happened instead?**
The MongoDBCommunity resource indicated that it failed, but I had a pod successfully deployed.
```
❯ k get mongodbcommunity
NAME          PHASE    VERSION
mern-k8s-db   Failed   
❯ k get pods
NAME                                           READY   STATUS    RESTARTS   AGE
mern-k8s-db-0                                  1/2     Running   0          5m14s
```

Trying to debug:
```
❯ k describe mongodbcommunity mern-k8s-db
...
Error deploying MongoDB ReplicaSet: failed to ensure AutomationConfig: could not build automation config: could not create an automation config: can't build the automation config: can't compute semver version from previous FeatureCompatibilityVersion 

❯ k describe pod mern-k8s-db-0
  Warning  Unhealthy               2m5s (x32 over 6m45s)  kubelet                  Readiness probe failed: panic: open /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json: no such file or directory

goroutine 1 [running]:
main.main()
  /build/main.go:218 +0x15a
```

In hindsight, I guess I can understand the error message, but it wasn't clear to me and I need @rodrigovalin 's assistance to actually figure it out.

**Operator Information**
 - Operator Version: 0.7.3
 - MongoDB Image used: `4.4` (failed) `4.4.4` (worked)

**Kubernetes Cluster Information**
```
k version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:43:55Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
```
 - Image Registry location (quay, or an internal registry) Docker.io
