### ISSUE TITLE
Not every built-in roles present by default

### ISSUE THREAD

**Issue by paul-mesnilgrente** [mongodb/mongodb-kubernetes-operator#934]
**What did you do to encounter the bug?**
Install a basic instance of mongo using the operator (tested on mongo 4.4)

**What did you expect?**
I expect to have the default roles installed by default, listed there: https://www.mongodb.com/docs/v4.4/reference/built-in-roles/

**What happened instead?**
I have these roles only:

```json
{
        "role" : "dbAdmin",
        "db" : "test",
        "isBuiltin" : true,
        "roles" : [ ],
        "inheritedRoles" : [ ]
}
{
        "role" : "dbOwner",
        "db" : "test",
        "isBuiltin" : true,
        "roles" : [ ],
        "inheritedRoles" : [ ]
}
{
        "role" : "enableSharding",
        "db" : "test",
        "isBuiltin" : true,
        "roles" : [ ],
        "inheritedRoles" : [ ]
}
{
        "role" : "read",
        "db" : "test",
        "isBuiltin" : true,
        "roles" : [ ],
        "inheritedRoles" : [ ]
}
{
        "role" : "readWrite",
        "db" : "test",
        "isBuiltin" : true,
        "roles" : [ ],
        "inheritedRoles" : [ ]
}
{
        "role" : "userAdmin",
        "db" : "test",
        "isBuiltin" : true,
        "roles" : [ ],
        "inheritedRoles" : [ ]
}
```

**Operator Information**
 - Operator Version: 0.7.3
 - MongoDB Image used: 4.4.13

**Kubernetes Cluster Information**
 - Distribution: EKS
 - Version: v1.21.5

If possible, please include:

```yaml
# Secrets should be made for each user and then added to Mongo.
# Note that in the docs, `stringData` is used instead of `data`
# so you need to base64 encode the password value

# https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/users.md

---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-test
  namespace: staging
spec:
  members: 1
  type: ReplicaSet
  version: "4.4.13"
  featureCompatibilityVersion: "4.4"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: root
      passwordSecretRef:
        name: mongodb-root-password
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: 5t3p2kd8su2t49t
    - name: dnz-api
      passwordSecretRef:
        name: mongodb-dnz-api-password
      roles:
        - name: readWrite
          db: dnz_api_staging
        - name: readWrite
          db: dnz_api_uat
      scramCredentialsSecretName: pudh5tcc8b8w7sc
    - name: digitalnz
      passwordSecretRef:
        name: mongodb-digitalnz-password
      roles:
        - name: readWrite
          db: digitalnz_staging
        - name: readWrite
          db: digitalnz_uat
      scramCredentialsSecretName: jqqumf5r36xauxa
    - name: anyquestions
      passwordSecretRef:
        name: mongodb-anyquestions-password
      roles:
        - name: readWrite
          db: any_questions_staging
      scramCredentialsSecretName: w9sf8q8c5s5r4mr
    - name: national-library
      passwordSecretRef:
        name: mongodb-national-library-password
      roles:
        - name: readWrite
          db: national_library_staging
      scramCredentialsSecretName: t2jpbpjd3edv2jd
    - name: worker
      passwordSecretRef:
        name: mongodb-worker-password
      roles:
        - name: readWrite
          db: worker_staging
        - name: readWrite
          db: worker_uat
      scramCredentialsSecretName: qckp5ywpo8ciyh7
    - name: manager
      passwordSecretRef:
        name: mongodb-manager-password
      roles:
        - name: readWrite
          db: manager_uat
      scramCredentialsSecretName: 84wd2f6z66pf62q
    - name: mongo-backup
      passwordSecretRef:
        name: mongodb-backup-password
      roles:
        - name: backup
          db: admin
      scramCredentialsSecretName: m5x63cee32ctiwo
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          nodeSelector:
            app: mongodb-replicaset
            namespace: staging
          tolerations:
          - key: "restriction"
            operator: "Equal"
            value: "mongo-staging-only-on-this-node"
            effect: "NoSchedule"
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: 1
                  memory: 8Gi
                limits:
                  memory: 16Gi
            - name: mongodb-agent
              resources:
                requests:
                  memory: 50Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: encrypted-gp2-xfs
            resources:
              requests:
                storage: 30Gi
```
