### ISSUE TITLE
Mongodb replicaset fails to initialize when using images 5.0.6 or 5.0.7

### ISSUE THREAD

**Issue by entitylabs** [mongodb/mongodb-kubernetes-operator#944]
**Environment Details :**
Vanilla Kubernetes on Bare metal.
version: 1.22

**Images used**

1. mongodb-agent:11.12.0.7388-1
2. mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4
3. mongodb-kubernetes-readinessprobe:1.0.8
4. mongodb/mongodb-kubernetes-operator:0.7.3
5. mongo:5.0.6 or mongo:5.0.7

**Behavior**
On installing mongodb via operator, no replica is initialized.

**Following is the log from mongod** 

_sudo kubectl get logs mongodb-replica-0 mongod -n mongo-database_

```
2022-04-12T12:56:28.793Z        INFO    versionhook/main.go:34  Running version change post-start hook
2022-04-12T12:56:28.793Z        INFO    versionhook/main.go:41  Waiting for agent health status...
2022-04-12T12:56:29.794Z        INFO    versionhook/main.go:77  Pod should not be deleted, mongod started
tail: cannot open '/var/log/mongodb-mms-automation/mongodb.log' for reading: No such file or directory

```

However, on using Mongo image **4.2.6 or 4.4.13** replicas are coming up perfectly.

**Images used**

1. mongodb-agent:11.12.0.7388-1
2. mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4
3. mongodb-kubernetes-readinessprobe:1.0.8
4. mongodb/mongodb-kubernetes-operator:0.7.3
5. mongo:4.2.6 or mongo:4.4.13-focal

Here are the contents of **/var/log/mongodb-mms-automation/** directory inside one replica and there is no **mongodb.log** here too.

This is the command used to enter pod

_sudo kubectl exec -it mongodb-replica-0 mongod -n mongo-database -- bash_

```
I have no name!@mongodb-replica-0:/var/log/mongodb-mms-automation$ ls -lrt
total 12
drwxr-xr-x 2 nobody nogroup 4096 Apr 12 13:05 healthstatus
-rw-r--r-- 1   2000 nogroup 5788 Apr 12 13:17 readiness.log

```

**Comment by priyolahiri** [comment]
Could you please provide the YAMLs for the deployment?

**Comment by entitylabs** [comment]
Here is the yaml used for deploying replica set

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replica
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: app-admin
      db: admin
      passwordSecretRef:
        name: admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      template:
        spec:
          initContainers:
          - command:
              - chown
              - -R
              - "2000"
              - /data
            image: busybox
            volumeMounts:
            - mountPath: /data
              name: data-volume
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
            name: change-dir-permissions
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce", "ReadWriteMany" ]
            resources:
              requests:
                storage: "10Gi"
            storageClassName:  "app-nfs-provisioner"
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce", "ReadWriteMany" ]
            resources:
              requests:
                storage: "10Gi"
            storageClassName: "app-nfs-provisioner"

      template:
        # Adds a custom volume to the pods
        spec:
          volumes:
            - name: custom-volume
              emptyDir: {}
          containers:
          - name: mongodb-agent
            volumeMounts:
              - name: custom-volume
                mountPath: /my-custom-version/mount-path
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-password
type: Opaque
stringData:
  password: "admin"
```


For volumes I am using a NFS provisoner.
