### ISSUE TITLE
Modify port error

### ISSUE THREAD

**Issue by jinchengsix** [mongodb/mongodb-kubernetes-operator#945]
**What did you do to encounter the bug?**
1. Deploy the operator and cluster as normal
2. Modify the port of the configuration file from the original default 27017 to 27018

**What did you expect?**
The cluster state is running and the new port 27018 is in effect

**What happened instead?**
The cluster status is running, the port is still 27017, and mongodb-agent reports an error
It says 【 Cannot simultaneously change multiple ports in the same deployment item. Please do one of them at a time.Both process = mongodb-0 and process = mongodb-1 changed ports.】

**Screenshots**
![image](https://user-images.githubusercontent.com/39333013/163404692-34e1b44d-94bc-436e-bcc3-514fc3d99388.png)
![image](https://user-images.githubusercontent.com/39333013/163404774-d073cb9e-9d11-4dd2-8e03-5baf806b43a3.png)
![image](https://user-images.githubusercontent.com/39333013/163404884-9318883c-9d6a-44d4-b334-f5c4bca64f63.png)

**Operator Information**
 - Operator v0.7.3
 - MongoDB 4.4.13

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**
cr.yaml
```
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 5
  type: ReplicaSet
  version: "4.4.13"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: shuaib
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    net:
      port: 27018
      maxIncomingConnections: 100000
    replication:
      oplogSizeMB: 2048

  statefulSet:
    spec:
      template:
        spec:
          initContainers:
            - name: mongod-posthook
              imagePullPolicy: IfNotPresent
            - name: mongodb-agent-readinessprobe
              imagePullPolicy: IfNotPresent
          containers:
            - name: mongod
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "8"
                  memory: 16G
                requests:
                  cpu: "8"
                  memory: 16G
            - name: mongodb-agent
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M


# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: echo1106

```

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods
