### ISSUE TITLE
Container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by radekknytl** [mongodb/mongodb-kubernetes-operator#952]
**What did you do to encounter the bug?**
Hello,
I have tried to deploy a MongoDB cluster using the operator (v0.7.3) on my Kubernetes cluster 1.22 but it failed during the Mongo cluster spin up with this error:

`Error: container has runAsNonRoot and image will run as root (pod: "mongodb-0_mongodb(e29ddd4d-aff8-43a8-9040-ee4bf168919a)", container: mongod-posthook)`

I have checked the quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4 docker image and it is not a non-root image. Is there a parameter which disable the runAsNonRoot validation? I have tried to search it in the documentation but without success.

**Full events log**
```bash
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Normal   Scheduled               32s                default-scheduler        Successfully assigned mongodb/mongodb-0 to vnc0008
  Normal   SuccessfulAttachVolume  27s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-268eaa35-96e6-4b78-ae3b-94dc3753da10"
  Normal   SuccessfulAttachVolume  23s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-702fda5b-d0ac-4b8e-85ff-8968084804c5"
  Normal   SuccessfulAttachVolume  19s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-94dd6cb3-1942-4d89-bd37-3f844d52c50d"
  Normal   Pulled                  19s                kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4" in 1.481840562s
  Normal   Pulled                  14s                kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4" in 1.589172071s
  Normal   SandboxChanged          13s (x2 over 19s)  kubelet                  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled                  10s                kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4" in 1.372046129s
  Normal   Pulling                 9s (x4 over 21s)   kubelet                  Pulling image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4"
  Warning  Failed                  8s (x4 over 19s)   kubelet                  Error: container has runAsNonRoot and image will run as root (pod: "mongodb-0_mongodb(e29ddd4d-aff8-43a8-9040-ee4bf168919a)", container: mongod-posthook)
  Normal   Pulled                  8s                 kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4" in 1.394893263s
```

**Operator Information**
 - Operator Version 0.7.3
 - MongoDB Image used 4.2.6
 - mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4

**Kubernetes Cluster Information**
 - Distribution Kubernetes
 - Version 1.22
 - Image Registry: quay

**operator.yaml**
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    email: support@mongodb.com
  labels:
    owner: mongodb
  name: mongodb-kubernetes-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-kubernetes-operator
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mongodb-kubernetes-operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - mongodb-kubernetes-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /usr/local/bin/entrypoint
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: mongodb-kubernetes-operator
        - name: AGENT_IMAGE
          value: quay.io/mongodb/mongodb-agent:11.12.0.7388-1
        - name: VERSION_UPGRADE_HOOK_IMAGE
          value: quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4
        - name: READINESS_PROBE_IMAGE
          value: quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.8
        - name: MONGODB_IMAGE
          value: mongo
        - name: MONGODB_REPO_URL
          value: docker.io
        image: quay.io/mongodb/mongodb-kubernetes-operator:0.7.3
        imagePullPolicy: Always
        name: mongodb-kubernetes-operator
        resources:
          limits:
            cpu: 1100m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 200Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 2000
          allowPrivilegeEscalation: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: mongodb-kubernetes-operator
```

mongodb.yaml
```yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
  - name: admin-user
    db: admin
    passwordSecretRef:
      name: admin-user-password
    roles:
    - name: clusterAdmin
      db: admin
    - name: userAdminAnyDatabase
      db: admin
    scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "1"
                  memory: 2Gi
                requests:
                  cpu: 500m
                  memory: 1Gi
      volumeClaimTemplates:
        - metadata:
            name: data-volume-mongodb-0
          spec:
            accessModes: [ "ReadWriteOnce", "ReadWriteMany" ]
            resources:
              requests:
                storage: 10Gi
```

**Comment by radekknytl** [comment]
Problem solved.

Solution: Add an initContainers template with the runAsUser propertyt in the mongodb.yaml as shown below:

```yaml
  statefulSet:
    spec:
      template:
        spec:
          initContainers:
            - name: mongod-posthook
              securityContext:
                runAsNonRoot: true
                runAsUser: 1001
```

**Comment by cortopy** [comment]
This is what worked for me:

```yaml
  statefulSet:
    spec:
      template:
        spec:
          initContainers:
            - name: mongod-posthook
              securityContext:
                runAsNonRoot: true
                runAsUser: 2000
            - name:  mongodb-agent-readinessprobe
              securityContext:
                runAsNonRoot: true
                runAsUser: 2000
          containers:
            - name: mongod
              securityContext:
                runAsNonRoot: true
                runAsUser: 2000
```
