### ISSUE TITLE
Custom StorageClass  Configuration

### ISSUE THREAD

**Issue by Daxcor69** [mongodb/mongodb-kubernetes-operator#961]
**What did you do to encounter the bug?**
I did a default operator install with the provided yaml
`mongodb.com_v1_mongodbcommunity_cr.yaml`

**What did you expect?**
I was expecting the option to specify the storage class but found no reference in the yaml or in the docs.

**What happened instead?**
The db deployment was stalled pending pvc creation.  Creation was held up due to no storageclass being specified.

**Operator Information**
 - Operator Version
latest
 - MongoDB Image used
5.0.8

**Kubernetes Cluster Information**
 - Distribution
kubeadm
 - Version
 - 1.23.6
 - Image Registry location (quay, or an internal registry)

**Additional context**
I was able to manually create the pvc's and the replica set spun right up.  Not sure, but I think this is more of a documentation issue than anything.

**Comment by dasantonym** [comment]
This worked for me:

```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
spec:
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: openebs-zfspv
            resources:
              requests:
                storage: 10G
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: openebs-zfspv
            resources:
              requests:
                storage: 2G
```

Found it here: https://github.com/mongodb/mongodb-kubernetes-operator/pull/157
