### ISSUE TITLE
It is not possible to adjust arbiter's resource limits separately from cluster nodes

### ISSUE THREAD

**Issue by anikievev** [mongodb/mongodb-kubernetes-operator#962]
We can not adjust resource limits for arbiter itself. Currently, it is just wasting resources, because we need arbiter  only for election

Expected behavior: 
We should be able to adjust it separately.

Currently, we use such yaml:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  members: 2
  arbiters: 1
  security:
    authentication:
      ignoreUnknownUsers: true
      modes:
      - SCRAM
  type: ReplicaSet
  users:
  - db: admin
    name: user
    passwordSecretRef:
      name: user-password
    roles:
    - db: admin
      name: clusterAdmin
    - db: admin
      name: userAdminAnyDatabase

    scramCredentialsSecretName: my-scram
  
  statefulSet:
    spec:
      template:
        spec:
          # resources can be specified by applying an override
          # per container name.
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "8"
                  memory: 32G
                requests:
                  cpu: "8"
                  memory: 32G
  version: 4.4.13

```
