### ISSUE TITLE
connectionStringSecretName not working

### ISSUE THREAD

**Issue by bygui86** [mongodb/mongodb-kubernetes-operator#973]
**What did you do to encounter the bug?**
1. Deploy a simple MongoDBCommunity with a custom value in a `connectionStringSecretName` of any user
2. Wait until MongoDB replicaset is ready
3. Look for k8s Secret containing connection string, but not found

**What did you expect?**
Find the k8s Secret containing connection string with the right name specified in the `connectionStringSecretName` field in the definition of the MongoDBCommunity.

**What happened instead?**
k8s Secret gets created with the default name `<mongodbcommunity-obj-name>-<db-name>-<username>`.

**Screenshots**

**Operator Information**
 - Operator Version: `0.7.3`
 - MongoDB Image used: `4.4.1` and `5.0.8`

**Kubernetes Cluster Information**
 - Distribution: `Minikube`
 - Version: `1.23.2`
 - Image Registry location: `quay`

**Additional context**
All other user secrets were created properly with all custom names.

We need the `connectionStringSecretName` option as our DB names contains invalid k8s characters (e.g. "_").

MongoDBCommunity yaml:
```yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mst-mongodb
spec:
  type: ReplicaSet
  members: 3
  version: "4.4.1"
  security:
    authentication:
      modes:
        - SCRAM
      ignoreUnknownUsers: false
  users:
    - name: mst-reader
      db: market_state
      passwordSecretRef:
        name: mst-mongodb-mst-reader
        key: password
      roles:
        - name: read
          db: market_state
      scramCredentialsSecretName: mst-reader
      connectionStringSecretName: mst-mongodb-market-state-mst-reader-conn-string
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 500m
                  memory: 1Gi
            - name: mongodb-agent
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              readinessProbe:
                failureThreshold: 50
                initialDelaySeconds: 10
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 3Gi
  prometheus:
    username: prometheus
    passwordSecretRef:
      name: mst-mongodb-metrics
      key: password
```

[operator-logs.log](https://github.com/mongodb/mongodb-kubernetes-operator/files/8677363/operator-logs.log)
