### ISSUE TITLE
Cannot create index on non-empty collection when ReplicaSet has more than 2 members

### ISSUE THREAD

**Issue by arthursantana** [mongodb/mongodb-kubernetes-operator#988]
**What did you do to encounter the bug?**
1. Create a MongoDBCommunity object instance with 3 members
2. Create a collection and add data
3. Create an index for this collection

**What did you expect?**
For the index to be created normally.

**What happened instead?**
The operation never finishes. There is no extra resource consumption.

**Operator Information**
 - Operator Version: v0.7.1
 - MongoDB Image used: 5.0.0

**Kubernetes Cluster Information**
 - Distribution: AKS
 - Version: 1.22.6
 - Image Registry location: quay.io

**Additional context**
If the number of members is reduced to 2, I can create the index. If there is no data in the collection, I can create the index.

The object definition is as follows:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: <REDACTED>
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: analytics-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.0"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          nodeSelector:
            type: MongoDB
          volumes:
            - name: mongokeyfile
              secret:
                secretName: mongokeyfile
                items:
                  - key: "mongo.keyfile"
                    path: "mongo.keyfile"
          containers:
            - name: mongod
              #entrypoint: "mongod --keyFile /keyfile/mongo.keyfile -f /data/automation-mongod.conf"
              resources:
                limits:
                  cpu: "3.4"
                  memory: 12500M
                requests:
                  cpu: "3.4"
                  memory: 12500M
              volumeMounts:
                - name: mongokeyfile
                  mountPath: "/keyfile"
                  readOnly: true
            - name: mongodb-agent
              resources:
                limits:
                  cpu: ".15"
                  memory: 100M
                requests:
                  cpu: ".15"
                  memory: 100M
              readinessProbe:
                exec:
                  command:
                  - "true"
                initialDelaySeconds: 0
                periodSeconds: 1
                successThreshold: 1
                timeoutSeconds: 5
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            storageClassName: "azuredisk-premium"
            resources:
              requests:
                storage: 512Gi
```

The options for `mongokeyfile` are not currently being used, I was using them to try to fix this problem, but didn't manage yet to configure the mongo command line options through the operator.

The readiness probe is being bypassed because of  issue https://github.com/mongodb/mongodb-kubernetes-operator/issues/912 .

Pasting logs here is impractical because the problem is happening in a production server.
