### ISSUE TITLE
Readiness probe failed: panic: open /var/lib/automation/config/acVersion/version: no such file or directory

### ISSUE THREAD

**Issue by itaytalmi** [mongodb/mongodb-kubernetes-operator#989]
**What did you do to encounter the bug?**

1. Deployed the Operator Helm Chart using default values, except for:2. 

```yaml
operator:
  watchNamespace: app-ns
```

2. Deployed a simple Replica Set using the following manifest:3. 

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
  namespace: app-ns
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replica-set
  namespace: app-ns
spec:
  members: 3
  type: ReplicaSet
  version: "5.0.8"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef:
        name: mongodb-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-password
  namespace: app-ns
type: Opaque
stringData:
  password: P@ssw0rd
```

**What did you expect?**

Expected the Replica Set to deploy.

**What happened instead?**
A clear and concise description of what happened instead

The Replica Set is stuck in the `Pending` state because the first pod is unable to start.

In the output of `kubectl describe pod mongodb-replica-set-0 -n app-ns` I see the following issue:

```text
...
Events:
  Type     Reason     Age                      From     Message
  ----     ------     ----                     ----     -------
  Warning  Unhealthy  3m21s (x1019 over 153m)  kubelet  Readiness probe failed: panic: open /var/lib/automation/config/acVersion/version: no such file or directory

goroutine 1 [running]:
main.main()
  /build/main.go:225 +0x14b
```

Additional information:

Output of `kubectl get pod -n mongodb-system` (where the operator is deployed):

```text
NAME                                           READY   STATUS    RESTARTS   AGE
mongodb-kubernetes-operator-79976894db-9h56s   1/1     Running   0          3h11m
```

Output of `kubectl get mongodbcommunity.mongodbcommunity.mongodb.com -n app-ns`:

```text
NAME                  PHASE     VERSION
mongodb-replica-set   Pending
```

Output of `kubectl get pod -n app-ns` (where the Replica Set is deployed):

```text
NAME                    READY   STATUS    RESTARTS   AGE
mongodb-replica-set-0   1/2     Running   0          155m
```

Output of `kubectl get endpoints -n app-ns`:

```text
NAME                          ENDPOINTS                                                           AGE
mongodb-replica-set-arb-svc   <none>                                                              154m
mongodb-replica-set-svc       100.96.1.94:27017                                                   154m
```

**Screenshots**

I think the above outputs are sufficient.

**Operator Information**
 - Operator Version: `0.7.3`
 - MongoDB Image used: `5.0.8`

**Kubernetes Cluster Information**
 - Distribution: `VMware Tanzu Kubernetes Grid`
 - Version: `1.22.8`
 - Image Registry location (quay, or an internal registry): `private registry - Harbor`

**Additional context**

If possible, please include:
 - `kubectl describe` output: see above outputs
 - yaml definitions for your objects: see above outputs
 - log files for the operator and database pods: see above outputs

**Comment by Brice187** [comment]
https://github.com/mongodb/mongodb-kubernetes-operator/issues/949

**Comment by priyolahiri** [comment]
We are currently looking into this issue and hope to have a resolution soon.

**Comment by irajdeep** [comment]
>  I've managed to narrow this down - when the operator and the Replica Set are deployed in the same namespace, everything is fine. When they're not, I keep getting the ReadinessProbe issue above.

Hi @itaytalmi could you please check in the `database namespace` that the service-account `mongodb-database` and the role/rolebinding `mongodb-database` are present. You can also find them here: https://github.com/mongodb/mongodb-kubernetes-operator/tree/master/config/rbac

**Comment by itaytalmi** [comment]
Hi @irajdeep, thanks for your response, I've just checked. I actually suspected it might be related to RBAC somehow.

Here is the output of `kubectl get sa,role,rolebinding -n app-ns` (the database resides in the `app-ns` namespace):

```text
$ kubectl get sa,role,rolebinding -n app-ns

NAME                     SECRETS   AGE
serviceaccount/default   1         2m4s

NAME                                                         CREATED AT
role.rbac.authorization.k8s.io/mongodb-kubernetes-operator   2022-06-09T11:32:22Z

NAME                                                                ROLE                               AGE
rolebinding.rbac.authorization.k8s.io/mongodb-kubernetes-operator   Role/mongodb-kubernetes-operator   85s
```

Looks like the `mongodb-database` service account, role and role binding are missing in the database namespace.

I created my own RBAC.yaml containing the service account, role and role binding in the database namespace:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-database
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
  - delete
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-database
subjects:
- kind: ServiceAccount
  name: mongodb-database
```

Applied it using `kubectl apply -f rbac.yaml -n app-ns`

Then deleted the database using `kubectl delete -f mongodb-replica-set.yaml` and redeployed using `kubectl apply -f mongodb-replica-set.yaml`

And the database started successfully.

```text
$ kubectl get mongodbcommunity.mongodbcommunity.mongodb.com -n app-ns

NAME                  PHASE     VERSION
mongodb-replica-set   Running   5.0.8

$ kubectl get pods -n app-ns
NAME                    READY   STATUS    RESTARTS   AGE
mongodb-replica-set-0   2/2     Running   0          4m9s
```
